// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: academics.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const clearCurrentTerm = `-- name: ClearCurrentTerm :exec
UPDATE terms SET is_current = false WHERE is_current
`

func (q *Queries) ClearCurrentTerm(ctx context.Context) error {
	_, err := q.db.Exec(ctx, clearCurrentTerm)
	return err
}

const clearCurrentYear = `-- name: ClearCurrentYear :exec
UPDATE academic_years SET is_current = false WHERE is_current
`

// Cleared first and set second, in the same transaction: one statement cannot
// both drop and take the only-current index without colliding with itself.
func (q *Queries) ClearCurrentYear(ctx context.Context) error {
	_, err := q.db.Exec(ctx, clearCurrentYear)
	return err
}

const createAcademicYear = `-- name: CreateAcademicYear :one
INSERT INTO academic_years (tenant_id, name, starts_on, ends_on)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, name, starts_on, ends_on, is_current, created_at, updated_at
`

type CreateAcademicYearParams struct {
	TenantID uuid.UUID   `json:"tenant_id"`
	Name     string      `json:"name"`
	StartsOn pgtype.Date `json:"starts_on"`
	EndsOn   pgtype.Date `json:"ends_on"`
}

func (q *Queries) CreateAcademicYear(ctx context.Context, arg CreateAcademicYearParams) (AcademicYear, error) {
	row := q.db.QueryRow(ctx, createAcademicYear,
		arg.TenantID,
		arg.Name,
		arg.StartsOn,
		arg.EndsOn,
	)
	var i AcademicYear
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.StartsOn,
		&i.EndsOn,
		&i.IsCurrent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createClass = `-- name: CreateClass :one
INSERT INTO classes (tenant_id, name, rank) VALUES ($1, $2, $3) RETURNING id, tenant_id, name, rank, created_at, updated_at
`

type CreateClassParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Name     string    `json:"name"`
	Rank     int32     `json:"rank"`
}

func (q *Queries) CreateClass(ctx context.Context, arg CreateClassParams) (Class, error) {
	row := q.db.QueryRow(ctx, createClass, arg.TenantID, arg.Name, arg.Rank)
	var i Class
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Rank,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSection = `-- name: CreateSection :one
INSERT INTO sections (tenant_id, class_id, name, capacity, teacher_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, class_id, name, capacity, teacher_id, created_at, updated_at
`

type CreateSectionParams struct {
	TenantID  uuid.UUID     `json:"tenant_id"`
	ClassID   uuid.UUID     `json:"class_id"`
	Name      string        `json:"name"`
	Capacity  *int32        `json:"capacity"`
	TeacherID uuid.NullUUID `json:"teacher_id"`
}

func (q *Queries) CreateSection(ctx context.Context, arg CreateSectionParams) (Section, error) {
	row := q.db.QueryRow(ctx, createSection,
		arg.TenantID,
		arg.ClassID,
		arg.Name,
		arg.Capacity,
		arg.TeacherID,
	)
	var i Section
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ClassID,
		&i.Name,
		&i.Capacity,
		&i.TeacherID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSubject = `-- name: CreateSubject :one
INSERT INTO subjects (tenant_id, class_id, name, code, dir)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, class_id, name, code, dir, created_at, updated_at
`

type CreateSubjectParams struct {
	TenantID uuid.UUID     `json:"tenant_id"`
	ClassID  uuid.NullUUID `json:"class_id"`
	Name     string        `json:"name"`
	Code     string        `json:"code"`
	Dir      TextDir       `json:"dir"`
}

func (q *Queries) CreateSubject(ctx context.Context, arg CreateSubjectParams) (Subject, error) {
	row := q.db.QueryRow(ctx, createSubject,
		arg.TenantID,
		arg.ClassID,
		arg.Name,
		arg.Code,
		arg.Dir,
	)
	var i Subject
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ClassID,
		&i.Name,
		&i.Code,
		&i.Dir,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTerm = `-- name: CreateTerm :one
INSERT INTO terms (tenant_id, year_id, name, starts_on, ends_on)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, year_id, name, starts_on, ends_on, is_current, created_at, updated_at
`

type CreateTermParams struct {
	TenantID uuid.UUID   `json:"tenant_id"`
	YearID   uuid.UUID   `json:"year_id"`
	Name     string      `json:"name"`
	StartsOn pgtype.Date `json:"starts_on"`
	EndsOn   pgtype.Date `json:"ends_on"`
}

func (q *Queries) CreateTerm(ctx context.Context, arg CreateTermParams) (Term, error) {
	row := q.db.QueryRow(ctx, createTerm,
		arg.TenantID,
		arg.YearID,
		arg.Name,
		arg.StartsOn,
		arg.EndsOn,
	)
	var i Term
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.YearID,
		&i.Name,
		&i.StartsOn,
		&i.EndsOn,
		&i.IsCurrent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const currentTerm = `-- name: CurrentTerm :one
SELECT id, tenant_id, year_id, name, starts_on, ends_on, is_current, created_at, updated_at FROM terms WHERE is_current
`

func (q *Queries) CurrentTerm(ctx context.Context) (Term, error) {
	row := q.db.QueryRow(ctx, currentTerm)
	var i Term
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.YearID,
		&i.Name,
		&i.StartsOn,
		&i.EndsOn,
		&i.IsCurrent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const currentYear = `-- name: CurrentYear :one
SELECT id, tenant_id, name, starts_on, ends_on, is_current, created_at, updated_at FROM academic_years WHERE is_current
`

func (q *Queries) CurrentYear(ctx context.Context) (AcademicYear, error) {
	row := q.db.QueryRow(ctx, currentYear)
	var i AcademicYear
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.StartsOn,
		&i.EndsOn,
		&i.IsCurrent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAcademicYear = `-- name: DeleteAcademicYear :execrows
DELETE FROM academic_years WHERE id = $1
`

func (q *Queries) DeleteAcademicYear(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAcademicYear, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteClass = `-- name: DeleteClass :execrows
DELETE FROM classes WHERE id = $1
`

func (q *Queries) DeleteClass(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteClass, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSection = `-- name: DeleteSection :execrows
DELETE FROM sections WHERE id = $1
`

func (q *Queries) DeleteSection(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSection, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSubject = `-- name: DeleteSubject :execrows
DELETE FROM subjects WHERE id = $1
`

func (q *Queries) DeleteSubject(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSubject, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTerm = `-- name: DeleteTerm :execrows
DELETE FROM terms WHERE id = $1
`

func (q *Queries) DeleteTerm(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTerm, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listAcademicYears = `-- name: ListAcademicYears :many
SELECT id, tenant_id, name, starts_on, ends_on, is_current, created_at, updated_at FROM academic_years ORDER BY starts_on DESC
`

func (q *Queries) ListAcademicYears(ctx context.Context) ([]AcademicYear, error) {
	rows, err := q.db.Query(ctx, listAcademicYears)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AcademicYear{}
	for rows.Next() {
		var i AcademicYear
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.StartsOn,
			&i.EndsOn,
			&i.IsCurrent,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClasses = `-- name: ListClasses :many
SELECT id, tenant_id, name, rank, created_at, updated_at FROM classes ORDER BY rank, name
`

func (q *Queries) ListClasses(ctx context.Context) ([]Class, error) {
	rows, err := q.db.Query(ctx, listClasses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Class{}
	for rows.Next() {
		var i Class
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Rank,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSectionRoll = `-- name: ListSectionRoll :many
SELECT p.id, p.tenant_id, p.year_id, p.section_id, p.user_id, p.roll_no, p.created_at, u.full_name, u.phone, u.email
FROM placements p JOIN users u ON u.id = p.user_id
WHERE p.section_id = $1
ORDER BY p.roll_no NULLS LAST, u.full_name
`

type ListSectionRollRow struct {
	Placement Placement `json:"placement"`
	FullName  string    `json:"full_name"`
	Phone     *string   `json:"phone"`
	Email     *string   `json:"email"`
}

func (q *Queries) ListSectionRoll(ctx context.Context, sectionID uuid.UUID) ([]ListSectionRollRow, error) {
	rows, err := q.db.Query(ctx, listSectionRoll, sectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSectionRollRow{}
	for rows.Next() {
		var i ListSectionRollRow
		if err := rows.Scan(
			&i.Placement.ID,
			&i.Placement.TenantID,
			&i.Placement.YearID,
			&i.Placement.SectionID,
			&i.Placement.UserID,
			&i.Placement.RollNo,
			&i.Placement.CreatedAt,
			&i.FullName,
			&i.Phone,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSections = `-- name: ListSections :many
SELECT s.id, s.tenant_id, s.class_id, s.name, s.capacity, s.teacher_id, s.created_at, s.updated_at, c.name AS class_name, u.full_name AS teacher_name,
       (SELECT count(*) FROM placements p WHERE p.section_id = s.id) AS students
FROM sections s
JOIN classes c ON c.id = s.class_id
LEFT JOIN users u ON u.id = s.teacher_id
ORDER BY c.rank, c.name, s.name
`

type ListSectionsRow struct {
	Section     Section `json:"section"`
	ClassName   string  `json:"class_name"`
	TeacherName *string `json:"teacher_name"`
	Students    int64   `json:"students"`
}

func (q *Queries) ListSections(ctx context.Context) ([]ListSectionsRow, error) {
	rows, err := q.db.Query(ctx, listSections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSectionsRow{}
	for rows.Next() {
		var i ListSectionsRow
		if err := rows.Scan(
			&i.Section.ID,
			&i.Section.TenantID,
			&i.Section.ClassID,
			&i.Section.Name,
			&i.Section.Capacity,
			&i.Section.TeacherID,
			&i.Section.CreatedAt,
			&i.Section.UpdatedAt,
			&i.ClassName,
			&i.TeacherName,
			&i.Students,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubjects = `-- name: ListSubjects :many
SELECT s.id, s.tenant_id, s.class_id, s.name, s.code, s.dir, s.created_at, s.updated_at, c.name AS class_name
FROM subjects s LEFT JOIN classes c ON c.id = s.class_id
ORDER BY c.rank NULLS FIRST, s.name
`

type ListSubjectsRow struct {
	Subject   Subject `json:"subject"`
	ClassName *string `json:"class_name"`
}

func (q *Queries) ListSubjects(ctx context.Context) ([]ListSubjectsRow, error) {
	rows, err := q.db.Query(ctx, listSubjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubjectsRow{}
	for rows.Next() {
		var i ListSubjectsRow
		if err := rows.Scan(
			&i.Subject.ID,
			&i.Subject.TenantID,
			&i.Subject.ClassID,
			&i.Subject.Name,
			&i.Subject.Code,
			&i.Subject.Dir,
			&i.Subject.CreatedAt,
			&i.Subject.UpdatedAt,
			&i.ClassName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTerms = `-- name: ListTerms :many
SELECT id, tenant_id, year_id, name, starts_on, ends_on, is_current, created_at, updated_at FROM terms WHERE year_id = $1 ORDER BY starts_on
`

func (q *Queries) ListTerms(ctx context.Context, yearID uuid.UUID) ([]Term, error) {
	rows, err := q.db.Query(ctx, listTerms, yearID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Term{}
	for rows.Next() {
		var i Term
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.YearID,
			&i.Name,
			&i.StartsOn,
			&i.EndsOn,
			&i.IsCurrent,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const makeTermCurrent = `-- name: MakeTermCurrent :one
UPDATE terms SET is_current = true WHERE id = $1 RETURNING id, tenant_id, year_id, name, starts_on, ends_on, is_current, created_at, updated_at
`

func (q *Queries) MakeTermCurrent(ctx context.Context, id uuid.UUID) (Term, error) {
	row := q.db.QueryRow(ctx, makeTermCurrent, id)
	var i Term
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.YearID,
		&i.Name,
		&i.StartsOn,
		&i.EndsOn,
		&i.IsCurrent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const makeYearCurrent = `-- name: MakeYearCurrent :one
UPDATE academic_years SET is_current = true WHERE id = $1 RETURNING id, tenant_id, name, starts_on, ends_on, is_current, created_at, updated_at
`

func (q *Queries) MakeYearCurrent(ctx context.Context, id uuid.UUID) (AcademicYear, error) {
	row := q.db.QueryRow(ctx, makeYearCurrent, id)
	var i AcademicYear
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.StartsOn,
		&i.EndsOn,
		&i.IsCurrent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const placeStudent = `-- name: PlaceStudent :one
INSERT INTO placements (tenant_id, year_id, section_id, user_id, roll_no)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (year_id, user_id) DO UPDATE
SET section_id = excluded.section_id, roll_no = excluded.roll_no
RETURNING id, tenant_id, year_id, section_id, user_id, roll_no, created_at
`

type PlaceStudentParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	YearID    uuid.UUID `json:"year_id"`
	SectionID uuid.UUID `json:"section_id"`
	UserID    uuid.UUID `json:"user_id"`
	RollNo    *int32    `json:"roll_no"`
}

func (q *Queries) PlaceStudent(ctx context.Context, arg PlaceStudentParams) (Placement, error) {
	row := q.db.QueryRow(ctx, placeStudent,
		arg.TenantID,
		arg.YearID,
		arg.SectionID,
		arg.UserID,
		arg.RollNo,
	)
	var i Placement
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.YearID,
		&i.SectionID,
		&i.UserID,
		&i.RollNo,
		&i.CreatedAt,
	)
	return i, err
}

const removePlacement = `-- name: RemovePlacement :execrows
DELETE FROM placements WHERE id = $1
`

func (q *Queries) RemovePlacement(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, removePlacement, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const studentPlacement = `-- name: StudentPlacement :one
SELECT p.id, p.tenant_id, p.year_id, p.section_id, p.user_id, p.roll_no, p.created_at, s.name AS section_name, c.name AS class_name, y.name AS year_name
FROM placements p
JOIN sections s ON s.id = p.section_id
JOIN classes c ON c.id = s.class_id
JOIN academic_years y ON y.id = p.year_id
WHERE p.user_id = $1 AND y.is_current
`

type StudentPlacementRow struct {
	Placement   Placement `json:"placement"`
	SectionName string    `json:"section_name"`
	ClassName   string    `json:"class_name"`
	YearName    string    `json:"year_name"`
}

func (q *Queries) StudentPlacement(ctx context.Context, userID uuid.UUID) (StudentPlacementRow, error) {
	row := q.db.QueryRow(ctx, studentPlacement, userID)
	var i StudentPlacementRow
	err := row.Scan(
		&i.Placement.ID,
		&i.Placement.TenantID,
		&i.Placement.YearID,
		&i.Placement.SectionID,
		&i.Placement.UserID,
		&i.Placement.RollNo,
		&i.Placement.CreatedAt,
		&i.SectionName,
		&i.ClassName,
		&i.YearName,
	)
	return i, err
}

const updateClass = `-- name: UpdateClass :one
UPDATE classes SET
  name = coalesce($1, name),
  rank = coalesce($2, rank)
WHERE id = $3
RETURNING id, tenant_id, name, rank, created_at, updated_at
`

type UpdateClassParams struct {
	Name *string   `json:"name"`
	Rank *int32    `json:"rank"`
	ID   uuid.UUID `json:"id"`
}

func (q *Queries) UpdateClass(ctx context.Context, arg UpdateClassParams) (Class, error) {
	row := q.db.QueryRow(ctx, updateClass, arg.Name, arg.Rank, arg.ID)
	var i Class
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Rank,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSection = `-- name: UpdateSection :one
UPDATE sections SET
  name       = coalesce($1, name),
  capacity   = CASE WHEN $2::boolean THEN $3 ELSE capacity END,
  teacher_id = CASE WHEN $4::boolean THEN $5 ELSE teacher_id END
WHERE id = $6
RETURNING id, tenant_id, class_id, name, capacity, teacher_id, created_at, updated_at
`

type UpdateSectionParams struct {
	Name        *string       `json:"name"`
	SetCapacity bool          `json:"set_capacity"`
	Capacity    *int32        `json:"capacity"`
	SetTeacher  bool          `json:"set_teacher"`
	TeacherID   uuid.NullUUID `json:"teacher_id"`
	ID          uuid.UUID     `json:"id"`
}

func (q *Queries) UpdateSection(ctx context.Context, arg UpdateSectionParams) (Section, error) {
	row := q.db.QueryRow(ctx, updateSection,
		arg.Name,
		arg.SetCapacity,
		arg.Capacity,
		arg.SetTeacher,
		arg.TeacherID,
		arg.ID,
	)
	var i Section
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ClassID,
		&i.Name,
		&i.Capacity,
		&i.TeacherID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
