// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const adminLeads = `-- name: AdminLeads :many
SELECT id, full_name, email, phone, organisation, role, learners, runs, note, created_at, state, worked_note FROM admin_leads($1, $2, $3, $4)
`

type AdminLeadsParams struct {
	State    string `json:"state"`
	Query    string `json:"query"`
	LimitTo  int32  `json:"limit_to"`
	OffsetBy int32  `json:"offset_by"`
}

func (q *Queries) AdminLeads(ctx context.Context, arg AdminLeadsParams) ([]DemoLead, error) {
	rows, err := q.db.Query(ctx, adminLeads,
		arg.State,
		arg.Query,
		arg.LimitTo,
		arg.OffsetBy,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DemoLead{}
	for rows.Next() {
		var i DemoLead
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Email,
			&i.Phone,
			&i.Organisation,
			&i.Role,
			&i.Learners,
			&i.Runs,
			&i.Note,
			&i.CreatedAt,
			&i.State,
			&i.WorkedNote,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminOverview = `-- name: AdminOverview :one
SELECT admin_overview FROM admin_overview()
`

func (q *Queries) AdminOverview(ctx context.Context) ([]byte, error) {
	row := q.db.QueryRow(ctx, adminOverview)
	var admin_overview []byte
	err := row.Scan(&admin_overview)
	return admin_overview, err
}

const adminSetLead = `-- name: AdminSetLead :one
SELECT id, full_name, email, phone, organisation, role, learners, runs, note, created_at, state, worked_note FROM admin_set_lead($1, $2, $3)
`

type AdminSetLeadParams struct {
	ID    uuid.UUID `json:"id"`
	State string    `json:"state"`
	Note  string    `json:"note"`
}

func (q *Queries) AdminSetLead(ctx context.Context, arg AdminSetLeadParams) (DemoLead, error) {
	row := q.db.QueryRow(ctx, adminSetLead, arg.ID, arg.State, arg.Note)
	var i DemoLead
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.Phone,
		&i.Organisation,
		&i.Role,
		&i.Learners,
		&i.Runs,
		&i.Note,
		&i.CreatedAt,
		&i.State,
		&i.WorkedNote,
	)
	return i, err
}

const adminTenant = `-- name: AdminTenant :one
SELECT admin_tenant FROM admin_tenant($1)
`

func (q *Queries) AdminTenant(ctx context.Context, tenantID uuid.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, adminTenant, tenantID)
	var admin_tenant []byte
	err := row.Scan(&admin_tenant)
	return admin_tenant, err
}

const adminTenants = `-- name: AdminTenants :one
SELECT admin_tenants FROM admin_tenants($1, $2, $3)
`

type AdminTenantsParams struct {
	Query    string `json:"query"`
	LimitTo  int32  `json:"limit_to"`
	OffsetBy int32  `json:"offset_by"`
}

func (q *Queries) AdminTenants(ctx context.Context, arg AdminTenantsParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, adminTenants, arg.Query, arg.LimitTo, arg.OffsetBy)
	var admin_tenants []byte
	err := row.Scan(&admin_tenants)
	return admin_tenants, err
}

const logStaffAction = `-- name: LogStaffAction :exec
SELECT staff_log($1, $2, $3, $4)
`

type LogStaffActionParams struct {
	UserID  uuid.UUID `json:"user_id"`
	Action  string    `json:"action"`
	Subject string    `json:"subject"`
	Detail  string    `json:"detail"`
}

func (q *Queries) LogStaffAction(ctx context.Context, arg LogStaffActionParams) error {
	_, err := q.db.Exec(ctx, logStaffAction,
		arg.UserID,
		arg.Action,
		arg.Subject,
		arg.Detail,
	)
	return err
}

const staffByEmail = `-- name: StaffByEmail :one
SELECT user_id, role, password_hash, created_at, last_seen_at FROM staff_by_email($1)
`

func (q *Queries) StaffByEmail(ctx context.Context, email string) (PlatformStaff, error) {
	row := q.db.QueryRow(ctx, staffByEmail, email)
	var i PlatformStaff
	err := row.Scan(
		&i.UserID,
		&i.Role,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const staffRole = `-- name: StaffRole :one
SELECT staff_role FROM staff_role($1)
`

func (q *Queries) StaffRole(ctx context.Context, userID uuid.UUID) (*string, error) {
	row := q.db.QueryRow(ctx, staffRole, userID)
	var staff_role *string
	err := row.Scan(&staff_role)
	return staff_role, err
}

const touchStaff = `-- name: TouchStaff :exec
SELECT staff_seen($1)
`

func (q *Queries) TouchStaff(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchStaff, userID)
	return err
}
