// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assessment.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const attemptSheet = `-- name: AttemptSheet :many
SELECT q.id, q.tenant_id, q.quiz_id, q.kind, q.prompt, q.dir, q.points, q.explanation, q.position, q.created_at, q.updated_at, ans.option_ids, ans.text_answer, ans.points_awarded,
       ans.needs_grading, ans.feedback
FROM questions q
LEFT JOIN attempt_answers ans ON ans.question_id = q.id AND ans.attempt_id = $1
WHERE q.quiz_id = $2
ORDER BY q.position
`

type AttemptSheetParams struct {
	AttemptID uuid.UUID `json:"attempt_id"`
	QuizID    uuid.UUID `json:"quiz_id"`
}

type AttemptSheetRow struct {
	Question      Question    `json:"question"`
	OptionIds     []uuid.UUID `json:"option_ids"`
	TextAnswer    *string     `json:"text_answer"`
	PointsAwarded *int32      `json:"points_awarded"`
	NeedsGrading  *bool       `json:"needs_grading"`
	Feedback      *string     `json:"feedback"`
}

// Everything a marker needs for one attempt, answer key included.
func (q *Queries) AttemptSheet(ctx context.Context, arg AttemptSheetParams) ([]AttemptSheetRow, error) {
	rows, err := q.db.Query(ctx, attemptSheet, arg.AttemptID, arg.QuizID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AttemptSheetRow{}
	for rows.Next() {
		var i AttemptSheetRow
		if err := rows.Scan(
			&i.Question.ID,
			&i.Question.TenantID,
			&i.Question.QuizID,
			&i.Question.Kind,
			&i.Question.Prompt,
			&i.Question.Dir,
			&i.Question.Points,
			&i.Question.Explanation,
			&i.Question.Position,
			&i.Question.CreatedAt,
			&i.Question.UpdatedAt,
			&i.OptionIds,
			&i.TextAnswer,
			&i.PointsAwarded,
			&i.NeedsGrading,
			&i.Feedback,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countAttempts = `-- name: CountAttempts :one
SELECT count(*) FROM quiz_attempts WHERE quiz_id = $1 AND user_id = $2
`

type CountAttemptsParams struct {
	QuizID uuid.UUID `json:"quiz_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) CountAttempts(ctx context.Context, arg CountAttemptsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAttempts, arg.QuizID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOption = `-- name: CreateOption :one
INSERT INTO question_options (tenant_id, question_id, label, is_correct, position)
VALUES ($1, $2, $3, $4,
        coalesce((SELECT max(position) + 1024 FROM question_options WHERE question_id = $2), 1024))
RETURNING id, tenant_id, question_id, label, is_correct, position
`

type CreateOptionParams struct {
	TenantID   uuid.UUID `json:"tenant_id"`
	QuestionID uuid.UUID `json:"question_id"`
	Label      string    `json:"label"`
	IsCorrect  bool      `json:"is_correct"`
}

func (q *Queries) CreateOption(ctx context.Context, arg CreateOptionParams) (QuestionOption, error) {
	row := q.db.QueryRow(ctx, createOption,
		arg.TenantID,
		arg.QuestionID,
		arg.Label,
		arg.IsCorrect,
	)
	var i QuestionOption
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.QuestionID,
		&i.Label,
		&i.IsCorrect,
		&i.Position,
	)
	return i, err
}

const createQuestion = `-- name: CreateQuestion :one
INSERT INTO questions (tenant_id, quiz_id, kind, prompt, dir, points, explanation, position)
VALUES ($1, $2, $3, $4, $5, $6, $7,
        coalesce((SELECT max(position) + 1024 FROM questions WHERE quiz_id = $2), 1024))
RETURNING id, tenant_id, quiz_id, kind, prompt, dir, points, explanation, position, created_at, updated_at
`

type CreateQuestionParams struct {
	TenantID    uuid.UUID    `json:"tenant_id"`
	QuizID      uuid.UUID    `json:"quiz_id"`
	Kind        QuestionKind `json:"kind"`
	Prompt      string       `json:"prompt"`
	Dir         TextDir      `json:"dir"`
	Points      int32        `json:"points"`
	Explanation string       `json:"explanation"`
}

func (q *Queries) CreateQuestion(ctx context.Context, arg CreateQuestionParams) (Question, error) {
	row := q.db.QueryRow(ctx, createQuestion,
		arg.TenantID,
		arg.QuizID,
		arg.Kind,
		arg.Prompt,
		arg.Dir,
		arg.Points,
		arg.Explanation,
	)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.QuizID,
		&i.Kind,
		&i.Prompt,
		&i.Dir,
		&i.Points,
		&i.Explanation,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createQuiz = `-- name: CreateQuiz :one
INSERT INTO quizzes (tenant_id, lesson_id, title, instructions, dir, time_limit_s, max_attempts, pass_percent, shuffle, reveal_answers)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, tenant_id, lesson_id, title, instructions, dir, time_limit_s, max_attempts, pass_percent, shuffle, reveal_answers, created_at, updated_at
`

type CreateQuizParams struct {
	TenantID      uuid.UUID `json:"tenant_id"`
	LessonID      uuid.UUID `json:"lesson_id"`
	Title         string    `json:"title"`
	Instructions  string    `json:"instructions"`
	Dir           TextDir   `json:"dir"`
	TimeLimitS    int32     `json:"time_limit_s"`
	MaxAttempts   int16     `json:"max_attempts"`
	PassPercent   int16     `json:"pass_percent"`
	Shuffle       bool      `json:"shuffle"`
	RevealAnswers bool      `json:"reveal_answers"`
}

func (q *Queries) CreateQuiz(ctx context.Context, arg CreateQuizParams) (Quiz, error) {
	row := q.db.QueryRow(ctx, createQuiz,
		arg.TenantID,
		arg.LessonID,
		arg.Title,
		arg.Instructions,
		arg.Dir,
		arg.TimeLimitS,
		arg.MaxAttempts,
		arg.PassPercent,
		arg.Shuffle,
		arg.RevealAnswers,
	)
	var i Quiz
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.LessonID,
		&i.Title,
		&i.Instructions,
		&i.Dir,
		&i.TimeLimitS,
		&i.MaxAttempts,
		&i.PassPercent,
		&i.Shuffle,
		&i.RevealAnswers,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteQuestion = `-- name: DeleteQuestion :execrows
DELETE FROM questions WHERE id = $1
`

func (q *Queries) DeleteQuestion(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteQuestion, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const expireAttempt = `-- name: ExpireAttempt :one
UPDATE quiz_attempts SET state = 'expired', submitted_at = coalesce(submitted_at, now())
WHERE id = $1 AND state = 'in_progress'
RETURNING id, tenant_id, quiz_id, enrollment_id, user_id, attempt_no, state, started_at, expires_at, submitted_at, graded_at, points_awarded, points_possible
`

func (q *Queries) ExpireAttempt(ctx context.Context, id uuid.UUID) (QuizAttempt, error) {
	row := q.db.QueryRow(ctx, expireAttempt, id)
	var i QuizAttempt
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.QuizID,
		&i.EnrollmentID,
		&i.UserID,
		&i.AttemptNo,
		&i.State,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.SubmittedAt,
		&i.GradedAt,
		&i.PointsAwarded,
		&i.PointsPossible,
	)
	return i, err
}

const finalizeAttempt = `-- name: FinalizeAttempt :one
UPDATE quiz_attempts SET state = 'graded', graded_at = now(), points_awarded = $1
WHERE id = $2 AND state = 'submitted'
RETURNING id, tenant_id, quiz_id, enrollment_id, user_id, attempt_no, state, started_at, expires_at, submitted_at, graded_at, points_awarded, points_possible
`

type FinalizeAttemptParams struct {
	PointsAwarded int32     `json:"points_awarded"`
	ID            uuid.UUID `json:"id"`
}

func (q *Queries) FinalizeAttempt(ctx context.Context, arg FinalizeAttemptParams) (QuizAttempt, error) {
	row := q.db.QueryRow(ctx, finalizeAttempt, arg.PointsAwarded, arg.ID)
	var i QuizAttempt
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.QuizID,
		&i.EnrollmentID,
		&i.UserID,
		&i.AttemptNo,
		&i.State,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.SubmittedAt,
		&i.GradedAt,
		&i.PointsAwarded,
		&i.PointsPossible,
	)
	return i, err
}

const finishAttempt = `-- name: FinishAttempt :one
UPDATE quiz_attempts SET
  state = $1,
  submitted_at = coalesce(submitted_at, now()),
  graded_at = CASE WHEN $1::attempt_state = 'graded' THEN now() ELSE graded_at END,
  points_awarded = $2
WHERE id = $3 AND state = 'in_progress'
RETURNING id, tenant_id, quiz_id, enrollment_id, user_id, attempt_no, state, started_at, expires_at, submitted_at, graded_at, points_awarded, points_possible
`

type FinishAttemptParams struct {
	State         AttemptState `json:"state"`
	PointsAwarded int32        `json:"points_awarded"`
	ID            uuid.UUID    `json:"id"`
}

func (q *Queries) FinishAttempt(ctx context.Context, arg FinishAttemptParams) (QuizAttempt, error) {
	row := q.db.QueryRow(ctx, finishAttempt, arg.State, arg.PointsAwarded, arg.ID)
	var i QuizAttempt
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.QuizID,
		&i.EnrollmentID,
		&i.UserID,
		&i.AttemptNo,
		&i.State,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.SubmittedAt,
		&i.GradedAt,
		&i.PointsAwarded,
		&i.PointsPossible,
	)
	return i, err
}

const getAttempt = `-- name: GetAttempt :one
SELECT id, tenant_id, quiz_id, enrollment_id, user_id, attempt_no, state, started_at, expires_at, submitted_at, graded_at, points_awarded, points_possible FROM quiz_attempts WHERE id = $1
`

func (q *Queries) GetAttempt(ctx context.Context, id uuid.UUID) (QuizAttempt, error) {
	row := q.db.QueryRow(ctx, getAttempt, id)
	var i QuizAttempt
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.QuizID,
		&i.EnrollmentID,
		&i.UserID,
		&i.AttemptNo,
		&i.State,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.SubmittedAt,
		&i.GradedAt,
		&i.PointsAwarded,
		&i.PointsPossible,
	)
	return i, err
}

const getQuestion = `-- name: GetQuestion :one
SELECT id, tenant_id, quiz_id, kind, prompt, dir, points, explanation, position, created_at, updated_at FROM questions WHERE id = $1
`

func (q *Queries) GetQuestion(ctx context.Context, id uuid.UUID) (Question, error) {
	row := q.db.QueryRow(ctx, getQuestion, id)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.QuizID,
		&i.Kind,
		&i.Prompt,
		&i.Dir,
		&i.Points,
		&i.Explanation,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getQuiz = `-- name: GetQuiz :one
SELECT id, tenant_id, lesson_id, title, instructions, dir, time_limit_s, max_attempts, pass_percent, shuffle, reveal_answers, created_at, updated_at FROM quizzes WHERE id = $1
`

func (q *Queries) GetQuiz(ctx context.Context, id uuid.UUID) (Quiz, error) {
	row := q.db.QueryRow(ctx, getQuiz, id)
	var i Quiz
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.LessonID,
		&i.Title,
		&i.Instructions,
		&i.Dir,
		&i.TimeLimitS,
		&i.MaxAttempts,
		&i.PassPercent,
		&i.Shuffle,
		&i.RevealAnswers,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getQuizByLesson = `-- name: GetQuizByLesson :one
SELECT id, tenant_id, lesson_id, title, instructions, dir, time_limit_s, max_attempts, pass_percent, shuffle, reveal_answers, created_at, updated_at FROM quizzes WHERE lesson_id = $1
`

func (q *Queries) GetQuizByLesson(ctx context.Context, lessonID uuid.UUID) (Quiz, error) {
	row := q.db.QueryRow(ctx, getQuizByLesson, lessonID)
	var i Quiz
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.LessonID,
		&i.Title,
		&i.Instructions,
		&i.Dir,
		&i.TimeLimitS,
		&i.MaxAttempts,
		&i.PassPercent,
		&i.Shuffle,
		&i.RevealAnswers,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const gradeAnswer = `-- name: GradeAnswer :exec
UPDATE attempt_answers SET points_awarded = $1, needs_grading = $2
WHERE attempt_id = $3 AND question_id = $4
`

type GradeAnswerParams struct {
	PointsAwarded *int32    `json:"points_awarded"`
	NeedsGrading  bool      `json:"needs_grading"`
	AttemptID     uuid.UUID `json:"attempt_id"`
	QuestionID    uuid.UUID `json:"question_id"`
}

func (q *Queries) GradeAnswer(ctx context.Context, arg GradeAnswerParams) error {
	_, err := q.db.Exec(ctx, gradeAnswer,
		arg.PointsAwarded,
		arg.NeedsGrading,
		arg.AttemptID,
		arg.QuestionID,
	)
	return err
}

const listAnswers = `-- name: ListAnswers :many
SELECT attempt_id, question_id, tenant_id, option_ids, text_answer, points_awarded, needs_grading, feedback, graded_by, updated_at FROM attempt_answers WHERE attempt_id = $1
`

func (q *Queries) ListAnswers(ctx context.Context, attemptID uuid.UUID) ([]AttemptAnswer, error) {
	rows, err := q.db.Query(ctx, listAnswers, attemptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AttemptAnswer{}
	for rows.Next() {
		var i AttemptAnswer
		if err := rows.Scan(
			&i.AttemptID,
			&i.QuestionID,
			&i.TenantID,
			&i.OptionIds,
			&i.TextAnswer,
			&i.PointsAwarded,
			&i.NeedsGrading,
			&i.Feedback,
			&i.GradedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttemptsForMarking = `-- name: ListAttemptsForMarking :many
SELECT a.id, a.tenant_id, a.quiz_id, a.enrollment_id, a.user_id, a.attempt_no, a.state, a.started_at, a.expires_at, a.submitted_at, a.graded_at, a.points_awarded, a.points_possible, u.full_name, q.title AS quiz_title, l.title AS lesson_title,
       count(ans.question_id) FILTER (WHERE ans.needs_grading) AS pending
FROM quiz_attempts a
JOIN users u ON u.id = a.user_id
JOIN quizzes q ON q.id = a.quiz_id
JOIN lessons l ON l.id = q.lesson_id
LEFT JOIN attempt_answers ans ON ans.attempt_id = a.id
WHERE a.state = 'submitted'
GROUP BY a.id, u.full_name, q.title, l.title
HAVING count(ans.question_id) FILTER (WHERE ans.needs_grading) > 0
ORDER BY a.submitted_at
LIMIT $2 OFFSET $1
`

type ListAttemptsForMarkingParams struct {
	PageOffset int32 `json:"page_offset"`
	PageLimit  int32 `json:"page_limit"`
}

type ListAttemptsForMarkingRow struct {
	QuizAttempt QuizAttempt `json:"quiz_attempt"`
	FullName    string      `json:"full_name"`
	QuizTitle   string      `json:"quiz_title"`
	LessonTitle string      `json:"lesson_title"`
	Pending     int64       `json:"pending"`
}

func (q *Queries) ListAttemptsForMarking(ctx context.Context, arg ListAttemptsForMarkingParams) ([]ListAttemptsForMarkingRow, error) {
	rows, err := q.db.Query(ctx, listAttemptsForMarking, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAttemptsForMarkingRow{}
	for rows.Next() {
		var i ListAttemptsForMarkingRow
		if err := rows.Scan(
			&i.QuizAttempt.ID,
			&i.QuizAttempt.TenantID,
			&i.QuizAttempt.QuizID,
			&i.QuizAttempt.EnrollmentID,
			&i.QuizAttempt.UserID,
			&i.QuizAttempt.AttemptNo,
			&i.QuizAttempt.State,
			&i.QuizAttempt.StartedAt,
			&i.QuizAttempt.ExpiresAt,
			&i.QuizAttempt.SubmittedAt,
			&i.QuizAttempt.GradedAt,
			&i.QuizAttempt.PointsAwarded,
			&i.QuizAttempt.PointsPossible,
			&i.FullName,
			&i.QuizTitle,
			&i.LessonTitle,
			&i.Pending,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMyAttempts = `-- name: ListMyAttempts :many
SELECT id, tenant_id, quiz_id, enrollment_id, user_id, attempt_no, state, started_at, expires_at, submitted_at, graded_at, points_awarded, points_possible FROM quiz_attempts WHERE quiz_id = $1 AND user_id = $2 ORDER BY attempt_no
`

type ListMyAttemptsParams struct {
	QuizID uuid.UUID `json:"quiz_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) ListMyAttempts(ctx context.Context, arg ListMyAttemptsParams) ([]QuizAttempt, error) {
	rows, err := q.db.Query(ctx, listMyAttempts, arg.QuizID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QuizAttempt{}
	for rows.Next() {
		var i QuizAttempt
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.QuizID,
			&i.EnrollmentID,
			&i.UserID,
			&i.AttemptNo,
			&i.State,
			&i.StartedAt,
			&i.ExpiresAt,
			&i.SubmittedAt,
			&i.GradedAt,
			&i.PointsAwarded,
			&i.PointsPossible,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOptionsForQuiz = `-- name: ListOptionsForQuiz :many
SELECT o.id, o.tenant_id, o.question_id, o.label, o.is_correct, o.position FROM question_options o JOIN questions q ON q.id = o.question_id
WHERE q.quiz_id = $1
ORDER BY q.position, o.position
`

func (q *Queries) ListOptionsForQuiz(ctx context.Context, quizID uuid.UUID) ([]QuestionOption, error) {
	rows, err := q.db.Query(ctx, listOptionsForQuiz, quizID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QuestionOption{}
	for rows.Next() {
		var i QuestionOption
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.QuestionID,
			&i.Label,
			&i.IsCorrect,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuestions = `-- name: ListQuestions :many
SELECT id, tenant_id, quiz_id, kind, prompt, dir, points, explanation, position, created_at, updated_at FROM questions WHERE quiz_id = $1 ORDER BY position, created_at
`

func (q *Queries) ListQuestions(ctx context.Context, quizID uuid.UUID) ([]Question, error) {
	rows, err := q.db.Query(ctx, listQuestions, quizID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Question{}
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.QuizID,
			&i.Kind,
			&i.Prompt,
			&i.Dir,
			&i.Points,
			&i.Explanation,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAnswer = `-- name: MarkAnswer :one
UPDATE attempt_answers SET
  points_awarded = $1,
  feedback       = $2,
  graded_by      = $3,
  needs_grading  = false
WHERE attempt_id = $4 AND question_id = $5
RETURNING attempt_id, question_id, tenant_id, option_ids, text_answer, points_awarded, needs_grading, feedback, graded_by, updated_at
`

type MarkAnswerParams struct {
	PointsAwarded *int32        `json:"points_awarded"`
	Feedback      string        `json:"feedback"`
	GradedBy      uuid.NullUUID `json:"graded_by"`
	AttemptID     uuid.UUID     `json:"attempt_id"`
	QuestionID    uuid.UUID     `json:"question_id"`
}

func (q *Queries) MarkAnswer(ctx context.Context, arg MarkAnswerParams) (AttemptAnswer, error) {
	row := q.db.QueryRow(ctx, markAnswer,
		arg.PointsAwarded,
		arg.Feedback,
		arg.GradedBy,
		arg.AttemptID,
		arg.QuestionID,
	)
	var i AttemptAnswer
	err := row.Scan(
		&i.AttemptID,
		&i.QuestionID,
		&i.TenantID,
		&i.OptionIds,
		&i.TextAnswer,
		&i.PointsAwarded,
		&i.NeedsGrading,
		&i.Feedback,
		&i.GradedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const openAttempt = `-- name: OpenAttempt :one
SELECT id, tenant_id, quiz_id, enrollment_id, user_id, attempt_no, state, started_at, expires_at, submitted_at, graded_at, points_awarded, points_possible FROM quiz_attempts
WHERE quiz_id = $1 AND user_id = $2 AND state = 'in_progress'
`

type OpenAttemptParams struct {
	QuizID uuid.UUID `json:"quiz_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) OpenAttempt(ctx context.Context, arg OpenAttemptParams) (QuizAttempt, error) {
	row := q.db.QueryRow(ctx, openAttempt, arg.QuizID, arg.UserID)
	var i QuizAttempt
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.QuizID,
		&i.EnrollmentID,
		&i.UserID,
		&i.AttemptNo,
		&i.State,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.SubmittedAt,
		&i.GradedAt,
		&i.PointsAwarded,
		&i.PointsPossible,
	)
	return i, err
}

const replaceOptions = `-- name: ReplaceOptions :exec
DELETE FROM question_options WHERE question_id = $1
`

func (q *Queries) ReplaceOptions(ctx context.Context, questionID uuid.UUID) error {
	_, err := q.db.Exec(ctx, replaceOptions, questionID)
	return err
}

const saveAnswer = `-- name: SaveAnswer :one
INSERT INTO attempt_answers (tenant_id, attempt_id, question_id, option_ids, text_answer, needs_grading)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (attempt_id, question_id) DO UPDATE SET
  option_ids    = excluded.option_ids,
  text_answer   = excluded.text_answer,
  needs_grading = excluded.needs_grading,
  updated_at    = now()
RETURNING attempt_id, question_id, tenant_id, option_ids, text_answer, points_awarded, needs_grading, feedback, graded_by, updated_at
`

type SaveAnswerParams struct {
	TenantID     uuid.UUID   `json:"tenant_id"`
	AttemptID    uuid.UUID   `json:"attempt_id"`
	QuestionID   uuid.UUID   `json:"question_id"`
	OptionIds    []uuid.UUID `json:"option_ids"`
	TextAnswer   string      `json:"text_answer"`
	NeedsGrading bool        `json:"needs_grading"`
}

func (q *Queries) SaveAnswer(ctx context.Context, arg SaveAnswerParams) (AttemptAnswer, error) {
	row := q.db.QueryRow(ctx, saveAnswer,
		arg.TenantID,
		arg.AttemptID,
		arg.QuestionID,
		arg.OptionIds,
		arg.TextAnswer,
		arg.NeedsGrading,
	)
	var i AttemptAnswer
	err := row.Scan(
		&i.AttemptID,
		&i.QuestionID,
		&i.TenantID,
		&i.OptionIds,
		&i.TextAnswer,
		&i.PointsAwarded,
		&i.NeedsGrading,
		&i.Feedback,
		&i.GradedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const startAttempt = `-- name: StartAttempt :one
INSERT INTO quiz_attempts (tenant_id, quiz_id, enrollment_id, user_id, attempt_no, expires_at, points_possible)
VALUES ($1, $2, $3, $4, $5,
        CASE WHEN $6::integer > 0 THEN now() + make_interval(secs => $6::integer) END,
        $7)
RETURNING id, tenant_id, quiz_id, enrollment_id, user_id, attempt_no, state, started_at, expires_at, submitted_at, graded_at, points_awarded, points_possible
`

type StartAttemptParams struct {
	TenantID       uuid.UUID `json:"tenant_id"`
	QuizID         uuid.UUID `json:"quiz_id"`
	EnrollmentID   uuid.UUID `json:"enrollment_id"`
	UserID         uuid.UUID `json:"user_id"`
	AttemptNo      int16     `json:"attempt_no"`
	TimeLimitS     int32     `json:"time_limit_s"`
	PointsPossible int32     `json:"points_possible"`
}

func (q *Queries) StartAttempt(ctx context.Context, arg StartAttemptParams) (QuizAttempt, error) {
	row := q.db.QueryRow(ctx, startAttempt,
		arg.TenantID,
		arg.QuizID,
		arg.EnrollmentID,
		arg.UserID,
		arg.AttemptNo,
		arg.TimeLimitS,
		arg.PointsPossible,
	)
	var i QuizAttempt
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.QuizID,
		&i.EnrollmentID,
		&i.UserID,
		&i.AttemptNo,
		&i.State,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.SubmittedAt,
		&i.GradedAt,
		&i.PointsAwarded,
		&i.PointsPossible,
	)
	return i, err
}

const sumAwardedPoints = `-- name: SumAwardedPoints :one
SELECT coalesce(sum(points_awarded), 0)::integer AS total,
       count(*) FILTER (WHERE needs_grading) AS pending
FROM attempt_answers WHERE attempt_id = $1
`

type SumAwardedPointsRow struct {
	Total   int32 `json:"total"`
	Pending int64 `json:"pending"`
}

func (q *Queries) SumAwardedPoints(ctx context.Context, attemptID uuid.UUID) (SumAwardedPointsRow, error) {
	row := q.db.QueryRow(ctx, sumAwardedPoints, attemptID)
	var i SumAwardedPointsRow
	err := row.Scan(&i.Total, &i.Pending)
	return i, err
}

const updateQuiz = `-- name: UpdateQuiz :one
UPDATE quizzes SET
  title          = coalesce($1, title),
  instructions   = coalesce($2, instructions),
  time_limit_s   = coalesce($3, time_limit_s),
  max_attempts   = coalesce($4, max_attempts),
  pass_percent   = coalesce($5, pass_percent),
  shuffle        = coalesce($6, shuffle),
  reveal_answers = coalesce($7, reveal_answers)
WHERE id = $8
RETURNING id, tenant_id, lesson_id, title, instructions, dir, time_limit_s, max_attempts, pass_percent, shuffle, reveal_answers, created_at, updated_at
`

type UpdateQuizParams struct {
	Title         *string   `json:"title"`
	Instructions  *string   `json:"instructions"`
	TimeLimitS    *int32    `json:"time_limit_s"`
	MaxAttempts   *int16    `json:"max_attempts"`
	PassPercent   *int16    `json:"pass_percent"`
	Shuffle       *bool     `json:"shuffle"`
	RevealAnswers *bool     `json:"reveal_answers"`
	ID            uuid.UUID `json:"id"`
}

func (q *Queries) UpdateQuiz(ctx context.Context, arg UpdateQuizParams) (Quiz, error) {
	row := q.db.QueryRow(ctx, updateQuiz,
		arg.Title,
		arg.Instructions,
		arg.TimeLimitS,
		arg.MaxAttempts,
		arg.PassPercent,
		arg.Shuffle,
		arg.RevealAnswers,
		arg.ID,
	)
	var i Quiz
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.LessonID,
		&i.Title,
		&i.Instructions,
		&i.Dir,
		&i.TimeLimitS,
		&i.MaxAttempts,
		&i.PassPercent,
		&i.Shuffle,
		&i.RevealAnswers,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
