// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assignments.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const bestAssignmentScores = `-- name: BestAssignmentScores :many
SELECT a.id AS assignment_id, s.enrollment_id, s.points_awarded
FROM submissions s JOIN assignments a ON a.id = s.assignment_id
JOIN lessons l ON l.id = a.lesson_id JOIN modules m ON m.id = l.module_id
WHERE m.course_id = $1 AND s.state = 'returned' AND s.points_awarded IS NOT NULL
`

type BestAssignmentScoresRow struct {
	AssignmentID  uuid.UUID `json:"assignment_id"`
	EnrollmentID  uuid.UUID `json:"enrollment_id"`
	PointsAwarded *int32    `json:"points_awarded"`
}

func (q *Queries) BestAssignmentScores(ctx context.Context, courseID uuid.UUID) ([]BestAssignmentScoresRow, error) {
	rows, err := q.db.Query(ctx, bestAssignmentScores, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BestAssignmentScoresRow{}
	for rows.Next() {
		var i BestAssignmentScoresRow
		if err := rows.Scan(&i.AssignmentID, &i.EnrollmentID, &i.PointsAwarded); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createAssignment = `-- name: CreateAssignment :one
INSERT INTO assignments (tenant_id, lesson_id, title, instructions, dir, points, due_at, allow_late, late_penalty, max_files)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, tenant_id, lesson_id, title, instructions, dir, points, due_at, allow_late, late_penalty, max_files, created_at, updated_at
`

type CreateAssignmentParams struct {
	TenantID     uuid.UUID          `json:"tenant_id"`
	LessonID     uuid.UUID          `json:"lesson_id"`
	Title        string             `json:"title"`
	Instructions string             `json:"instructions"`
	Dir          TextDir            `json:"dir"`
	Points       int32              `json:"points"`
	DueAt        pgtype.Timestamptz `json:"due_at"`
	AllowLate    bool               `json:"allow_late"`
	LatePenalty  int16              `json:"late_penalty"`
	MaxFiles     int16              `json:"max_files"`
}

func (q *Queries) CreateAssignment(ctx context.Context, arg CreateAssignmentParams) (Assignment, error) {
	row := q.db.QueryRow(ctx, createAssignment,
		arg.TenantID,
		arg.LessonID,
		arg.Title,
		arg.Instructions,
		arg.Dir,
		arg.Points,
		arg.DueAt,
		arg.AllowLate,
		arg.LatePenalty,
		arg.MaxFiles,
	)
	var i Assignment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.LessonID,
		&i.Title,
		&i.Instructions,
		&i.Dir,
		&i.Points,
		&i.DueAt,
		&i.AllowLate,
		&i.LatePenalty,
		&i.MaxFiles,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAssignment = `-- name: GetAssignment :one
SELECT id, tenant_id, lesson_id, title, instructions, dir, points, due_at, allow_late, late_penalty, max_files, created_at, updated_at FROM assignments WHERE id = $1
`

func (q *Queries) GetAssignment(ctx context.Context, id uuid.UUID) (Assignment, error) {
	row := q.db.QueryRow(ctx, getAssignment, id)
	var i Assignment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.LessonID,
		&i.Title,
		&i.Instructions,
		&i.Dir,
		&i.Points,
		&i.DueAt,
		&i.AllowLate,
		&i.LatePenalty,
		&i.MaxFiles,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAssignmentByLesson = `-- name: GetAssignmentByLesson :one
SELECT id, tenant_id, lesson_id, title, instructions, dir, points, due_at, allow_late, late_penalty, max_files, created_at, updated_at FROM assignments WHERE lesson_id = $1
`

func (q *Queries) GetAssignmentByLesson(ctx context.Context, lessonID uuid.UUID) (Assignment, error) {
	row := q.db.QueryRow(ctx, getAssignmentByLesson, lessonID)
	var i Assignment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.LessonID,
		&i.Title,
		&i.Instructions,
		&i.Dir,
		&i.Points,
		&i.DueAt,
		&i.AllowLate,
		&i.LatePenalty,
		&i.MaxFiles,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubmission = `-- name: GetSubmission :one
SELECT id, tenant_id, assignment_id, enrollment_id, user_id, state, body, media_ids, is_late, submitted_at, points_awarded, feedback, graded_by, graded_at, created_at, updated_at FROM submissions WHERE id = $1
`

func (q *Queries) GetSubmission(ctx context.Context, id uuid.UUID) (Submission, error) {
	row := q.db.QueryRow(ctx, getSubmission, id)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AssignmentID,
		&i.EnrollmentID,
		&i.UserID,
		&i.State,
		&i.Body,
		&i.MediaIds,
		&i.IsLate,
		&i.SubmittedAt,
		&i.PointsAwarded,
		&i.Feedback,
		&i.GradedBy,
		&i.GradedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const gradeSubmission = `-- name: GradeSubmission :one
UPDATE submissions SET
  state = 'returned', points_awarded = $1, feedback = $2,
  graded_by = $3, graded_at = now()
WHERE id = $4 AND state = 'submitted'
RETURNING id, tenant_id, assignment_id, enrollment_id, user_id, state, body, media_ids, is_late, submitted_at, points_awarded, feedback, graded_by, graded_at, created_at, updated_at
`

type GradeSubmissionParams struct {
	PointsAwarded *int32        `json:"points_awarded"`
	Feedback      string        `json:"feedback"`
	GradedBy      uuid.NullUUID `json:"graded_by"`
	ID            uuid.UUID     `json:"id"`
}

func (q *Queries) GradeSubmission(ctx context.Context, arg GradeSubmissionParams) (Submission, error) {
	row := q.db.QueryRow(ctx, gradeSubmission,
		arg.PointsAwarded,
		arg.Feedback,
		arg.GradedBy,
		arg.ID,
	)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AssignmentID,
		&i.EnrollmentID,
		&i.UserID,
		&i.State,
		&i.Body,
		&i.MediaIds,
		&i.IsLate,
		&i.SubmittedAt,
		&i.PointsAwarded,
		&i.Feedback,
		&i.GradedBy,
		&i.GradedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSubmissions = `-- name: ListSubmissions :many
SELECT s.id, s.tenant_id, s.assignment_id, s.enrollment_id, s.user_id, s.state, s.body, s.media_ids, s.is_late, s.submitted_at, s.points_awarded, s.feedback, s.graded_by, s.graded_at, s.created_at, s.updated_at, u.full_name
FROM submissions s JOIN users u ON u.id = s.user_id
WHERE s.assignment_id = $1 AND s.state <> 'draft'
ORDER BY s.submitted_at
LIMIT $3 OFFSET $2
`

type ListSubmissionsParams struct {
	AssignmentID uuid.UUID `json:"assignment_id"`
	PageOffset   int32     `json:"page_offset"`
	PageLimit    int32     `json:"page_limit"`
}

type ListSubmissionsRow struct {
	Submission Submission `json:"submission"`
	FullName   string     `json:"full_name"`
}

func (q *Queries) ListSubmissions(ctx context.Context, arg ListSubmissionsParams) ([]ListSubmissionsRow, error) {
	rows, err := q.db.Query(ctx, listSubmissions, arg.AssignmentID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubmissionsRow{}
	for rows.Next() {
		var i ListSubmissionsRow
		if err := rows.Scan(
			&i.Submission.ID,
			&i.Submission.TenantID,
			&i.Submission.AssignmentID,
			&i.Submission.EnrollmentID,
			&i.Submission.UserID,
			&i.Submission.State,
			&i.Submission.Body,
			&i.Submission.MediaIds,
			&i.Submission.IsLate,
			&i.Submission.SubmittedAt,
			&i.Submission.PointsAwarded,
			&i.Submission.Feedback,
			&i.Submission.GradedBy,
			&i.Submission.GradedAt,
			&i.Submission.CreatedAt,
			&i.Submission.UpdatedAt,
			&i.FullName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubmissionsToGrade = `-- name: ListSubmissionsToGrade :many
SELECT s.id, s.tenant_id, s.assignment_id, s.enrollment_id, s.user_id, s.state, s.body, s.media_ids, s.is_late, s.submitted_at, s.points_awarded, s.feedback, s.graded_by, s.graded_at, s.created_at, s.updated_at, u.full_name, a.title AS assignment_title, a.points, a.due_at
FROM submissions s
JOIN users u ON u.id = s.user_id
JOIN assignments a ON a.id = s.assignment_id
WHERE s.state = 'submitted'
ORDER BY s.submitted_at
LIMIT $2 OFFSET $1
`

type ListSubmissionsToGradeParams struct {
	PageOffset int32 `json:"page_offset"`
	PageLimit  int32 `json:"page_limit"`
}

type ListSubmissionsToGradeRow struct {
	Submission      Submission         `json:"submission"`
	FullName        string             `json:"full_name"`
	AssignmentTitle string             `json:"assignment_title"`
	Points          int32              `json:"points"`
	DueAt           pgtype.Timestamptz `json:"due_at"`
}

func (q *Queries) ListSubmissionsToGrade(ctx context.Context, arg ListSubmissionsToGradeParams) ([]ListSubmissionsToGradeRow, error) {
	rows, err := q.db.Query(ctx, listSubmissionsToGrade, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubmissionsToGradeRow{}
	for rows.Next() {
		var i ListSubmissionsToGradeRow
		if err := rows.Scan(
			&i.Submission.ID,
			&i.Submission.TenantID,
			&i.Submission.AssignmentID,
			&i.Submission.EnrollmentID,
			&i.Submission.UserID,
			&i.Submission.State,
			&i.Submission.Body,
			&i.Submission.MediaIds,
			&i.Submission.IsLate,
			&i.Submission.SubmittedAt,
			&i.Submission.PointsAwarded,
			&i.Submission.Feedback,
			&i.Submission.GradedBy,
			&i.Submission.GradedAt,
			&i.Submission.CreatedAt,
			&i.Submission.UpdatedAt,
			&i.FullName,
			&i.AssignmentTitle,
			&i.Points,
			&i.DueAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mySubmission = `-- name: MySubmission :one
SELECT id, tenant_id, assignment_id, enrollment_id, user_id, state, body, media_ids, is_late, submitted_at, points_awarded, feedback, graded_by, graded_at, created_at, updated_at FROM submissions WHERE assignment_id = $1 AND user_id = $2
`

type MySubmissionParams struct {
	AssignmentID uuid.UUID `json:"assignment_id"`
	UserID       uuid.UUID `json:"user_id"`
}

func (q *Queries) MySubmission(ctx context.Context, arg MySubmissionParams) (Submission, error) {
	row := q.db.QueryRow(ctx, mySubmission, arg.AssignmentID, arg.UserID)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AssignmentID,
		&i.EnrollmentID,
		&i.UserID,
		&i.State,
		&i.Body,
		&i.MediaIds,
		&i.IsLate,
		&i.SubmittedAt,
		&i.PointsAwarded,
		&i.Feedback,
		&i.GradedBy,
		&i.GradedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const submissionForMarking = `-- name: SubmissionForMarking :one
SELECT s.id, s.tenant_id, s.assignment_id, s.enrollment_id, s.user_id, s.state, s.body, s.media_ids, s.is_late, s.submitted_at, s.points_awarded, s.feedback, s.graded_by, s.graded_at, s.created_at, s.updated_at, a.id, a.tenant_id, a.lesson_id, a.title, a.instructions, a.dir, a.points, a.due_at, a.allow_late, a.late_penalty, a.max_files, a.created_at, a.updated_at, u.full_name
FROM submissions s
JOIN assignments a ON a.id = s.assignment_id
JOIN users u ON u.id = s.user_id
WHERE s.id = $1
`

type SubmissionForMarkingRow struct {
	Submission Submission `json:"submission"`
	Assignment Assignment `json:"assignment"`
	FullName   string     `json:"full_name"`
}

func (q *Queries) SubmissionForMarking(ctx context.Context, id uuid.UUID) (SubmissionForMarkingRow, error) {
	row := q.db.QueryRow(ctx, submissionForMarking, id)
	var i SubmissionForMarkingRow
	err := row.Scan(
		&i.Submission.ID,
		&i.Submission.TenantID,
		&i.Submission.AssignmentID,
		&i.Submission.EnrollmentID,
		&i.Submission.UserID,
		&i.Submission.State,
		&i.Submission.Body,
		&i.Submission.MediaIds,
		&i.Submission.IsLate,
		&i.Submission.SubmittedAt,
		&i.Submission.PointsAwarded,
		&i.Submission.Feedback,
		&i.Submission.GradedBy,
		&i.Submission.GradedAt,
		&i.Submission.CreatedAt,
		&i.Submission.UpdatedAt,
		&i.Assignment.ID,
		&i.Assignment.TenantID,
		&i.Assignment.LessonID,
		&i.Assignment.Title,
		&i.Assignment.Instructions,
		&i.Assignment.Dir,
		&i.Assignment.Points,
		&i.Assignment.DueAt,
		&i.Assignment.AllowLate,
		&i.Assignment.LatePenalty,
		&i.Assignment.MaxFiles,
		&i.Assignment.CreatedAt,
		&i.Assignment.UpdatedAt,
		&i.FullName,
	)
	return i, err
}

const updateAssignment = `-- name: UpdateAssignment :one
UPDATE assignments SET
  title        = coalesce($1, title),
  instructions = coalesce($2, instructions),
  due_at       = coalesce($3, due_at),
  allow_late   = coalesce($4, allow_late),
  late_penalty = coalesce($5, late_penalty)
WHERE id = $6
RETURNING id, tenant_id, lesson_id, title, instructions, dir, points, due_at, allow_late, late_penalty, max_files, created_at, updated_at
`

type UpdateAssignmentParams struct {
	Title        *string            `json:"title"`
	Instructions *string            `json:"instructions"`
	DueAt        pgtype.Timestamptz `json:"due_at"`
	AllowLate    *bool              `json:"allow_late"`
	LatePenalty  *int16             `json:"late_penalty"`
	ID           uuid.UUID          `json:"id"`
}

func (q *Queries) UpdateAssignment(ctx context.Context, arg UpdateAssignmentParams) (Assignment, error) {
	row := q.db.QueryRow(ctx, updateAssignment,
		arg.Title,
		arg.Instructions,
		arg.DueAt,
		arg.AllowLate,
		arg.LatePenalty,
		arg.ID,
	)
	var i Assignment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.LessonID,
		&i.Title,
		&i.Instructions,
		&i.Dir,
		&i.Points,
		&i.DueAt,
		&i.AllowLate,
		&i.LatePenalty,
		&i.MaxFiles,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSubmission = `-- name: UpsertSubmission :one
INSERT INTO submissions (tenant_id, assignment_id, enrollment_id, user_id, state, body, media_ids, is_late, submitted_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8,
        CASE WHEN $5::submission_state <> 'draft' THEN now() END)
ON CONFLICT (assignment_id, enrollment_id) DO UPDATE SET
  state        = excluded.state,
  body         = excluded.body,
  media_ids    = excluded.media_ids,
  is_late      = excluded.is_late,
  submitted_at = CASE WHEN excluded.state <> 'draft' THEN coalesce(submissions.submitted_at, now()) END,
  updated_at   = now()
RETURNING id, tenant_id, assignment_id, enrollment_id, user_id, state, body, media_ids, is_late, submitted_at, points_awarded, feedback, graded_by, graded_at, created_at, updated_at
`

type UpsertSubmissionParams struct {
	TenantID     uuid.UUID       `json:"tenant_id"`
	AssignmentID uuid.UUID       `json:"assignment_id"`
	EnrollmentID uuid.UUID       `json:"enrollment_id"`
	UserID       uuid.UUID       `json:"user_id"`
	State        SubmissionState `json:"state"`
	Body         string          `json:"body"`
	MediaIds     []uuid.UUID     `json:"media_ids"`
	IsLate       bool            `json:"is_late"`
}

func (q *Queries) UpsertSubmission(ctx context.Context, arg UpsertSubmissionParams) (Submission, error) {
	row := q.db.QueryRow(ctx, upsertSubmission,
		arg.TenantID,
		arg.AssignmentID,
		arg.EnrollmentID,
		arg.UserID,
		arg.State,
		arg.Body,
		arg.MediaIds,
		arg.IsLate,
	)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AssignmentID,
		&i.EnrollmentID,
		&i.UserID,
		&i.State,
		&i.Body,
		&i.MediaIds,
		&i.IsLate,
		&i.SubmittedAt,
		&i.PointsAwarded,
		&i.Feedback,
		&i.GradedBy,
		&i.GradedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
