// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attendance.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addGuardian = `-- name: AddGuardian :one
INSERT INTO guardianships (tenant_id, guardian_id, student_id, relation)
VALUES ($1, $2, $3, $4)
ON CONFLICT (tenant_id, guardian_id, student_id) DO UPDATE SET relation = excluded.relation
RETURNING tenant_id, guardian_id, student_id, relation, created_at
`

type AddGuardianParams struct {
	TenantID   uuid.UUID `json:"tenant_id"`
	GuardianID uuid.UUID `json:"guardian_id"`
	StudentID  uuid.UUID `json:"student_id"`
	Relation   string    `json:"relation"`
}

func (q *Queries) AddGuardian(ctx context.Context, arg AddGuardianParams) (Guardianship, error) {
	row := q.db.QueryRow(ctx, addGuardian,
		arg.TenantID,
		arg.GuardianID,
		arg.StudentID,
		arg.Relation,
	)
	var i Guardianship
	err := row.Scan(
		&i.TenantID,
		&i.GuardianID,
		&i.StudentID,
		&i.Relation,
		&i.CreatedAt,
	)
	return i, err
}

const attendanceSummary = `-- name: AttendanceSummary :one
SELECT
  count(*) FILTER (WHERE a.status = 'present') AS present,
  count(*) FILTER (WHERE a.status = 'late')    AS late,
  count(*) FILTER (WHERE a.status = 'absent')  AS absent,
  count(*) FILTER (WHERE a.status = 'excused') AS excused
FROM attendance a JOIN class_sessions s ON s.id = a.session_id
WHERE s.course_id = $1 AND a.enrollment_id = $2
`

type AttendanceSummaryParams struct {
	CourseID     uuid.UUID `json:"course_id"`
	EnrollmentID uuid.UUID `json:"enrollment_id"`
}

type AttendanceSummaryRow struct {
	Present int64 `json:"present"`
	Late    int64 `json:"late"`
	Absent  int64 `json:"absent"`
	Excused int64 `json:"excused"`
}

func (q *Queries) AttendanceSummary(ctx context.Context, arg AttendanceSummaryParams) (AttendanceSummaryRow, error) {
	row := q.db.QueryRow(ctx, attendanceSummary, arg.CourseID, arg.EnrollmentID)
	var i AttendanceSummaryRow
	err := row.Scan(
		&i.Present,
		&i.Late,
		&i.Absent,
		&i.Excused,
	)
	return i, err
}

const createClassSession = `-- name: CreateClassSession :one
INSERT INTO class_sessions (tenant_id, course_id, title, location, starts_at, ends_at, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, course_id, title, location, starts_at, ends_at, created_by, created_at, updated_at, provider, join_url, host_url, recording_media_id
`

type CreateClassSessionParams struct {
	TenantID  uuid.UUID          `json:"tenant_id"`
	CourseID  uuid.UUID          `json:"course_id"`
	Title     string             `json:"title"`
	Location  string             `json:"location"`
	StartsAt  pgtype.Timestamptz `json:"starts_at"`
	EndsAt    pgtype.Timestamptz `json:"ends_at"`
	CreatedBy uuid.NullUUID      `json:"created_by"`
}

func (q *Queries) CreateClassSession(ctx context.Context, arg CreateClassSessionParams) (ClassSession, error) {
	row := q.db.QueryRow(ctx, createClassSession,
		arg.TenantID,
		arg.CourseID,
		arg.Title,
		arg.Location,
		arg.StartsAt,
		arg.EndsAt,
		arg.CreatedBy,
	)
	var i ClassSession
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CourseID,
		&i.Title,
		&i.Location,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Provider,
		&i.JoinUrl,
		&i.HostUrl,
		&i.RecordingMediaID,
	)
	return i, err
}

const getClassSession = `-- name: GetClassSession :one
SELECT id, tenant_id, course_id, title, location, starts_at, ends_at, created_by, created_at, updated_at, provider, join_url, host_url, recording_media_id FROM class_sessions WHERE id = $1
`

func (q *Queries) GetClassSession(ctx context.Context, id uuid.UUID) (ClassSession, error) {
	row := q.db.QueryRow(ctx, getClassSession, id)
	var i ClassSession
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CourseID,
		&i.Title,
		&i.Location,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Provider,
		&i.JoinUrl,
		&i.HostUrl,
		&i.RecordingMediaID,
	)
	return i, err
}

const guardiansOf = `-- name: GuardiansOf :many
SELECT guardian_id, relation FROM guardianships WHERE student_id = $1
`

type GuardiansOfRow struct {
	GuardianID uuid.UUID `json:"guardian_id"`
	Relation   string    `json:"relation"`
}

func (q *Queries) GuardiansOf(ctx context.Context, studentID uuid.UUID) ([]GuardiansOfRow, error) {
	rows, err := q.db.Query(ctx, guardiansOf, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GuardiansOfRow{}
	for rows.Next() {
		var i GuardiansOfRow
		if err := rows.Scan(&i.GuardianID, &i.Relation); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClassSessions = `-- name: ListClassSessions :many
SELECT id, tenant_id, course_id, title, location, starts_at, ends_at, created_by, created_at, updated_at, provider, join_url, host_url, recording_media_id FROM class_sessions WHERE course_id = $1
ORDER BY starts_at DESC
LIMIT $3 OFFSET $2
`

type ListClassSessionsParams struct {
	CourseID   uuid.UUID `json:"course_id"`
	PageOffset int32     `json:"page_offset"`
	PageLimit  int32     `json:"page_limit"`
}

func (q *Queries) ListClassSessions(ctx context.Context, arg ListClassSessionsParams) ([]ClassSession, error) {
	rows, err := q.db.Query(ctx, listClassSessions, arg.CourseID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClassSession{}
	for rows.Next() {
		var i ClassSession
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CourseID,
			&i.Title,
			&i.Location,
			&i.StartsAt,
			&i.EndsAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Provider,
			&i.JoinUrl,
			&i.HostUrl,
			&i.RecordingMediaID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGuardianships = `-- name: ListGuardianships :many
SELECT g.tenant_id, g.guardian_id, g.student_id, g.relation, g.created_at, gu.full_name AS guardian_name, st.full_name AS student_name
FROM guardianships g
JOIN users gu ON gu.id = g.guardian_id
JOIN users st ON st.id = g.student_id
ORDER BY st.full_name
`

type ListGuardianshipsRow struct {
	TenantID     uuid.UUID          `json:"tenant_id"`
	GuardianID   uuid.UUID          `json:"guardian_id"`
	StudentID    uuid.UUID          `json:"student_id"`
	Relation     string             `json:"relation"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	GuardianName string             `json:"guardian_name"`
	StudentName  string             `json:"student_name"`
}

func (q *Queries) ListGuardianships(ctx context.Context) ([]ListGuardianshipsRow, error) {
	rows, err := q.db.Query(ctx, listGuardianships)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGuardianshipsRow{}
	for rows.Next() {
		var i ListGuardianshipsRow
		if err := rows.Scan(
			&i.TenantID,
			&i.GuardianID,
			&i.StudentID,
			&i.Relation,
			&i.CreatedAt,
			&i.GuardianName,
			&i.StudentName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAttendance = `-- name: MarkAttendance :one
INSERT INTO attendance (tenant_id, session_id, enrollment_id, status, note, marked_by)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (session_id, enrollment_id) DO UPDATE
SET status = excluded.status, note = excluded.note, marked_by = excluded.marked_by, marked_at = now()
RETURNING session_id, enrollment_id, tenant_id, status, note, marked_by, marked_at
`

type MarkAttendanceParams struct {
	TenantID     uuid.UUID        `json:"tenant_id"`
	SessionID    uuid.UUID        `json:"session_id"`
	EnrollmentID uuid.UUID        `json:"enrollment_id"`
	Status       AttendanceStatus `json:"status"`
	Note         string           `json:"note"`
	MarkedBy     uuid.NullUUID    `json:"marked_by"`
}

func (q *Queries) MarkAttendance(ctx context.Context, arg MarkAttendanceParams) (Attendance, error) {
	row := q.db.QueryRow(ctx, markAttendance,
		arg.TenantID,
		arg.SessionID,
		arg.EnrollmentID,
		arg.Status,
		arg.Note,
		arg.MarkedBy,
	)
	var i Attendance
	err := row.Scan(
		&i.SessionID,
		&i.EnrollmentID,
		&i.TenantID,
		&i.Status,
		&i.Note,
		&i.MarkedBy,
		&i.MarkedAt,
	)
	return i, err
}

const myAttendance = `-- name: MyAttendance :many
SELECT a.session_id, a.enrollment_id, a.tenant_id, a.status, a.note, a.marked_by, a.marked_at, s.title, s.starts_at
FROM attendance a JOIN class_sessions s ON s.id = a.session_id
WHERE a.enrollment_id = $1
ORDER BY s.starts_at DESC
LIMIT $3 OFFSET $2
`

type MyAttendanceParams struct {
	EnrollmentID uuid.UUID `json:"enrollment_id"`
	PageOffset   int32     `json:"page_offset"`
	PageLimit    int32     `json:"page_limit"`
}

type MyAttendanceRow struct {
	Attendance Attendance         `json:"attendance"`
	Title      string             `json:"title"`
	StartsAt   pgtype.Timestamptz `json:"starts_at"`
}

func (q *Queries) MyAttendance(ctx context.Context, arg MyAttendanceParams) ([]MyAttendanceRow, error) {
	rows, err := q.db.Query(ctx, myAttendance, arg.EnrollmentID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MyAttendanceRow{}
	for rows.Next() {
		var i MyAttendanceRow
		if err := rows.Scan(
			&i.Attendance.SessionID,
			&i.Attendance.EnrollmentID,
			&i.Attendance.TenantID,
			&i.Attendance.Status,
			&i.Attendance.Note,
			&i.Attendance.MarkedBy,
			&i.Attendance.MarkedAt,
			&i.Title,
			&i.StartsAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeGuardian = `-- name: RemoveGuardian :execrows
DELETE FROM guardianships WHERE guardian_id = $1 AND student_id = $2
`

type RemoveGuardianParams struct {
	GuardianID uuid.UUID `json:"guardian_id"`
	StudentID  uuid.UUID `json:"student_id"`
}

func (q *Queries) RemoveGuardian(ctx context.Context, arg RemoveGuardianParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeGuardian, arg.GuardianID, arg.StudentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const sessionRoll = `-- name: SessionRoll :many
SELECT e.id AS enrollment_id, e.user_id, u.full_name, a.status, a.note, a.marked_at
FROM enrollments e
JOIN users u ON u.id = e.user_id
LEFT JOIN attendance a ON a.enrollment_id = e.id AND a.session_id = $1
WHERE e.course_id = $2 AND e.status <> 'cancelled'
ORDER BY u.full_name
`

type SessionRollParams struct {
	SessionID uuid.UUID `json:"session_id"`
	CourseID  uuid.UUID `json:"course_id"`
}

type SessionRollRow struct {
	EnrollmentID uuid.UUID          `json:"enrollment_id"`
	UserID       uuid.UUID          `json:"user_id"`
	FullName     string             `json:"full_name"`
	Status       *AttendanceStatus  `json:"status"`
	Note         *string            `json:"note"`
	MarkedAt     pgtype.Timestamptz `json:"marked_at"`
}

// The roll for one session: every enrolled learner, marked or not.
func (q *Queries) SessionRoll(ctx context.Context, arg SessionRollParams) ([]SessionRollRow, error) {
	rows, err := q.db.Query(ctx, sessionRoll, arg.SessionID, arg.CourseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionRollRow{}
	for rows.Next() {
		var i SessionRollRow
		if err := rows.Scan(
			&i.EnrollmentID,
			&i.UserID,
			&i.FullName,
			&i.Status,
			&i.Note,
			&i.MarkedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSessionLink = `-- name: SetSessionLink :one
UPDATE class_sessions SET provider = $1, join_url = $2, host_url = $3
WHERE id = $4
RETURNING id, tenant_id, course_id, title, location, starts_at, ends_at, created_by, created_at, updated_at, provider, join_url, host_url, recording_media_id
`

type SetSessionLinkParams struct {
	Provider string    `json:"provider"`
	JoinUrl  string    `json:"join_url"`
	HostUrl  string    `json:"host_url"`
	ID       uuid.UUID `json:"id"`
}

func (q *Queries) SetSessionLink(ctx context.Context, arg SetSessionLinkParams) (ClassSession, error) {
	row := q.db.QueryRow(ctx, setSessionLink,
		arg.Provider,
		arg.JoinUrl,
		arg.HostUrl,
		arg.ID,
	)
	var i ClassSession
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CourseID,
		&i.Title,
		&i.Location,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Provider,
		&i.JoinUrl,
		&i.HostUrl,
		&i.RecordingMediaID,
	)
	return i, err
}

const setSessionRecording = `-- name: SetSessionRecording :one
UPDATE class_sessions SET recording_media_id = $1 WHERE id = $2 RETURNING id, tenant_id, course_id, title, location, starts_at, ends_at, created_by, created_at, updated_at, provider, join_url, host_url, recording_media_id
`

type SetSessionRecordingParams struct {
	RecordingMediaID uuid.NullUUID `json:"recording_media_id"`
	ID               uuid.UUID     `json:"id"`
}

func (q *Queries) SetSessionRecording(ctx context.Context, arg SetSessionRecordingParams) (ClassSession, error) {
	row := q.db.QueryRow(ctx, setSessionRecording, arg.RecordingMediaID, arg.ID)
	var i ClassSession
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CourseID,
		&i.Title,
		&i.Location,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Provider,
		&i.JoinUrl,
		&i.HostUrl,
		&i.RecordingMediaID,
	)
	return i, err
}
