// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package database

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const consumeOTPChallenge = `-- name: ConsumeOTPChallenge :exec
UPDATE otp_challenges SET consumed_at = now() WHERE id = $1 AND consumed_at IS NULL
`

func (q *Queries) ConsumeOTPChallenge(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, consumeOTPChallenge, id)
	return err
}

const countRecentOTPs = `-- name: CountRecentOTPs :one
SELECT count(*) FROM otp_challenges
WHERE destination = $1 AND purpose = $2 AND created_at > now() - $3::interval
`

type CountRecentOTPsParams struct {
	Destination string          `json:"destination"`
	Purpose     OtpPurpose      `json:"purpose"`
	Lookback    pgtype.Interval `json:"lookback"`
}

func (q *Queries) CountRecentOTPs(ctx context.Context, arg CountRecentOTPsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentOTPs, arg.Destination, arg.Purpose, arg.Lookback)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOTPChallenge = `-- name: CreateOTPChallenge :one
INSERT INTO otp_challenges (destination, purpose, code_hash, expires_at)
VALUES ($1, $2, $3, now() + $4::interval)
RETURNING id, destination, purpose, code_hash, attempts, consumed_at, expires_at, created_at
`

type CreateOTPChallengeParams struct {
	Destination string          `json:"destination"`
	Purpose     OtpPurpose      `json:"purpose"`
	CodeHash    []byte          `json:"code_hash"`
	TtlInterval pgtype.Interval `json:"ttl_interval"`
}

func (q *Queries) CreateOTPChallenge(ctx context.Context, arg CreateOTPChallengeParams) (OtpChallenge, error) {
	row := q.db.QueryRow(ctx, createOTPChallenge,
		arg.Destination,
		arg.Purpose,
		arg.CodeHash,
		arg.TtlInterval,
	)
	var i OtpChallenge
	err := row.Scan(
		&i.ID,
		&i.Destination,
		&i.Purpose,
		&i.CodeHash,
		&i.Attempts,
		&i.ConsumedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, token_hash, user_agent, ip, expires_at)
VALUES ($1, $2, $3, $4, now() + $5::interval)
RETURNING id, user_id, token_hash, user_agent, ip, last_used_at, revoked_at, expires_at, created_at
`

type CreateSessionParams struct {
	UserID      uuid.UUID       `json:"user_id"`
	TokenHash   []byte          `json:"token_hash"`
	UserAgent   string          `json:"user_agent"`
	Ip          *netip.Addr     `json:"ip"`
	TtlInterval pgtype.Interval `json:"ttl_interval"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.TokenHash,
		arg.UserAgent,
		arg.Ip,
		arg.TtlInterval,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.UserAgent,
		&i.Ip,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredAuthRecords = `-- name: DeleteExpiredAuthRecords :exec
WITH s AS (DELETE FROM sessions WHERE expires_at < now() - interval '30 days')
DELETE FROM otp_challenges WHERE created_at < now() - interval '7 days'
`

func (q *Queries) DeleteExpiredAuthRecords(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredAuthRecords)
	return err
}

const getSessionByToken = `-- name: GetSessionByToken :one
SELECT session_id, user_id, full_name, expires_at FROM live_sessions WHERE token_hash = $1
`

type GetSessionByTokenRow struct {
	SessionID uuid.UUID          `json:"session_id"`
	UserID    uuid.UUID          `json:"user_id"`
	FullName  string             `json:"full_name"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) GetSessionByToken(ctx context.Context, tokenHash []byte) (GetSessionByTokenRow, error) {
	row := q.db.QueryRow(ctx, getSessionByToken, tokenHash)
	var i GetSessionByTokenRow
	err := row.Scan(
		&i.SessionID,
		&i.UserID,
		&i.FullName,
		&i.ExpiresAt,
	)
	return i, err
}

const latestOTPChallenge = `-- name: LatestOTPChallenge :one
SELECT id, destination, purpose, code_hash, attempts, consumed_at, expires_at, created_at FROM otp_challenges
WHERE destination = $1 AND purpose = $2 AND consumed_at IS NULL
ORDER BY created_at DESC LIMIT 1
`

type LatestOTPChallengeParams struct {
	Destination string     `json:"destination"`
	Purpose     OtpPurpose `json:"purpose"`
}

func (q *Queries) LatestOTPChallenge(ctx context.Context, arg LatestOTPChallengeParams) (OtpChallenge, error) {
	row := q.db.QueryRow(ctx, latestOTPChallenge, arg.Destination, arg.Purpose)
	var i OtpChallenge
	err := row.Scan(
		&i.ID,
		&i.Destination,
		&i.Purpose,
		&i.CodeHash,
		&i.Attempts,
		&i.ConsumedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const recordOTPAttempt = `-- name: RecordOTPAttempt :exec
UPDATE otp_challenges SET attempts = attempts + 1 WHERE id = $1
`

func (q *Queries) RecordOTPAttempt(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, recordOTPAttempt, id)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions SET revoked_at = now() WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeSession, id)
	return err
}

const revokeUserSessions = `-- name: RevokeUserSessions :exec
UPDATE sessions SET revoked_at = now() WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeUserSessions(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeUserSessions, userID)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchSession, id)
	return err
}
