// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const countCourses = `-- name: CountCourses :one
SELECT count(*) FROM courses
WHERE ($1::publish_status IS NULL OR status = $1)
`

func (q *Queries) CountCourses(ctx context.Context, statusFilter *PublishStatus) (int64, error) {
	row := q.db.QueryRow(ctx, countCourses, statusFilter)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCourse = `-- name: CreateCourse :one
INSERT INTO courses (tenant_id, slug, title, summary, dir, visibility, price_minor, currency, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, tenant_id, slug, title, summary, dir, status, visibility, price_minor, currency, created_by, published_at, created_at, updated_at
`

type CreateCourseParams struct {
	TenantID   uuid.UUID        `json:"tenant_id"`
	Slug       string           `json:"slug"`
	Title      string           `json:"title"`
	Summary    string           `json:"summary"`
	Dir        TextDir          `json:"dir"`
	Visibility CourseVisibility `json:"visibility"`
	PriceMinor int64            `json:"price_minor"`
	Currency   string           `json:"currency"`
	CreatedBy  uuid.NullUUID    `json:"created_by"`
}

func (q *Queries) CreateCourse(ctx context.Context, arg CreateCourseParams) (Course, error) {
	row := q.db.QueryRow(ctx, createCourse,
		arg.TenantID,
		arg.Slug,
		arg.Title,
		arg.Summary,
		arg.Dir,
		arg.Visibility,
		arg.PriceMinor,
		arg.Currency,
		arg.CreatedBy,
	)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Slug,
		&i.Title,
		&i.Summary,
		&i.Dir,
		&i.Status,
		&i.Visibility,
		&i.PriceMinor,
		&i.Currency,
		&i.CreatedBy,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createLesson = `-- name: CreateLesson :one
INSERT INTO lessons (tenant_id, module_id, title, kind, body, dir, duration_s, is_preview, position)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8,
        coalesce((SELECT max(position) + 1024 FROM lessons WHERE module_id = $2), 1024))
RETURNING id, tenant_id, module_id, title, kind, body, dir, duration_s, is_preview, status, position, created_at, updated_at, media_id
`

type CreateLessonParams struct {
	TenantID  uuid.UUID  `json:"tenant_id"`
	ModuleID  uuid.UUID  `json:"module_id"`
	Title     string     `json:"title"`
	Kind      LessonKind `json:"kind"`
	Body      string     `json:"body"`
	Dir       TextDir    `json:"dir"`
	DurationS int32      `json:"duration_s"`
	IsPreview bool       `json:"is_preview"`
}

func (q *Queries) CreateLesson(ctx context.Context, arg CreateLessonParams) (Lesson, error) {
	row := q.db.QueryRow(ctx, createLesson,
		arg.TenantID,
		arg.ModuleID,
		arg.Title,
		arg.Kind,
		arg.Body,
		arg.Dir,
		arg.DurationS,
		arg.IsPreview,
	)
	var i Lesson
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ModuleID,
		&i.Title,
		&i.Kind,
		&i.Body,
		&i.Dir,
		&i.DurationS,
		&i.IsPreview,
		&i.Status,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MediaID,
	)
	return i, err
}

const createModule = `-- name: CreateModule :one
INSERT INTO modules (tenant_id, course_id, title, position)
VALUES ($1, $2, $3, coalesce((SELECT max(position) + 1024 FROM modules WHERE course_id = $2), 1024))
RETURNING id, tenant_id, course_id, title, position, created_at, updated_at
`

type CreateModuleParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	CourseID uuid.UUID `json:"course_id"`
	Title    string    `json:"title"`
}

func (q *Queries) CreateModule(ctx context.Context, arg CreateModuleParams) (Module, error) {
	row := q.db.QueryRow(ctx, createModule, arg.TenantID, arg.CourseID, arg.Title)
	var i Module
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CourseID,
		&i.Title,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCourse = `-- name: DeleteCourse :execrows
DELETE FROM courses WHERE id = $1
`

func (q *Queries) DeleteCourse(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCourse, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteLesson = `-- name: DeleteLesson :execrows
DELETE FROM lessons WHERE id = $1
`

func (q *Queries) DeleteLesson(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteLesson, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteModule = `-- name: DeleteModule :execrows
DELETE FROM modules WHERE id = $1
`

func (q *Queries) DeleteModule(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteModule, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCourse = `-- name: GetCourse :one
SELECT id, tenant_id, slug, title, summary, dir, status, visibility, price_minor, currency, created_by, published_at, created_at, updated_at FROM courses WHERE id = $1
`

func (q *Queries) GetCourse(ctx context.Context, id uuid.UUID) (Course, error) {
	row := q.db.QueryRow(ctx, getCourse, id)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Slug,
		&i.Title,
		&i.Summary,
		&i.Dir,
		&i.Status,
		&i.Visibility,
		&i.PriceMinor,
		&i.Currency,
		&i.CreatedBy,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCourseBySlug = `-- name: GetCourseBySlug :one
SELECT id, tenant_id, slug, title, summary, dir, status, visibility, price_minor, currency, created_by, published_at, created_at, updated_at FROM courses WHERE slug = $1
`

func (q *Queries) GetCourseBySlug(ctx context.Context, slug string) (Course, error) {
	row := q.db.QueryRow(ctx, getCourseBySlug, slug)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Slug,
		&i.Title,
		&i.Summary,
		&i.Dir,
		&i.Status,
		&i.Visibility,
		&i.PriceMinor,
		&i.Currency,
		&i.CreatedBy,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLesson = `-- name: GetLesson :one
SELECT id, tenant_id, module_id, title, kind, body, dir, duration_s, is_preview, status, position, created_at, updated_at, media_id FROM lessons WHERE id = $1
`

func (q *Queries) GetLesson(ctx context.Context, id uuid.UUID) (Lesson, error) {
	row := q.db.QueryRow(ctx, getLesson, id)
	var i Lesson
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ModuleID,
		&i.Title,
		&i.Kind,
		&i.Body,
		&i.Dir,
		&i.DurationS,
		&i.IsPreview,
		&i.Status,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MediaID,
	)
	return i, err
}

const listCourses = `-- name: ListCourses :many
SELECT id, tenant_id, slug, title, summary, dir, status, visibility, price_minor, currency, created_by, published_at, created_at, updated_at FROM courses
WHERE ($1::publish_status IS NULL OR status = $1)
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListCoursesParams struct {
	StatusFilter *PublishStatus `json:"status_filter"`
	PageOffset   int32          `json:"page_offset"`
	PageLimit    int32          `json:"page_limit"`
}

func (q *Queries) ListCourses(ctx context.Context, arg ListCoursesParams) ([]Course, error) {
	rows, err := q.db.Query(ctx, listCourses, arg.StatusFilter, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Course{}
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Slug,
			&i.Title,
			&i.Summary,
			&i.Dir,
			&i.Status,
			&i.Visibility,
			&i.PriceMinor,
			&i.Currency,
			&i.CreatedBy,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLessonsForCourse = `-- name: ListLessonsForCourse :many
SELECT l.id, l.tenant_id, l.module_id, l.title, l.kind, l.body, l.dir, l.duration_s, l.is_preview, l.status, l.position, l.created_at, l.updated_at, l.media_id FROM lessons l JOIN modules m ON m.id = l.module_id
WHERE m.course_id = $1
ORDER BY m.position, l.position, l.created_at
`

func (q *Queries) ListLessonsForCourse(ctx context.Context, courseID uuid.UUID) ([]Lesson, error) {
	rows, err := q.db.Query(ctx, listLessonsForCourse, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Lesson{}
	for rows.Next() {
		var i Lesson
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ModuleID,
			&i.Title,
			&i.Kind,
			&i.Body,
			&i.Dir,
			&i.DurationS,
			&i.IsPreview,
			&i.Status,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MediaID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModules = `-- name: ListModules :many
SELECT id, tenant_id, course_id, title, position, created_at, updated_at FROM modules WHERE course_id = $1 ORDER BY position, created_at
`

func (q *Queries) ListModules(ctx context.Context, courseID uuid.UUID) ([]Module, error) {
	rows, err := q.db.Query(ctx, listModules, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Module{}
	for rows.Next() {
		var i Module
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CourseID,
			&i.Title,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveLesson = `-- name: MoveLesson :one
UPDATE lessons SET module_id = $1, position = $2 WHERE id = $3 RETURNING id, tenant_id, module_id, title, kind, body, dir, duration_s, is_preview, status, position, created_at, updated_at, media_id
`

type MoveLessonParams struct {
	ModuleID uuid.UUID `json:"module_id"`
	Position float64   `json:"position"`
	ID       uuid.UUID `json:"id"`
}

func (q *Queries) MoveLesson(ctx context.Context, arg MoveLessonParams) (Lesson, error) {
	row := q.db.QueryRow(ctx, moveLesson, arg.ModuleID, arg.Position, arg.ID)
	var i Lesson
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ModuleID,
		&i.Title,
		&i.Kind,
		&i.Body,
		&i.Dir,
		&i.DurationS,
		&i.IsPreview,
		&i.Status,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MediaID,
	)
	return i, err
}

const moveModule = `-- name: MoveModule :one
UPDATE modules SET position = $1 WHERE id = $2 RETURNING id, tenant_id, course_id, title, position, created_at, updated_at
`

type MoveModuleParams struct {
	Position float64   `json:"position"`
	ID       uuid.UUID `json:"id"`
}

func (q *Queries) MoveModule(ctx context.Context, arg MoveModuleParams) (Module, error) {
	row := q.db.QueryRow(ctx, moveModule, arg.Position, arg.ID)
	var i Module
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CourseID,
		&i.Title,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setCourseStatus = `-- name: SetCourseStatus :one
UPDATE courses SET
  status = $1,
  published_at = CASE WHEN $1::publish_status = 'published' THEN coalesce(published_at, now()) ELSE published_at END
WHERE id = $2
RETURNING id, tenant_id, slug, title, summary, dir, status, visibility, price_minor, currency, created_by, published_at, created_at, updated_at
`

type SetCourseStatusParams struct {
	Status PublishStatus `json:"status"`
	ID     uuid.UUID     `json:"id"`
}

func (q *Queries) SetCourseStatus(ctx context.Context, arg SetCourseStatusParams) (Course, error) {
	row := q.db.QueryRow(ctx, setCourseStatus, arg.Status, arg.ID)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Slug,
		&i.Title,
		&i.Summary,
		&i.Dir,
		&i.Status,
		&i.Visibility,
		&i.PriceMinor,
		&i.Currency,
		&i.CreatedBy,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCourse = `-- name: UpdateCourse :one
UPDATE courses SET
  title       = coalesce($1, title),
  summary     = coalesce($2, summary),
  dir         = coalesce($3, dir),
  visibility  = coalesce($4, visibility),
  price_minor = coalesce($5, price_minor)
WHERE id = $6
RETURNING id, tenant_id, slug, title, summary, dir, status, visibility, price_minor, currency, created_by, published_at, created_at, updated_at
`

type UpdateCourseParams struct {
	Title      *string           `json:"title"`
	Summary    *string           `json:"summary"`
	Dir        *TextDir          `json:"dir"`
	Visibility *CourseVisibility `json:"visibility"`
	PriceMinor *int64            `json:"price_minor"`
	ID         uuid.UUID         `json:"id"`
}

func (q *Queries) UpdateCourse(ctx context.Context, arg UpdateCourseParams) (Course, error) {
	row := q.db.QueryRow(ctx, updateCourse,
		arg.Title,
		arg.Summary,
		arg.Dir,
		arg.Visibility,
		arg.PriceMinor,
		arg.ID,
	)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Slug,
		&i.Title,
		&i.Summary,
		&i.Dir,
		&i.Status,
		&i.Visibility,
		&i.PriceMinor,
		&i.Currency,
		&i.CreatedBy,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLesson = `-- name: UpdateLesson :one
UPDATE lessons SET
  title      = coalesce($1, title),
  body       = coalesce($2, body),
  kind       = coalesce($3, kind),
  dir        = coalesce($4, dir),
  duration_s = coalesce($5, duration_s),
  is_preview = coalesce($6, is_preview),
  status     = coalesce($7, status)
WHERE id = $8
RETURNING id, tenant_id, module_id, title, kind, body, dir, duration_s, is_preview, status, position, created_at, updated_at, media_id
`

type UpdateLessonParams struct {
	Title     *string        `json:"title"`
	Body      *string        `json:"body"`
	Kind      *LessonKind    `json:"kind"`
	Dir       *TextDir       `json:"dir"`
	DurationS *int32         `json:"duration_s"`
	IsPreview *bool          `json:"is_preview"`
	Status    *PublishStatus `json:"status"`
	ID        uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateLesson(ctx context.Context, arg UpdateLessonParams) (Lesson, error) {
	row := q.db.QueryRow(ctx, updateLesson,
		arg.Title,
		arg.Body,
		arg.Kind,
		arg.Dir,
		arg.DurationS,
		arg.IsPreview,
		arg.Status,
		arg.ID,
	)
	var i Lesson
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ModuleID,
		&i.Title,
		&i.Kind,
		&i.Body,
		&i.Dir,
		&i.DurationS,
		&i.IsPreview,
		&i.Status,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MediaID,
	)
	return i, err
}
