// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: certlayout.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const certificateBackground = `-- name: CertificateBackground :one
SELECT background, background_type FROM certificate_layout_for($1)
`

type CertificateBackgroundRow struct {
	Background     []byte `json:"background"`
	BackgroundType string `json:"background_type"`
}

func (q *Queries) CertificateBackground(ctx context.Context, tenantID uuid.UUID) (CertificateBackgroundRow, error) {
	row := q.db.QueryRow(ctx, certificateBackground, tenantID)
	var i CertificateBackgroundRow
	err := row.Scan(&i.Background, &i.BackgroundType)
	return i, err
}

const certificateTenant = `-- name: CertificateTenant :one
SELECT certificate_tenant FROM certificate_tenant($1)
`

func (q *Queries) CertificateTenant(ctx context.Context, serial string) (uuid.NullUUID, error) {
	row := q.db.QueryRow(ctx, certificateTenant, serial)
	var certificate_tenant uuid.NullUUID
	err := row.Scan(&certificate_tenant)
	return certificate_tenant, err
}

const clearCertificateBackground = `-- name: ClearCertificateBackground :exec
UPDATE certificate_layouts SET background = NULL, background_type = '' WHERE tenant_id = $1
`

func (q *Queries) ClearCertificateBackground(ctx context.Context, tenantID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearCertificateBackground, tenantID)
	return err
}

const getCertificateLayout = `-- name: GetCertificateLayout :one
SELECT tenant_id, fields, background_type, (background IS NOT NULL)::boolean AS has_background, updated_at
FROM certificate_layouts WHERE tenant_id = $1
`

type GetCertificateLayoutRow struct {
	TenantID       uuid.UUID          `json:"tenant_id"`
	Fields         []byte             `json:"fields"`
	BackgroundType string             `json:"background_type"`
	HasBackground  bool               `json:"has_background"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetCertificateLayout(ctx context.Context, tenantID uuid.UUID) (GetCertificateLayoutRow, error) {
	row := q.db.QueryRow(ctx, getCertificateLayout, tenantID)
	var i GetCertificateLayoutRow
	err := row.Scan(
		&i.TenantID,
		&i.Fields,
		&i.BackgroundType,
		&i.HasBackground,
		&i.UpdatedAt,
	)
	return i, err
}

const ownCertificateBackground = `-- name: OwnCertificateBackground :one
SELECT background, background_type FROM certificate_layouts WHERE tenant_id = $1
`

type OwnCertificateBackgroundRow struct {
	Background     []byte `json:"background"`
	BackgroundType string `json:"background_type"`
}

func (q *Queries) OwnCertificateBackground(ctx context.Context, tenantID uuid.UUID) (OwnCertificateBackgroundRow, error) {
	row := q.db.QueryRow(ctx, ownCertificateBackground, tenantID)
	var i OwnCertificateBackgroundRow
	err := row.Scan(&i.Background, &i.BackgroundType)
	return i, err
}

const publicCertificateLayout = `-- name: PublicCertificateLayout :one
SELECT fields, background_type, (background IS NOT NULL)::boolean AS has_background
FROM certificate_layout_for($1)
`

type PublicCertificateLayoutRow struct {
	Fields         []byte `json:"fields"`
	BackgroundType string `json:"background_type"`
	HasBackground  bool   `json:"has_background"`
}

func (q *Queries) PublicCertificateLayout(ctx context.Context, tenantID uuid.UUID) (PublicCertificateLayoutRow, error) {
	row := q.db.QueryRow(ctx, publicCertificateLayout, tenantID)
	var i PublicCertificateLayoutRow
	err := row.Scan(&i.Fields, &i.BackgroundType, &i.HasBackground)
	return i, err
}

const saveCertificateBackground = `-- name: SaveCertificateBackground :exec
INSERT INTO certificate_layouts (tenant_id, background, background_type)
VALUES ($1, $2, $3)
ON CONFLICT (tenant_id) DO UPDATE
SET background = excluded.background, background_type = excluded.background_type
`

type SaveCertificateBackgroundParams struct {
	TenantID       uuid.UUID `json:"tenant_id"`
	Background     []byte    `json:"background"`
	BackgroundType string    `json:"background_type"`
}

func (q *Queries) SaveCertificateBackground(ctx context.Context, arg SaveCertificateBackgroundParams) error {
	_, err := q.db.Exec(ctx, saveCertificateBackground, arg.TenantID, arg.Background, arg.BackgroundType)
	return err
}

const saveCertificateFields = `-- name: SaveCertificateFields :one
INSERT INTO certificate_layouts (tenant_id, fields) VALUES ($1, $2)
ON CONFLICT (tenant_id) DO UPDATE SET fields = excluded.fields
RETURNING tenant_id, fields, background_type, (background IS NOT NULL)::boolean AS has_background, updated_at
`

type SaveCertificateFieldsParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Fields   []byte    `json:"fields"`
}

type SaveCertificateFieldsRow struct {
	TenantID       uuid.UUID          `json:"tenant_id"`
	Fields         []byte             `json:"fields"`
	BackgroundType string             `json:"background_type"`
	HasBackground  bool               `json:"has_background"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) SaveCertificateFields(ctx context.Context, arg SaveCertificateFieldsParams) (SaveCertificateFieldsRow, error) {
	row := q.db.QueryRow(ctx, saveCertificateFields, arg.TenantID, arg.Fields)
	var i SaveCertificateFieldsRow
	err := row.Scan(
		&i.TenantID,
		&i.Fields,
		&i.BackgroundType,
		&i.HasBackground,
		&i.UpdatedAt,
	)
	return i, err
}
