// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: certificates.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const certificateForEnrollment = `-- name: CertificateForEnrollment :one
SELECT id, tenant_id, course_id, enrollment_id, user_id, serial, recipient_name, course_title, issuer_name, grade_percent, issued_at, revoked_at, revoked_reason, issued_by FROM certificates WHERE enrollment_id = $1
`

func (q *Queries) CertificateForEnrollment(ctx context.Context, enrollmentID uuid.UUID) (Certificate, error) {
	row := q.db.QueryRow(ctx, certificateForEnrollment, enrollmentID)
	var i Certificate
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CourseID,
		&i.EnrollmentID,
		&i.UserID,
		&i.Serial,
		&i.RecipientName,
		&i.CourseTitle,
		&i.IssuerName,
		&i.GradePercent,
		&i.IssuedAt,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.IssuedBy,
	)
	return i, err
}

const getCertificate = `-- name: GetCertificate :one
SELECT id, tenant_id, course_id, enrollment_id, user_id, serial, recipient_name, course_title, issuer_name, grade_percent, issued_at, revoked_at, revoked_reason, issued_by FROM certificates WHERE id = $1
`

func (q *Queries) GetCertificate(ctx context.Context, id uuid.UUID) (Certificate, error) {
	row := q.db.QueryRow(ctx, getCertificate, id)
	var i Certificate
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CourseID,
		&i.EnrollmentID,
		&i.UserID,
		&i.Serial,
		&i.RecipientName,
		&i.CourseTitle,
		&i.IssuerName,
		&i.GradePercent,
		&i.IssuedAt,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.IssuedBy,
	)
	return i, err
}

const issueCertificate = `-- name: IssueCertificate :one
INSERT INTO certificates (tenant_id, course_id, enrollment_id, user_id, serial,
                          recipient_name, course_title, issuer_name, grade_percent, issued_by)
VALUES ($1, $2, $3, $4, $5,
        $6, $7, $8, $9, $10)
RETURNING id, tenant_id, course_id, enrollment_id, user_id, serial, recipient_name, course_title, issuer_name, grade_percent, issued_at, revoked_at, revoked_reason, issued_by
`

type IssueCertificateParams struct {
	TenantID      uuid.UUID     `json:"tenant_id"`
	CourseID      uuid.UUID     `json:"course_id"`
	EnrollmentID  uuid.UUID     `json:"enrollment_id"`
	UserID        uuid.UUID     `json:"user_id"`
	Serial        string        `json:"serial"`
	RecipientName string        `json:"recipient_name"`
	CourseTitle   string        `json:"course_title"`
	IssuerName    string        `json:"issuer_name"`
	GradePercent  *int16        `json:"grade_percent"`
	IssuedBy      uuid.NullUUID `json:"issued_by"`
}

func (q *Queries) IssueCertificate(ctx context.Context, arg IssueCertificateParams) (Certificate, error) {
	row := q.db.QueryRow(ctx, issueCertificate,
		arg.TenantID,
		arg.CourseID,
		arg.EnrollmentID,
		arg.UserID,
		arg.Serial,
		arg.RecipientName,
		arg.CourseTitle,
		arg.IssuerName,
		arg.GradePercent,
		arg.IssuedBy,
	)
	var i Certificate
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CourseID,
		&i.EnrollmentID,
		&i.UserID,
		&i.Serial,
		&i.RecipientName,
		&i.CourseTitle,
		&i.IssuerName,
		&i.GradePercent,
		&i.IssuedAt,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.IssuedBy,
	)
	return i, err
}

const listCourseCertificates = `-- name: ListCourseCertificates :many
SELECT c.id, c.tenant_id, c.course_id, c.enrollment_id, c.user_id, c.serial, c.recipient_name, c.course_title, c.issuer_name, c.grade_percent, c.issued_at, c.revoked_at, c.revoked_reason, c.issued_by, u.full_name
FROM certificates c JOIN users u ON u.id = c.user_id
WHERE c.course_id = $1
ORDER BY c.issued_at DESC
LIMIT $3 OFFSET $2
`

type ListCourseCertificatesParams struct {
	CourseID   uuid.UUID `json:"course_id"`
	PageOffset int32     `json:"page_offset"`
	PageLimit  int32     `json:"page_limit"`
}

type ListCourseCertificatesRow struct {
	Certificate Certificate `json:"certificate"`
	FullName    string      `json:"full_name"`
}

func (q *Queries) ListCourseCertificates(ctx context.Context, arg ListCourseCertificatesParams) ([]ListCourseCertificatesRow, error) {
	rows, err := q.db.Query(ctx, listCourseCertificates, arg.CourseID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCourseCertificatesRow{}
	for rows.Next() {
		var i ListCourseCertificatesRow
		if err := rows.Scan(
			&i.Certificate.ID,
			&i.Certificate.TenantID,
			&i.Certificate.CourseID,
			&i.Certificate.EnrollmentID,
			&i.Certificate.UserID,
			&i.Certificate.Serial,
			&i.Certificate.RecipientName,
			&i.Certificate.CourseTitle,
			&i.Certificate.IssuerName,
			&i.Certificate.GradePercent,
			&i.Certificate.IssuedAt,
			&i.Certificate.RevokedAt,
			&i.Certificate.RevokedReason,
			&i.Certificate.IssuedBy,
			&i.FullName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMyCertificates = `-- name: ListMyCertificates :many
SELECT c.id, c.tenant_id, c.course_id, c.enrollment_id, c.user_id, c.serial, c.recipient_name, c.course_title, c.issuer_name, c.grade_percent, c.issued_at, c.revoked_at, c.revoked_reason, c.issued_by, co.slug AS course_slug
FROM certificates c JOIN courses co ON co.id = c.course_id
WHERE c.user_id = $1
ORDER BY c.issued_at DESC
`

type ListMyCertificatesRow struct {
	Certificate Certificate `json:"certificate"`
	CourseSlug  string      `json:"course_slug"`
}

func (q *Queries) ListMyCertificates(ctx context.Context, userID uuid.UUID) ([]ListMyCertificatesRow, error) {
	rows, err := q.db.Query(ctx, listMyCertificates, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMyCertificatesRow{}
	for rows.Next() {
		var i ListMyCertificatesRow
		if err := rows.Scan(
			&i.Certificate.ID,
			&i.Certificate.TenantID,
			&i.Certificate.CourseID,
			&i.Certificate.EnrollmentID,
			&i.Certificate.UserID,
			&i.Certificate.Serial,
			&i.Certificate.RecipientName,
			&i.Certificate.CourseTitle,
			&i.Certificate.IssuerName,
			&i.Certificate.GradePercent,
			&i.Certificate.IssuedAt,
			&i.Certificate.RevokedAt,
			&i.Certificate.RevokedReason,
			&i.Certificate.IssuedBy,
			&i.CourseSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeCertificate = `-- name: RevokeCertificate :one
UPDATE certificates SET revoked_at = now(), revoked_reason = $1
WHERE id = $2 AND revoked_at IS NULL
RETURNING id, tenant_id, course_id, enrollment_id, user_id, serial, recipient_name, course_title, issuer_name, grade_percent, issued_at, revoked_at, revoked_reason, issued_by
`

type RevokeCertificateParams struct {
	RevokedReason string    `json:"revoked_reason"`
	ID            uuid.UUID `json:"id"`
}

func (q *Queries) RevokeCertificate(ctx context.Context, arg RevokeCertificateParams) (Certificate, error) {
	row := q.db.QueryRow(ctx, revokeCertificate, arg.RevokedReason, arg.ID)
	var i Certificate
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CourseID,
		&i.EnrollmentID,
		&i.UserID,
		&i.Serial,
		&i.RecipientName,
		&i.CourseTitle,
		&i.IssuerName,
		&i.GradePercent,
		&i.IssuedAt,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.IssuedBy,
	)
	return i, err
}

const verifyCertificate = `-- name: VerifyCertificate :one
SELECT serial, recipient_name, course_title, issuer_name, grade_percent, issued_at, revoked_at, tenant_dir FROM certificate_verifications WHERE serial = $1
`

func (q *Queries) VerifyCertificate(ctx context.Context, serial string) (CertificateVerification, error) {
	row := q.db.QueryRow(ctx, verifyCertificate, serial)
	var i CertificateVerification
	err := row.Scan(
		&i.Serial,
		&i.RecipientName,
		&i.CourseTitle,
		&i.IssuerName,
		&i.GradePercent,
		&i.IssuedAt,
		&i.RevokedAt,
		&i.TenantDir,
	)
	return i, err
}
