// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: collections.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addCourseToCollection = `-- name: AddCourseToCollection :exec
INSERT INTO collection_courses (collection_id, course_id, tenant_id, position)
VALUES ($1, $2, $3,
        coalesce((SELECT max(position) + 1 FROM collection_courses WHERE collection_id = $1), 1))
ON CONFLICT DO NOTHING
`

type AddCourseToCollectionParams struct {
	CollectionID uuid.UUID `json:"collection_id"`
	CourseID     uuid.UUID `json:"course_id"`
	TenantID     uuid.UUID `json:"tenant_id"`
}

func (q *Queries) AddCourseToCollection(ctx context.Context, arg AddCourseToCollectionParams) error {
	_, err := q.db.Exec(ctx, addCourseToCollection, arg.CollectionID, arg.CourseID, arg.TenantID)
	return err
}

const collectionCourses = `-- name: CollectionCourses :many
SELECT c.id, c.tenant_id, c.slug, c.title, c.summary, c.dir, c.status, c.visibility, c.price_minor, c.currency, c.created_by, c.published_at, c.created_at, c.updated_at, c.installments, c.installment_gap_days, cc.position
FROM collection_courses cc JOIN courses c ON c.id = cc.course_id
WHERE cc.collection_id = $1
ORDER BY cc.position
`

type CollectionCoursesRow struct {
	Course   Course  `json:"course"`
	Position float64 `json:"position"`
}

func (q *Queries) CollectionCourses(ctx context.Context, collectionID uuid.UUID) ([]CollectionCoursesRow, error) {
	rows, err := q.db.Query(ctx, collectionCourses, collectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CollectionCoursesRow{}
	for rows.Next() {
		var i CollectionCoursesRow
		if err := rows.Scan(
			&i.Course.ID,
			&i.Course.TenantID,
			&i.Course.Slug,
			&i.Course.Title,
			&i.Course.Summary,
			&i.Course.Dir,
			&i.Course.Status,
			&i.Course.Visibility,
			&i.Course.PriceMinor,
			&i.Course.Currency,
			&i.Course.CreatedBy,
			&i.Course.PublishedAt,
			&i.Course.CreatedAt,
			&i.Course.UpdatedAt,
			&i.Course.Installments,
			&i.Course.InstallmentGapDays,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createCollection = `-- name: CreateCollection :one
INSERT INTO collections (tenant_id, kind, slug, title, summary, dir, price_minor, currency)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, tenant_id, kind, slug, title, summary, dir, status, price_minor, currency, created_at, updated_at
`

type CreateCollectionParams struct {
	TenantID   uuid.UUID      `json:"tenant_id"`
	Kind       CollectionKind `json:"kind"`
	Slug       string         `json:"slug"`
	Title      string         `json:"title"`
	Summary    string         `json:"summary"`
	Dir        TextDir        `json:"dir"`
	PriceMinor int64          `json:"price_minor"`
	Currency   string         `json:"currency"`
}

func (q *Queries) CreateCollection(ctx context.Context, arg CreateCollectionParams) (Collection, error) {
	row := q.db.QueryRow(ctx, createCollection,
		arg.TenantID,
		arg.Kind,
		arg.Slug,
		arg.Title,
		arg.Summary,
		arg.Dir,
		arg.PriceMinor,
		arg.Currency,
	)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Kind,
		&i.Slug,
		&i.Title,
		&i.Summary,
		&i.Dir,
		&i.Status,
		&i.PriceMinor,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTopic = `-- name: CreateTopic :one
INSERT INTO topics (tenant_id, name, slug) VALUES ($1, $2, $3) RETURNING id, tenant_id, name, slug, created_at
`

type CreateTopicParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Name     string    `json:"name"`
	Slug     string    `json:"slug"`
}

func (q *Queries) CreateTopic(ctx context.Context, arg CreateTopicParams) (Topic, error) {
	row := q.db.QueryRow(ctx, createTopic, arg.TenantID, arg.Name, arg.Slug)
	var i Topic
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCollection = `-- name: DeleteCollection :execrows
DELETE FROM collections WHERE id = $1
`

func (q *Queries) DeleteCollection(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCollection, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTopic = `-- name: DeleteTopic :execrows
DELETE FROM topics WHERE id = $1
`

func (q *Queries) DeleteTopic(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTopic, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCollection = `-- name: GetCollection :one
SELECT id, tenant_id, kind, slug, title, summary, dir, status, price_minor, currency, created_at, updated_at FROM collections WHERE slug = $1
`

func (q *Queries) GetCollection(ctx context.Context, slug string) (Collection, error) {
	row := q.db.QueryRow(ctx, getCollection, slug)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Kind,
		&i.Slug,
		&i.Title,
		&i.Summary,
		&i.Dir,
		&i.Status,
		&i.PriceMinor,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCollections = `-- name: ListCollections :many
SELECT c.id, c.tenant_id, c.kind, c.slug, c.title, c.summary, c.dir, c.status, c.price_minor, c.currency, c.created_at, c.updated_at, (SELECT count(*) FROM collection_courses cc WHERE cc.collection_id = c.id) AS courses
FROM collections c
WHERE ($1::collection_kind IS NULL OR c.kind = $1::collection_kind)
ORDER BY c.title
`

type ListCollectionsRow struct {
	ID         uuid.UUID          `json:"id"`
	TenantID   uuid.UUID          `json:"tenant_id"`
	Kind       CollectionKind     `json:"kind"`
	Slug       string             `json:"slug"`
	Title      string             `json:"title"`
	Summary    string             `json:"summary"`
	Dir        TextDir            `json:"dir"`
	Status     PublishStatus      `json:"status"`
	PriceMinor int64              `json:"price_minor"`
	Currency   string             `json:"currency"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	Courses    int64              `json:"courses"`
}

func (q *Queries) ListCollections(ctx context.Context, kind *CollectionKind) ([]ListCollectionsRow, error) {
	rows, err := q.db.Query(ctx, listCollections, kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCollectionsRow{}
	for rows.Next() {
		var i ListCollectionsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Kind,
			&i.Slug,
			&i.Title,
			&i.Summary,
			&i.Dir,
			&i.Status,
			&i.PriceMinor,
			&i.Currency,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Courses,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopics = `-- name: ListTopics :many
SELECT t.id, t.tenant_id, t.name, t.slug, t.created_at, (SELECT count(*) FROM course_topics ct WHERE ct.topic_id = t.id) AS courses
FROM topics t ORDER BY t.name
`

type ListTopicsRow struct {
	ID        uuid.UUID          `json:"id"`
	TenantID  uuid.UUID          `json:"tenant_id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Courses   int64              `json:"courses"`
}

func (q *Queries) ListTopics(ctx context.Context) ([]ListTopicsRow, error) {
	rows, err := q.db.Query(ctx, listTopics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTopicsRow{}
	for rows.Next() {
		var i ListTopicsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
			&i.Courses,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveCourseInCollection = `-- name: MoveCourseInCollection :execrows
UPDATE collection_courses SET position = $1
WHERE collection_id = $2 AND course_id = $3
`

type MoveCourseInCollectionParams struct {
	Position     float64   `json:"position"`
	CollectionID uuid.UUID `json:"collection_id"`
	CourseID     uuid.UUID `json:"course_id"`
}

func (q *Queries) MoveCourseInCollection(ctx context.Context, arg MoveCourseInCollectionParams) (int64, error) {
	result, err := q.db.Exec(ctx, moveCourseInCollection, arg.Position, arg.CollectionID, arg.CourseID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const removeCourseFromCollection = `-- name: RemoveCourseFromCollection :execrows
DELETE FROM collection_courses WHERE collection_id = $1 AND course_id = $2
`

type RemoveCourseFromCollectionParams struct {
	CollectionID uuid.UUID `json:"collection_id"`
	CourseID     uuid.UUID `json:"course_id"`
}

func (q *Queries) RemoveCourseFromCollection(ctx context.Context, arg RemoveCourseFromCollectionParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeCourseFromCollection, arg.CollectionID, arg.CourseID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const tagCourse = `-- name: TagCourse :exec
INSERT INTO course_topics (course_id, topic_id, tenant_id)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type TagCourseParams struct {
	CourseID uuid.UUID `json:"course_id"`
	TopicID  uuid.UUID `json:"topic_id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) TagCourse(ctx context.Context, arg TagCourseParams) error {
	_, err := q.db.Exec(ctx, tagCourse, arg.CourseID, arg.TopicID, arg.TenantID)
	return err
}

const topicsOfCourse = `-- name: TopicsOfCourse :many
SELECT t.id, t.tenant_id, t.name, t.slug, t.created_at FROM course_topics ct JOIN topics t ON t.id = ct.topic_id
WHERE ct.course_id = $1 ORDER BY t.name
`

func (q *Queries) TopicsOfCourse(ctx context.Context, courseID uuid.UUID) ([]Topic, error) {
	rows, err := q.db.Query(ctx, topicsOfCourse, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Topic{}
	for rows.Next() {
		var i Topic
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const untagCourse = `-- name: UntagCourse :execrows
DELETE FROM course_topics WHERE course_id = $1 AND topic_id = $2
`

type UntagCourseParams struct {
	CourseID uuid.UUID `json:"course_id"`
	TopicID  uuid.UUID `json:"topic_id"`
}

func (q *Queries) UntagCourse(ctx context.Context, arg UntagCourseParams) (int64, error) {
	result, err := q.db.Exec(ctx, untagCourse, arg.CourseID, arg.TopicID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateCollection = `-- name: UpdateCollection :one
UPDATE collections SET
  title       = coalesce($1, title),
  summary     = coalesce($2, summary),
  status      = coalesce($3, status),
  price_minor = coalesce($4, price_minor)
WHERE id = $5
RETURNING id, tenant_id, kind, slug, title, summary, dir, status, price_minor, currency, created_at, updated_at
`

type UpdateCollectionParams struct {
	Title      *string        `json:"title"`
	Summary    *string        `json:"summary"`
	Status     *PublishStatus `json:"status"`
	PriceMinor *int64         `json:"price_minor"`
	ID         uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateCollection(ctx context.Context, arg UpdateCollectionParams) (Collection, error) {
	row := q.db.QueryRow(ctx, updateCollection,
		arg.Title,
		arg.Summary,
		arg.Status,
		arg.PriceMinor,
		arg.ID,
	)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Kind,
		&i.Slug,
		&i.Title,
		&i.Summary,
		&i.Dir,
		&i.Status,
		&i.PriceMinor,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
