// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: coupons.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const couponByCode = `-- name: CouponByCode :one
SELECT id, tenant_id, code, kind, value, course_id, max_redemptions, redeemed, starts_at, ends_at, active, created_by, created_at, updated_at FROM coupons WHERE code = $1
`

func (q *Queries) CouponByCode(ctx context.Context, code string) (Coupon, error) {
	row := q.db.QueryRow(ctx, couponByCode, code)
	var i Coupon
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Kind,
		&i.Value,
		&i.CourseID,
		&i.MaxRedemptions,
		&i.Redeemed,
		&i.StartsAt,
		&i.EndsAt,
		&i.Active,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCoupon = `-- name: CreateCoupon :one
INSERT INTO coupons (tenant_id, code, kind, value, course_id, max_redemptions, starts_at, ends_at, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, tenant_id, code, kind, value, course_id, max_redemptions, redeemed, starts_at, ends_at, active, created_by, created_at, updated_at
`

type CreateCouponParams struct {
	TenantID       uuid.UUID          `json:"tenant_id"`
	Code           string             `json:"code"`
	Kind           DiscountKind       `json:"kind"`
	Value          int64              `json:"value"`
	CourseID       uuid.NullUUID      `json:"course_id"`
	MaxRedemptions *int32             `json:"max_redemptions"`
	StartsAt       pgtype.Timestamptz `json:"starts_at"`
	EndsAt         pgtype.Timestamptz `json:"ends_at"`
	CreatedBy      uuid.NullUUID      `json:"created_by"`
}

func (q *Queries) CreateCoupon(ctx context.Context, arg CreateCouponParams) (Coupon, error) {
	row := q.db.QueryRow(ctx, createCoupon,
		arg.TenantID,
		arg.Code,
		arg.Kind,
		arg.Value,
		arg.CourseID,
		arg.MaxRedemptions,
		arg.StartsAt,
		arg.EndsAt,
		arg.CreatedBy,
	)
	var i Coupon
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Kind,
		&i.Value,
		&i.CourseID,
		&i.MaxRedemptions,
		&i.Redeemed,
		&i.StartsAt,
		&i.EndsAt,
		&i.Active,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCoupon = `-- name: DeleteCoupon :execrows
DELETE FROM coupons WHERE id = $1
`

func (q *Queries) DeleteCoupon(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCoupon, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listCoupons = `-- name: ListCoupons :many
SELECT id, tenant_id, code, kind, value, course_id, max_redemptions, redeemed, starts_at, ends_at, active, created_by, created_at, updated_at FROM coupons ORDER BY created_at DESC LIMIT $2 OFFSET $1
`

type ListCouponsParams struct {
	PageOffset int32 `json:"page_offset"`
	PageLimit  int32 `json:"page_limit"`
}

func (q *Queries) ListCoupons(ctx context.Context, arg ListCouponsParams) ([]Coupon, error) {
	rows, err := q.db.Query(ctx, listCoupons, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Coupon{}
	for rows.Next() {
		var i Coupon
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Code,
			&i.Kind,
			&i.Value,
			&i.CourseID,
			&i.MaxRedemptions,
			&i.Redeemed,
			&i.StartsAt,
			&i.EndsAt,
			&i.Active,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const redeemCoupon = `-- name: RedeemCoupon :execrows
UPDATE coupons SET redeemed = redeemed + 1
WHERE id = $1 AND (max_redemptions IS NULL OR redeemed < max_redemptions)
`

func (q *Queries) RedeemCoupon(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, redeemCoupon, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setCouponActive = `-- name: SetCouponActive :one
UPDATE coupons SET active = $1 WHERE id = $2 RETURNING id, tenant_id, code, kind, value, course_id, max_redemptions, redeemed, starts_at, ends_at, active, created_by, created_at, updated_at
`

type SetCouponActiveParams struct {
	Active bool      `json:"active"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) SetCouponActive(ctx context.Context, arg SetCouponActiveParams) (Coupon, error) {
	row := q.db.QueryRow(ctx, setCouponActive, arg.Active, arg.ID)
	var i Coupon
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Kind,
		&i.Value,
		&i.CourseID,
		&i.MaxRedemptions,
		&i.Redeemed,
		&i.StartsAt,
		&i.EndsAt,
		&i.Active,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
