// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: demo.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const countTenantCourses = `-- name: CountTenantCourses :one
SELECT count(*) FROM courses
`

func (q *Queries) CountTenantCourses(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTenantCourses)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const markTenantDemo = `-- name: MarkTenantDemo :exec
UPDATE tenants SET demo = true, institution = $1 WHERE id = $2
`

type MarkTenantDemoParams struct {
	Institution InstitutionKind `json:"institution"`
	ID          uuid.UUID       `json:"id"`
}

func (q *Queries) MarkTenantDemo(ctx context.Context, arg MarkTenantDemoParams) error {
	_, err := q.db.Exec(ctx, markTenantDemo, arg.Institution, arg.ID)
	return err
}

const recordDemoLead = `-- name: RecordDemoLead :one
SELECT record_demo_lead($1, $2, $3, $4, $5, $6, $7, $8)
`

type RecordDemoLeadParams struct {
	FullName     string `json:"full_name"`
	Email        string `json:"email"`
	Phone        string `json:"phone"`
	Organisation string `json:"organisation"`
	Role         string `json:"role"`
	Learners     string `json:"learners"`
	Runs         string `json:"runs"`
	Note         string `json:"note"`
}

func (q *Queries) RecordDemoLead(ctx context.Context, arg RecordDemoLeadParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, recordDemoLead,
		arg.FullName,
		arg.Email,
		arg.Phone,
		arg.Organisation,
		arg.Role,
		arg.Learners,
		arg.Runs,
		arg.Note,
	)
	var record_demo_lead uuid.UUID
	err := row.Scan(&record_demo_lead)
	return record_demo_lead, err
}
