// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: enrollment.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const cancelEnrollment = `-- name: CancelEnrollment :execrows
UPDATE enrollments SET status = 'cancelled' WHERE id = $1 AND status <> 'cancelled'
`

func (q *Queries) CancelEnrollment(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, cancelEnrollment, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const completeEnrollment = `-- name: CompleteEnrollment :one
UPDATE enrollments SET status = 'completed', completed_at = coalesce(completed_at, now())
WHERE id = $1
RETURNING id, tenant_id, course_id, user_id, status, source, completed_at, created_at, updated_at
`

func (q *Queries) CompleteEnrollment(ctx context.Context, id uuid.UUID) (Enrollment, error) {
	row := q.db.QueryRow(ctx, completeEnrollment, id)
	var i Enrollment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CourseID,
		&i.UserID,
		&i.Status,
		&i.Source,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countCompletedLessons = `-- name: CountCompletedLessons :one
SELECT count(*) FROM lesson_progress WHERE enrollment_id = $1 AND state = 'completed'
`

func (q *Queries) CountCompletedLessons(ctx context.Context, enrollmentID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCompletedLessons, enrollmentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPublishedLessons = `-- name: CountPublishedLessons :one
SELECT count(*) FROM lessons l
JOIN modules m ON m.id = l.module_id
WHERE m.course_id = $1 AND l.status = 'published'
`

func (q *Queries) CountPublishedLessons(ctx context.Context, courseID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPublishedLessons, courseID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const enrollUser = `-- name: EnrollUser :one
INSERT INTO enrollments (tenant_id, course_id, user_id, source)
VALUES ($1, $2, $3, $4)
ON CONFLICT (course_id, user_id) DO UPDATE
SET status = 'active', completed_at = NULL
RETURNING id, tenant_id, course_id, user_id, status, source, completed_at, created_at, updated_at
`

type EnrollUserParams struct {
	TenantID uuid.UUID        `json:"tenant_id"`
	CourseID uuid.UUID        `json:"course_id"`
	UserID   uuid.UUID        `json:"user_id"`
	Source   EnrollmentSource `json:"source"`
}

func (q *Queries) EnrollUser(ctx context.Context, arg EnrollUserParams) (Enrollment, error) {
	row := q.db.QueryRow(ctx, enrollUser,
		arg.TenantID,
		arg.CourseID,
		arg.UserID,
		arg.Source,
	)
	var i Enrollment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CourseID,
		&i.UserID,
		&i.Status,
		&i.Source,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEnrollment = `-- name: GetEnrollment :one
SELECT id, tenant_id, course_id, user_id, status, source, completed_at, created_at, updated_at FROM enrollments WHERE course_id = $1 AND user_id = $2
`

type GetEnrollmentParams struct {
	CourseID uuid.UUID `json:"course_id"`
	UserID   uuid.UUID `json:"user_id"`
}

func (q *Queries) GetEnrollment(ctx context.Context, arg GetEnrollmentParams) (Enrollment, error) {
	row := q.db.QueryRow(ctx, getEnrollment, arg.CourseID, arg.UserID)
	var i Enrollment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CourseID,
		&i.UserID,
		&i.Status,
		&i.Source,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lessonCourse = `-- name: LessonCourse :one
SELECT m.course_id FROM lessons l JOIN modules m ON m.id = l.module_id WHERE l.id = $1
`

func (q *Queries) LessonCourse(ctx context.Context, lessonID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lessonCourse, lessonID)
	var course_id uuid.UUID
	err := row.Scan(&course_id)
	return course_id, err
}

const listCourseRoster = `-- name: ListCourseRoster :many
SELECT
  e.id, e.tenant_id, e.course_id, e.user_id, e.status, e.source, e.completed_at, e.created_at, e.updated_at,
  u.full_name,
  count(p.lesson_id) FILTER (WHERE p.state = 'completed') AS lessons_completed
FROM enrollments e
JOIN users u ON u.id = e.user_id
LEFT JOIN lesson_progress p ON p.enrollment_id = e.id
WHERE e.course_id = $1 AND e.status <> 'cancelled'
GROUP BY e.id, u.full_name
ORDER BY u.full_name
LIMIT $3 OFFSET $2
`

type ListCourseRosterParams struct {
	CourseID   uuid.UUID `json:"course_id"`
	PageOffset int32     `json:"page_offset"`
	PageLimit  int32     `json:"page_limit"`
}

type ListCourseRosterRow struct {
	Enrollment       Enrollment `json:"enrollment"`
	FullName         string     `json:"full_name"`
	LessonsCompleted int64      `json:"lessons_completed"`
}

// Roster with a completion count, so the UI never asks per learner.
func (q *Queries) ListCourseRoster(ctx context.Context, arg ListCourseRosterParams) ([]ListCourseRosterRow, error) {
	rows, err := q.db.Query(ctx, listCourseRoster, arg.CourseID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCourseRosterRow{}
	for rows.Next() {
		var i ListCourseRosterRow
		if err := rows.Scan(
			&i.Enrollment.ID,
			&i.Enrollment.TenantID,
			&i.Enrollment.CourseID,
			&i.Enrollment.UserID,
			&i.Enrollment.Status,
			&i.Enrollment.Source,
			&i.Enrollment.CompletedAt,
			&i.Enrollment.CreatedAt,
			&i.Enrollment.UpdatedAt,
			&i.FullName,
			&i.LessonsCompleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMyEnrollments = `-- name: ListMyEnrollments :many
SELECT e.id, e.tenant_id, e.course_id, e.user_id, e.status, e.source, e.completed_at, e.created_at, e.updated_at, c.slug, c.title, c.dir, c.status AS course_status
FROM enrollments e JOIN courses c ON c.id = e.course_id
WHERE e.user_id = $1 AND e.status <> 'cancelled'
ORDER BY e.created_at DESC
LIMIT $3 OFFSET $2
`

type ListMyEnrollmentsParams struct {
	UserID     uuid.UUID `json:"user_id"`
	PageOffset int32     `json:"page_offset"`
	PageLimit  int32     `json:"page_limit"`
}

type ListMyEnrollmentsRow struct {
	Enrollment   Enrollment    `json:"enrollment"`
	Slug         string        `json:"slug"`
	Title        string        `json:"title"`
	Dir          TextDir       `json:"dir"`
	CourseStatus PublishStatus `json:"course_status"`
}

func (q *Queries) ListMyEnrollments(ctx context.Context, arg ListMyEnrollmentsParams) ([]ListMyEnrollmentsRow, error) {
	rows, err := q.db.Query(ctx, listMyEnrollments, arg.UserID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMyEnrollmentsRow{}
	for rows.Next() {
		var i ListMyEnrollmentsRow
		if err := rows.Scan(
			&i.Enrollment.ID,
			&i.Enrollment.TenantID,
			&i.Enrollment.CourseID,
			&i.Enrollment.UserID,
			&i.Enrollment.Status,
			&i.Enrollment.Source,
			&i.Enrollment.CompletedAt,
			&i.Enrollment.CreatedAt,
			&i.Enrollment.UpdatedAt,
			&i.Slug,
			&i.Title,
			&i.Dir,
			&i.CourseStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProgressForEnrollment = `-- name: ListProgressForEnrollment :many
SELECT tenant_id, enrollment_id, lesson_id, state, position_s, completed_at, updated_at FROM lesson_progress WHERE enrollment_id = $1
`

func (q *Queries) ListProgressForEnrollment(ctx context.Context, enrollmentID uuid.UUID) ([]LessonProgress, error) {
	rows, err := q.db.Query(ctx, listProgressForEnrollment, enrollmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LessonProgress{}
	for rows.Next() {
		var i LessonProgress
		if err := rows.Scan(
			&i.TenantID,
			&i.EnrollmentID,
			&i.LessonID,
			&i.State,
			&i.PositionS,
			&i.CompletedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordProgress = `-- name: RecordProgress :one
INSERT INTO lesson_progress (tenant_id, enrollment_id, lesson_id, state, position_s, completed_at)
VALUES ($1, $2, $3,
        CASE WHEN $4::boolean THEN 'completed'::progress_state ELSE 'in_progress'::progress_state END,
        $5,
        CASE WHEN $4::boolean THEN now() ELSE NULL END)
ON CONFLICT (enrollment_id, lesson_id) DO UPDATE SET
  position_s   = GREATEST(lesson_progress.position_s, excluded.position_s),
  state        = CASE WHEN lesson_progress.state = 'completed' THEN 'completed'::progress_state ELSE excluded.state END,
  completed_at = coalesce(lesson_progress.completed_at, excluded.completed_at),
  updated_at   = now()
RETURNING tenant_id, enrollment_id, lesson_id, state, position_s, completed_at, updated_at
`

type RecordProgressParams struct {
	TenantID     uuid.UUID `json:"tenant_id"`
	EnrollmentID uuid.UUID `json:"enrollment_id"`
	LessonID     uuid.UUID `json:"lesson_id"`
	Completed    bool      `json:"completed"`
	PositionS    int32     `json:"position_s"`
}

// Merge rules for offline sync: never rewind a resume point, never un-complete.
func (q *Queries) RecordProgress(ctx context.Context, arg RecordProgressParams) (LessonProgress, error) {
	row := q.db.QueryRow(ctx, recordProgress,
		arg.TenantID,
		arg.EnrollmentID,
		arg.LessonID,
		arg.Completed,
		arg.PositionS,
	)
	var i LessonProgress
	err := row.Scan(
		&i.TenantID,
		&i.EnrollmentID,
		&i.LessonID,
		&i.State,
		&i.PositionS,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}
