// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: forum.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const addPost = `-- name: AddPost :one
INSERT INTO forum_posts (tenant_id, thread_id, author_id, body, dir)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, thread_id, author_id, body, dir, removed_at, removed_by, created_at, updated_at
`

type AddPostParams struct {
	TenantID uuid.UUID     `json:"tenant_id"`
	ThreadID uuid.UUID     `json:"thread_id"`
	AuthorID uuid.NullUUID `json:"author_id"`
	Body     string        `json:"body"`
	Dir      TextDir       `json:"dir"`
}

func (q *Queries) AddPost(ctx context.Context, arg AddPostParams) (ForumPost, error) {
	row := q.db.QueryRow(ctx, addPost,
		arg.TenantID,
		arg.ThreadID,
		arg.AuthorID,
		arg.Body,
		arg.Dir,
	)
	var i ForumPost
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ThreadID,
		&i.AuthorID,
		&i.Body,
		&i.Dir,
		&i.RemovedAt,
		&i.RemovedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countReply = `-- name: CountReply :exec
UPDATE forum_threads SET reply_count = reply_count + 1, last_post_at = now() WHERE id = $1
`

// The thread carries its own count and last post, so a list of threads is one
// query rather than one per row.
func (q *Queries) CountReply(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, countReply, id)
	return err
}

const createThread = `-- name: CreateThread :one
INSERT INTO forum_threads (tenant_id, course_id, title, dir, author_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, course_id, title, dir, author_id, pinned, locked, reply_count, last_post_at, created_at, updated_at
`

type CreateThreadParams struct {
	TenantID uuid.UUID     `json:"tenant_id"`
	CourseID uuid.UUID     `json:"course_id"`
	Title    string        `json:"title"`
	Dir      TextDir       `json:"dir"`
	AuthorID uuid.NullUUID `json:"author_id"`
}

func (q *Queries) CreateThread(ctx context.Context, arg CreateThreadParams) (ForumThread, error) {
	row := q.db.QueryRow(ctx, createThread,
		arg.TenantID,
		arg.CourseID,
		arg.Title,
		arg.Dir,
		arg.AuthorID,
	)
	var i ForumThread
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CourseID,
		&i.Title,
		&i.Dir,
		&i.AuthorID,
		&i.Pinned,
		&i.Locked,
		&i.ReplyCount,
		&i.LastPostAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteThread = `-- name: DeleteThread :execrows
DELETE FROM forum_threads WHERE id = $1
`

func (q *Queries) DeleteThread(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteThread, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const editPost = `-- name: EditPost :one
UPDATE forum_posts SET body = $1 WHERE id = $2 AND removed_at IS NULL RETURNING id, tenant_id, thread_id, author_id, body, dir, removed_at, removed_by, created_at, updated_at
`

type EditPostParams struct {
	Body string    `json:"body"`
	ID   uuid.UUID `json:"id"`
}

func (q *Queries) EditPost(ctx context.Context, arg EditPostParams) (ForumPost, error) {
	row := q.db.QueryRow(ctx, editPost, arg.Body, arg.ID)
	var i ForumPost
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ThreadID,
		&i.AuthorID,
		&i.Body,
		&i.Dir,
		&i.RemovedAt,
		&i.RemovedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPost = `-- name: GetPost :one
SELECT id, tenant_id, thread_id, author_id, body, dir, removed_at, removed_by, created_at, updated_at FROM forum_posts WHERE id = $1
`

func (q *Queries) GetPost(ctx context.Context, id uuid.UUID) (ForumPost, error) {
	row := q.db.QueryRow(ctx, getPost, id)
	var i ForumPost
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ThreadID,
		&i.AuthorID,
		&i.Body,
		&i.Dir,
		&i.RemovedAt,
		&i.RemovedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getThread = `-- name: GetThread :one
SELECT t.id, t.tenant_id, t.course_id, t.title, t.dir, t.author_id, t.pinned, t.locked, t.reply_count, t.last_post_at, t.created_at, t.updated_at, u.full_name AS author_name, c.slug AS course_slug, c.title AS course_title
FROM forum_threads t
JOIN courses c ON c.id = t.course_id
LEFT JOIN users u ON u.id = t.author_id
WHERE t.id = $1
`

type GetThreadRow struct {
	ForumThread ForumThread `json:"forum_thread"`
	AuthorName  *string     `json:"author_name"`
	CourseSlug  string      `json:"course_slug"`
	CourseTitle string      `json:"course_title"`
}

func (q *Queries) GetThread(ctx context.Context, id uuid.UUID) (GetThreadRow, error) {
	row := q.db.QueryRow(ctx, getThread, id)
	var i GetThreadRow
	err := row.Scan(
		&i.ForumThread.ID,
		&i.ForumThread.TenantID,
		&i.ForumThread.CourseID,
		&i.ForumThread.Title,
		&i.ForumThread.Dir,
		&i.ForumThread.AuthorID,
		&i.ForumThread.Pinned,
		&i.ForumThread.Locked,
		&i.ForumThread.ReplyCount,
		&i.ForumThread.LastPostAt,
		&i.ForumThread.CreatedAt,
		&i.ForumThread.UpdatedAt,
		&i.AuthorName,
		&i.CourseSlug,
		&i.CourseTitle,
	)
	return i, err
}

const listPosts = `-- name: ListPosts :many
SELECT p.id, p.tenant_id, p.thread_id, p.author_id, p.body, p.dir, p.removed_at, p.removed_by, p.created_at, p.updated_at, u.full_name AS author_name
FROM forum_posts p LEFT JOIN users u ON u.id = p.author_id
WHERE p.thread_id = $1
ORDER BY p.created_at
`

type ListPostsRow struct {
	ForumPost  ForumPost `json:"forum_post"`
	AuthorName *string   `json:"author_name"`
}

func (q *Queries) ListPosts(ctx context.Context, threadID uuid.UUID) ([]ListPostsRow, error) {
	rows, err := q.db.Query(ctx, listPosts, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPostsRow{}
	for rows.Next() {
		var i ListPostsRow
		if err := rows.Scan(
			&i.ForumPost.ID,
			&i.ForumPost.TenantID,
			&i.ForumPost.ThreadID,
			&i.ForumPost.AuthorID,
			&i.ForumPost.Body,
			&i.ForumPost.Dir,
			&i.ForumPost.RemovedAt,
			&i.ForumPost.RemovedBy,
			&i.ForumPost.CreatedAt,
			&i.ForumPost.UpdatedAt,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThreads = `-- name: ListThreads :many
SELECT t.id, t.tenant_id, t.course_id, t.title, t.dir, t.author_id, t.pinned, t.locked, t.reply_count, t.last_post_at, t.created_at, t.updated_at, u.full_name AS author_name
FROM forum_threads t LEFT JOIN users u ON u.id = t.author_id
WHERE t.course_id = $1
ORDER BY t.pinned DESC, t.last_post_at DESC
LIMIT $3 OFFSET $2
`

type ListThreadsParams struct {
	CourseID   uuid.UUID `json:"course_id"`
	PageOffset int32     `json:"page_offset"`
	PageLimit  int32     `json:"page_limit"`
}

type ListThreadsRow struct {
	ForumThread ForumThread `json:"forum_thread"`
	AuthorName  *string     `json:"author_name"`
}

func (q *Queries) ListThreads(ctx context.Context, arg ListThreadsParams) ([]ListThreadsRow, error) {
	rows, err := q.db.Query(ctx, listThreads, arg.CourseID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListThreadsRow{}
	for rows.Next() {
		var i ListThreadsRow
		if err := rows.Scan(
			&i.ForumThread.ID,
			&i.ForumThread.TenantID,
			&i.ForumThread.CourseID,
			&i.ForumThread.Title,
			&i.ForumThread.Dir,
			&i.ForumThread.AuthorID,
			&i.ForumThread.Pinned,
			&i.ForumThread.Locked,
			&i.ForumThread.ReplyCount,
			&i.ForumThread.LastPostAt,
			&i.ForumThread.CreatedAt,
			&i.ForumThread.UpdatedAt,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removePost = `-- name: RemovePost :one
UPDATE forum_posts SET removed_at = now(), removed_by = $1
WHERE id = $2 AND removed_at IS NULL
RETURNING id, tenant_id, thread_id, author_id, body, dir, removed_at, removed_by, created_at, updated_at
`

type RemovePostParams struct {
	RemovedBy uuid.NullUUID `json:"removed_by"`
	ID        uuid.UUID     `json:"id"`
}

func (q *Queries) RemovePost(ctx context.Context, arg RemovePostParams) (ForumPost, error) {
	row := q.db.QueryRow(ctx, removePost, arg.RemovedBy, arg.ID)
	var i ForumPost
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ThreadID,
		&i.AuthorID,
		&i.Body,
		&i.Dir,
		&i.RemovedAt,
		&i.RemovedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setThreadFlags = `-- name: SetThreadFlags :one
UPDATE forum_threads SET
  pinned = coalesce($1, pinned),
  locked = coalesce($2, locked)
WHERE id = $3
RETURNING id, tenant_id, course_id, title, dir, author_id, pinned, locked, reply_count, last_post_at, created_at, updated_at
`

type SetThreadFlagsParams struct {
	Pinned *bool     `json:"pinned"`
	Locked *bool     `json:"locked"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) SetThreadFlags(ctx context.Context, arg SetThreadFlagsParams) (ForumThread, error) {
	row := q.db.QueryRow(ctx, setThreadFlags, arg.Pinned, arg.Locked, arg.ID)
	var i ForumThread
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CourseID,
		&i.Title,
		&i.Dir,
		&i.AuthorID,
		&i.Pinned,
		&i.Locked,
		&i.ReplyCount,
		&i.LastPostAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
