// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: gradebook.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const bestQuizScores = `-- name: BestQuizScores :many
SELECT DISTINCT ON (a.quiz_id, a.enrollment_id)
  a.quiz_id, a.enrollment_id, a.points_awarded, a.points_possible, a.graded_at
FROM quiz_attempts a
JOIN quizzes q ON q.id = a.quiz_id
JOIN lessons l ON l.id = q.lesson_id
JOIN modules m ON m.id = l.module_id
WHERE m.course_id = $1 AND a.state = 'graded'
ORDER BY a.quiz_id, a.enrollment_id, a.points_awarded DESC, a.graded_at
`

type BestQuizScoresRow struct {
	QuizID         uuid.UUID          `json:"quiz_id"`
	EnrollmentID   uuid.UUID          `json:"enrollment_id"`
	PointsAwarded  int32              `json:"points_awarded"`
	PointsPossible int32              `json:"points_possible"`
	GradedAt       pgtype.Timestamptz `json:"graded_at"`
}

// The best graded attempt per learner per quiz, which is what a grade uses.
func (q *Queries) BestQuizScores(ctx context.Context, courseID uuid.UUID) ([]BestQuizScoresRow, error) {
	rows, err := q.db.Query(ctx, bestQuizScores, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BestQuizScoresRow{}
	for rows.Next() {
		var i BestQuizScoresRow
		if err := rows.Scan(
			&i.QuizID,
			&i.EnrollmentID,
			&i.PointsAwarded,
			&i.PointsPossible,
			&i.GradedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const clearGradeOverride = `-- name: ClearGradeOverride :execrows
DELETE FROM grade_overrides WHERE grade_item_id = $1 AND enrollment_id = $2
`

type ClearGradeOverrideParams struct {
	GradeItemID  uuid.UUID `json:"grade_item_id"`
	EnrollmentID uuid.UUID `json:"enrollment_id"`
}

func (q *Queries) ClearGradeOverride(ctx context.Context, arg ClearGradeOverrideParams) (int64, error) {
	result, err := q.db.Exec(ctx, clearGradeOverride, arg.GradeItemID, arg.EnrollmentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createGradeItem = `-- name: CreateGradeItem :one
INSERT INTO grade_items (tenant_id, course_id, quiz_id, assignment_id, source, title, category, points_possible, weight, position)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9,
        coalesce((SELECT max(position) + 1024 FROM grade_items WHERE course_id = $2), 1024))
RETURNING id, tenant_id, course_id, quiz_id, source, title, category, points_possible, weight, position, created_at, updated_at, assignment_id
`

type CreateGradeItemParams struct {
	TenantID       uuid.UUID     `json:"tenant_id"`
	CourseID       uuid.UUID     `json:"course_id"`
	QuizID         uuid.NullUUID `json:"quiz_id"`
	AssignmentID   uuid.NullUUID `json:"assignment_id"`
	Source         GradeSource   `json:"source"`
	Title          string        `json:"title"`
	Category       string        `json:"category"`
	PointsPossible int32         `json:"points_possible"`
	Weight         int32         `json:"weight"`
}

func (q *Queries) CreateGradeItem(ctx context.Context, arg CreateGradeItemParams) (GradeItem, error) {
	row := q.db.QueryRow(ctx, createGradeItem,
		arg.TenantID,
		arg.CourseID,
		arg.QuizID,
		arg.AssignmentID,
		arg.Source,
		arg.Title,
		arg.Category,
		arg.PointsPossible,
		arg.Weight,
	)
	var i GradeItem
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CourseID,
		&i.QuizID,
		&i.Source,
		&i.Title,
		&i.Category,
		&i.PointsPossible,
		&i.Weight,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AssignmentID,
	)
	return i, err
}

const deleteGradeItem = `-- name: DeleteGradeItem :execrows
DELETE FROM grade_items WHERE id = $1 AND source = 'manual'
`

func (q *Queries) DeleteGradeItem(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGradeItem, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getGradeItem = `-- name: GetGradeItem :one
SELECT id, tenant_id, course_id, quiz_id, source, title, category, points_possible, weight, position, created_at, updated_at, assignment_id FROM grade_items WHERE id = $1
`

func (q *Queries) GetGradeItem(ctx context.Context, id uuid.UUID) (GradeItem, error) {
	row := q.db.QueryRow(ctx, getGradeItem, id)
	var i GradeItem
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CourseID,
		&i.QuizID,
		&i.Source,
		&i.Title,
		&i.Category,
		&i.PointsPossible,
		&i.Weight,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AssignmentID,
	)
	return i, err
}

const listCourseEnrollments = `-- name: ListCourseEnrollments :many
SELECT e.id, e.user_id, u.full_name
FROM enrollments e JOIN users u ON u.id = e.user_id
WHERE e.course_id = $1 AND e.status <> 'cancelled'
ORDER BY u.full_name
`

type ListCourseEnrollmentsRow struct {
	ID       uuid.UUID `json:"id"`
	UserID   uuid.UUID `json:"user_id"`
	FullName string    `json:"full_name"`
}

func (q *Queries) ListCourseEnrollments(ctx context.Context, courseID uuid.UUID) ([]ListCourseEnrollmentsRow, error) {
	rows, err := q.db.Query(ctx, listCourseEnrollments, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCourseEnrollmentsRow{}
	for rows.Next() {
		var i ListCourseEnrollmentsRow
		if err := rows.Scan(&i.ID, &i.UserID, &i.FullName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCourseOverrides = `-- name: ListCourseOverrides :many
SELECT o.grade_item_id, o.enrollment_id, o.tenant_id, o.points, o.note, o.set_by, o.updated_at FROM grade_overrides o JOIN grade_items i ON i.id = o.grade_item_id
WHERE i.course_id = $1
`

func (q *Queries) ListCourseOverrides(ctx context.Context, courseID uuid.UUID) ([]GradeOverride, error) {
	rows, err := q.db.Query(ctx, listCourseOverrides, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GradeOverride{}
	for rows.Next() {
		var i GradeOverride
		if err := rows.Scan(
			&i.GradeItemID,
			&i.EnrollmentID,
			&i.TenantID,
			&i.Points,
			&i.Note,
			&i.SetBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGradeItems = `-- name: ListGradeItems :many
SELECT id, tenant_id, course_id, quiz_id, source, title, category, points_possible, weight, position, created_at, updated_at, assignment_id FROM grade_items WHERE course_id = $1 ORDER BY position, created_at
`

func (q *Queries) ListGradeItems(ctx context.Context, courseID uuid.UUID) ([]GradeItem, error) {
	rows, err := q.db.Query(ctx, listGradeItems, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GradeItem{}
	for rows.Next() {
		var i GradeItem
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CourseID,
			&i.QuizID,
			&i.Source,
			&i.Title,
			&i.Category,
			&i.PointsPossible,
			&i.Weight,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AssignmentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setGradeOverride = `-- name: SetGradeOverride :one
INSERT INTO grade_overrides (tenant_id, grade_item_id, enrollment_id, points, note, set_by)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (grade_item_id, enrollment_id) DO UPDATE
SET points = excluded.points, note = excluded.note, set_by = excluded.set_by, updated_at = now()
RETURNING grade_item_id, enrollment_id, tenant_id, points, note, set_by, updated_at
`

type SetGradeOverrideParams struct {
	TenantID     uuid.UUID     `json:"tenant_id"`
	GradeItemID  uuid.UUID     `json:"grade_item_id"`
	EnrollmentID uuid.UUID     `json:"enrollment_id"`
	Points       int32         `json:"points"`
	Note         string        `json:"note"`
	SetBy        uuid.NullUUID `json:"set_by"`
}

func (q *Queries) SetGradeOverride(ctx context.Context, arg SetGradeOverrideParams) (GradeOverride, error) {
	row := q.db.QueryRow(ctx, setGradeOverride,
		arg.TenantID,
		arg.GradeItemID,
		arg.EnrollmentID,
		arg.Points,
		arg.Note,
		arg.SetBy,
	)
	var i GradeOverride
	err := row.Scan(
		&i.GradeItemID,
		&i.EnrollmentID,
		&i.TenantID,
		&i.Points,
		&i.Note,
		&i.SetBy,
		&i.UpdatedAt,
	)
	return i, err
}

const syncAssignmentItem = `-- name: SyncAssignmentItem :exec
UPDATE grade_items i
SET points_possible = (SELECT a.points FROM assignments a WHERE a.id = $1),
    title = (SELECT a.title FROM assignments a WHERE a.id = $1)
WHERE i.assignment_id = $1
`

func (q *Queries) SyncAssignmentItem(ctx context.Context, targetAssignment uuid.UUID) error {
	_, err := q.db.Exec(ctx, syncAssignmentItem, targetAssignment)
	return err
}

const syncQuizItemPoints = `-- name: SyncQuizItemPoints :exec
UPDATE grade_items i
SET points_possible = GREATEST(1, (SELECT coalesce(sum(q.points), 0)::integer FROM questions q WHERE q.quiz_id = $1))
WHERE i.quiz_id = $1
`

// A quiz item is worth whatever its questions add up to.
func (q *Queries) SyncQuizItemPoints(ctx context.Context, targetQuiz uuid.UUID) error {
	_, err := q.db.Exec(ctx, syncQuizItemPoints, targetQuiz)
	return err
}

const updateGradeItem = `-- name: UpdateGradeItem :one
UPDATE grade_items SET
  title    = coalesce($1, title),
  category = coalesce($2, category),
  weight   = coalesce($3, weight)
WHERE id = $4
RETURNING id, tenant_id, course_id, quiz_id, source, title, category, points_possible, weight, position, created_at, updated_at, assignment_id
`

type UpdateGradeItemParams struct {
	Title    *string   `json:"title"`
	Category *string   `json:"category"`
	Weight   *int32    `json:"weight"`
	ID       uuid.UUID `json:"id"`
}

func (q *Queries) UpdateGradeItem(ctx context.Context, arg UpdateGradeItemParams) (GradeItem, error) {
	row := q.db.QueryRow(ctx, updateGradeItem,
		arg.Title,
		arg.Category,
		arg.Weight,
		arg.ID,
	)
	var i GradeItem
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CourseID,
		&i.QuizID,
		&i.Source,
		&i.Title,
		&i.Category,
		&i.PointsPossible,
		&i.Weight,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AssignmentID,
	)
	return i, err
}
