// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: hifz.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteHifzEntry = `-- name: DeleteHifzEntry :execrows
DELETE FROM hifz_entries WHERE id = $1
`

func (q *Queries) DeleteHifzEntry(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteHifzEntry, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const hifzOnDate = `-- name: HifzOnDate :many
SELECT h.id, h.tenant_id, h.student_id, h.teacher_id, h.on_date, h.kind, h.from_surah, h.from_ayah, h.to_surah, h.to_ayah, h.quality, h.mistakes, h.note, h.created_at, u.full_name AS student_name
FROM hifz_entries h JOIN users u ON u.id = h.student_id
WHERE h.on_date = $1
ORDER BY u.full_name
`

type HifzOnDateRow struct {
	HifzEntry   HifzEntry `json:"hifz_entry"`
	StudentName string    `json:"student_name"`
}

func (q *Queries) HifzOnDate(ctx context.Context, onDate pgtype.Date) ([]HifzOnDateRow, error) {
	rows, err := q.db.Query(ctx, hifzOnDate, onDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HifzOnDateRow{}
	for rows.Next() {
		var i HifzOnDateRow
		if err := rows.Scan(
			&i.HifzEntry.ID,
			&i.HifzEntry.TenantID,
			&i.HifzEntry.StudentID,
			&i.HifzEntry.TeacherID,
			&i.HifzEntry.OnDate,
			&i.HifzEntry.Kind,
			&i.HifzEntry.FromSurah,
			&i.HifzEntry.FromAyah,
			&i.HifzEntry.ToSurah,
			&i.HifzEntry.ToAyah,
			&i.HifzEntry.Quality,
			&i.HifzEntry.Mistakes,
			&i.HifzEntry.Note,
			&i.HifzEntry.CreatedAt,
			&i.StudentName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hifzSummary = `-- name: HifzSummary :one
WITH taken AS (
  SELECT DISTINCT h.from_surah, h.from_ayah, h.to_surah, h.to_ayah
  FROM hifz_entries h
  WHERE h.student_id = $1 AND h.kind = 'sabaq'
)
SELECT
  coalesce(sum(
    CASE WHEN t.from_surah = t.to_surah THEN t.to_ayah - t.from_ayah + 1
    ELSE (SELECT s.ayah_count FROM surahs s WHERE s.number = t.from_surah) - t.from_ayah + 1
         + t.to_ayah
         + coalesce((SELECT sum(s.ayah_count) FROM surahs s
                     WHERE s.number > t.from_surah AND s.number < t.to_surah), 0)
    END
  ), 0)::bigint AS ayahs,
  count(*)::bigint AS lessons
FROM taken t
`

type HifzSummaryRow struct {
	Ayahs   int64 `json:"ayahs"`
	Lessons int64 `json:"lessons"`
}

// What a student has committed, counted in ayahs the way a teacher counts it:
// every ayah inside the ranges they have taken as a new lesson.
func (q *Queries) HifzSummary(ctx context.Context, studentID uuid.UUID) (HifzSummaryRow, error) {
	row := q.db.QueryRow(ctx, hifzSummary, studentID)
	var i HifzSummaryRow
	err := row.Scan(&i.Ayahs, &i.Lessons)
	return i, err
}

const isGuardianOf = `-- name: IsGuardianOf :one
SELECT EXISTS (
  SELECT 1 FROM guardianships WHERE guardian_id = $1 AND student_id = $2
) AS is_guardian
`

type IsGuardianOfParams struct {
	GuardianID uuid.UUID `json:"guardian_id"`
	StudentID  uuid.UUID `json:"student_id"`
}

func (q *Queries) IsGuardianOf(ctx context.Context, arg IsGuardianOfParams) (bool, error) {
	row := q.db.QueryRow(ctx, isGuardianOf, arg.GuardianID, arg.StudentID)
	var is_guardian bool
	err := row.Scan(&is_guardian)
	return is_guardian, err
}

const listHifzForStudent = `-- name: ListHifzForStudent :many
SELECT h.id, h.tenant_id, h.student_id, h.teacher_id, h.on_date, h.kind, h.from_surah, h.from_ayah, h.to_surah, h.to_ayah, h.quality, h.mistakes, h.note, h.created_at, s.name_en AS from_name, e.name_en AS to_name, u.full_name AS teacher_name
FROM hifz_entries h
JOIN surahs s ON s.number = h.from_surah
JOIN surahs e ON e.number = h.to_surah
LEFT JOIN users u ON u.id = h.teacher_id
WHERE h.student_id = $1
ORDER BY h.on_date DESC, h.created_at DESC
LIMIT $3 OFFSET $2
`

type ListHifzForStudentParams struct {
	StudentID  uuid.UUID `json:"student_id"`
	PageOffset int32     `json:"page_offset"`
	PageLimit  int32     `json:"page_limit"`
}

type ListHifzForStudentRow struct {
	HifzEntry   HifzEntry `json:"hifz_entry"`
	FromName    string    `json:"from_name"`
	ToName      string    `json:"to_name"`
	TeacherName *string   `json:"teacher_name"`
}

func (q *Queries) ListHifzForStudent(ctx context.Context, arg ListHifzForStudentParams) ([]ListHifzForStudentRow, error) {
	rows, err := q.db.Query(ctx, listHifzForStudent, arg.StudentID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHifzForStudentRow{}
	for rows.Next() {
		var i ListHifzForStudentRow
		if err := rows.Scan(
			&i.HifzEntry.ID,
			&i.HifzEntry.TenantID,
			&i.HifzEntry.StudentID,
			&i.HifzEntry.TeacherID,
			&i.HifzEntry.OnDate,
			&i.HifzEntry.Kind,
			&i.HifzEntry.FromSurah,
			&i.HifzEntry.FromAyah,
			&i.HifzEntry.ToSurah,
			&i.HifzEntry.ToAyah,
			&i.HifzEntry.Quality,
			&i.HifzEntry.Mistakes,
			&i.HifzEntry.Note,
			&i.HifzEntry.CreatedAt,
			&i.FromName,
			&i.ToName,
			&i.TeacherName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSurahs = `-- name: ListSurahs :many
SELECT number, name_ar, name_en, ayah_count FROM surahs ORDER BY number
`

func (q *Queries) ListSurahs(ctx context.Context) ([]Surah, error) {
	rows, err := q.db.Query(ctx, listSurahs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Surah{}
	for rows.Next() {
		var i Surah
		if err := rows.Scan(
			&i.Number,
			&i.NameAr,
			&i.NameEn,
			&i.AyahCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordHifz = `-- name: RecordHifz :one
INSERT INTO hifz_entries (tenant_id, student_id, teacher_id, on_date, kind,
                          from_surah, from_ayah, to_surah, to_ayah, quality, mistakes, note)
VALUES ($1, $2, $3, $4, $5,
        $6, $7, $8, $9, $10, $11, $12)
RETURNING id, tenant_id, student_id, teacher_id, on_date, kind, from_surah, from_ayah, to_surah, to_ayah, quality, mistakes, note, created_at
`

type RecordHifzParams struct {
	TenantID  uuid.UUID     `json:"tenant_id"`
	StudentID uuid.UUID     `json:"student_id"`
	TeacherID uuid.NullUUID `json:"teacher_id"`
	OnDate    pgtype.Date   `json:"on_date"`
	Kind      HifzKind      `json:"kind"`
	FromSurah int16         `json:"from_surah"`
	FromAyah  int16         `json:"from_ayah"`
	ToSurah   int16         `json:"to_surah"`
	ToAyah    int16         `json:"to_ayah"`
	Quality   HifzQuality   `json:"quality"`
	Mistakes  int16         `json:"mistakes"`
	Note      string        `json:"note"`
}

func (q *Queries) RecordHifz(ctx context.Context, arg RecordHifzParams) (HifzEntry, error) {
	row := q.db.QueryRow(ctx, recordHifz,
		arg.TenantID,
		arg.StudentID,
		arg.TeacherID,
		arg.OnDate,
		arg.Kind,
		arg.FromSurah,
		arg.FromAyah,
		arg.ToSurah,
		arg.ToAyah,
		arg.Quality,
		arg.Mistakes,
		arg.Note,
	)
	var i HifzEntry
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.StudentID,
		&i.TeacherID,
		&i.OnDate,
		&i.Kind,
		&i.FromSurah,
		&i.FromAyah,
		&i.ToSurah,
		&i.ToAyah,
		&i.Quality,
		&i.Mistakes,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const surahAyahCount = `-- name: SurahAyahCount :one
SELECT ayah_count FROM surahs WHERE number = $1
`

func (q *Queries) SurahAyahCount(ctx context.Context, number int16) (int16, error) {
	row := q.db.QueryRow(ctx, surahAyahCount, number)
	var ayah_count int16
	err := row.Scan(&ayah_count)
	return ayah_count, err
}
