// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const attachMediaToLesson = `-- name: AttachMediaToLesson :one
UPDATE lessons SET media_id = $1 WHERE id = $2 RETURNING id, tenant_id, module_id, title, kind, body, dir, duration_s, is_preview, status, position, created_at, updated_at, media_id
`

type AttachMediaToLessonParams struct {
	MediaID uuid.NullUUID `json:"media_id"`
	ID      uuid.UUID     `json:"id"`
}

func (q *Queries) AttachMediaToLesson(ctx context.Context, arg AttachMediaToLessonParams) (Lesson, error) {
	row := q.db.QueryRow(ctx, attachMediaToLesson, arg.MediaID, arg.ID)
	var i Lesson
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ModuleID,
		&i.Title,
		&i.Kind,
		&i.Body,
		&i.Dir,
		&i.DurationS,
		&i.IsPreview,
		&i.Status,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MediaID,
	)
	return i, err
}

const createMediaAsset = `-- name: CreateMediaAsset :one
INSERT INTO media_assets (tenant_id, provider, external_ref, state, kind, title, duration_s, content_type, metadata, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, tenant_id, provider, external_ref, state, kind, title, duration_s, byte_size, content_type, error, metadata, created_by, created_at, updated_at
`

type CreateMediaAssetParams struct {
	TenantID    uuid.UUID     `json:"tenant_id"`
	Provider    string        `json:"provider"`
	ExternalRef string        `json:"external_ref"`
	State       MediaState    `json:"state"`
	Kind        LessonKind    `json:"kind"`
	Title       string        `json:"title"`
	DurationS   int32         `json:"duration_s"`
	ContentType string        `json:"content_type"`
	Metadata    []byte        `json:"metadata"`
	CreatedBy   uuid.NullUUID `json:"created_by"`
}

func (q *Queries) CreateMediaAsset(ctx context.Context, arg CreateMediaAssetParams) (MediaAsset, error) {
	row := q.db.QueryRow(ctx, createMediaAsset,
		arg.TenantID,
		arg.Provider,
		arg.ExternalRef,
		arg.State,
		arg.Kind,
		arg.Title,
		arg.DurationS,
		arg.ContentType,
		arg.Metadata,
		arg.CreatedBy,
	)
	var i MediaAsset
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Provider,
		&i.ExternalRef,
		&i.State,
		&i.Kind,
		&i.Title,
		&i.DurationS,
		&i.ByteSize,
		&i.ContentType,
		&i.Error,
		&i.Metadata,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMediaAsset = `-- name: GetMediaAsset :one
SELECT id, tenant_id, provider, external_ref, state, kind, title, duration_s, byte_size, content_type, error, metadata, created_by, created_at, updated_at FROM media_assets WHERE id = $1
`

func (q *Queries) GetMediaAsset(ctx context.Context, id uuid.UUID) (MediaAsset, error) {
	row := q.db.QueryRow(ctx, getMediaAsset, id)
	var i MediaAsset
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Provider,
		&i.ExternalRef,
		&i.State,
		&i.Kind,
		&i.Title,
		&i.DurationS,
		&i.ByteSize,
		&i.ContentType,
		&i.Error,
		&i.Metadata,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const mediaUsage = `-- name: MediaUsage :many
SELECT tenant_id, day, requests, bytes FROM media_delivery WHERE day >= current_date - $1::integer ORDER BY day DESC
`

func (q *Queries) MediaUsage(ctx context.Context, days int32) ([]MediaDelivery, error) {
	rows, err := q.db.Query(ctx, mediaUsage, days)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaDelivery{}
	for rows.Next() {
		var i MediaDelivery
		if err := rows.Scan(
			&i.TenantID,
			&i.Day,
			&i.Requests,
			&i.Bytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordMediaDelivery = `-- name: RecordMediaDelivery :exec
INSERT INTO media_delivery (tenant_id, day, requests, bytes)
VALUES ($1, current_date, 1, $2)
ON CONFLICT (tenant_id, day) DO UPDATE
SET requests = media_delivery.requests + 1, bytes = media_delivery.bytes + excluded.bytes
`

type RecordMediaDeliveryParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Bytes    int64     `json:"bytes"`
}

func (q *Queries) RecordMediaDelivery(ctx context.Context, arg RecordMediaDeliveryParams) error {
	_, err := q.db.Exec(ctx, recordMediaDelivery, arg.TenantID, arg.Bytes)
	return err
}

const updateMediaState = `-- name: UpdateMediaState :one
UPDATE media_assets SET
  state        = $1,
  duration_s   = coalesce($2, duration_s),
  byte_size    = coalesce($3, byte_size),
  content_type = coalesce($4, content_type),
  error        = coalesce($5, error),
  metadata     = coalesce($6, metadata)
WHERE id = $7
RETURNING id, tenant_id, provider, external_ref, state, kind, title, duration_s, byte_size, content_type, error, metadata, created_by, created_at, updated_at
`

type UpdateMediaStateParams struct {
	State       MediaState `json:"state"`
	DurationS   *int32     `json:"duration_s"`
	ByteSize    *int64     `json:"byte_size"`
	ContentType *string    `json:"content_type"`
	Error       *string    `json:"error"`
	Metadata    []byte     `json:"metadata"`
	ID          uuid.UUID  `json:"id"`
}

func (q *Queries) UpdateMediaState(ctx context.Context, arg UpdateMediaStateParams) (MediaAsset, error) {
	row := q.db.QueryRow(ctx, updateMediaState,
		arg.State,
		arg.DurationS,
		arg.ByteSize,
		arg.ContentType,
		arg.Error,
		arg.Metadata,
		arg.ID,
	)
	var i MediaAsset
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Provider,
		&i.ExternalRef,
		&i.State,
		&i.Kind,
		&i.Title,
		&i.DurationS,
		&i.ByteSize,
		&i.ContentType,
		&i.Error,
		&i.Metadata,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
