// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: memberships.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countOwners = `-- name: CountOwners :one
SELECT count(*) FROM memberships WHERE role = 'owner' AND status = 'active'
`

func (q *Queries) CountOwners(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOwners)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTenantMembers = `-- name: CountTenantMembers :one
SELECT count(*) FROM memberships WHERE status = 'active'
`

func (q *Queries) CountTenantMembers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTenantMembers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMembership = `-- name: CreateMembership :one
INSERT INTO memberships (tenant_id, user_id, role)
VALUES ($1, $2, $3)
RETURNING id, tenant_id, user_id, role, status, created_at, updated_at
`

type CreateMembershipParams struct {
	TenantID uuid.UUID  `json:"tenant_id"`
	UserID   uuid.UUID  `json:"user_id"`
	Role     MemberRole `json:"role"`
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, createMembership, arg.TenantID, arg.UserID, arg.Role)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMembership = `-- name: DeleteMembership :execrows
DELETE FROM memberships WHERE tenant_id = $1 AND user_id = $2
`

type DeleteMembershipParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	UserID   uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteMembership(ctx context.Context, arg DeleteMembershipParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMembership, arg.TenantID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMembership = `-- name: GetMembership :one
SELECT id, tenant_id, user_id, role, status, created_at, updated_at FROM memberships WHERE tenant_id = $1 AND user_id = $2
`

type GetMembershipParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	UserID   uuid.UUID `json:"user_id"`
}

func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, getMembership, arg.TenantID, arg.UserID)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTenantMembers = `-- name: ListTenantMembers :many
SELECT m.id, m.tenant_id, m.user_id, m.role, m.status, m.created_at, m.updated_at, u.full_name, u.phone, u.email
FROM memberships m JOIN users u ON u.id = m.user_id
WHERE m.status = 'active'
ORDER BY u.full_name
LIMIT $2 OFFSET $1
`

type ListTenantMembersParams struct {
	PageOffset int32 `json:"page_offset"`
	PageLimit  int32 `json:"page_limit"`
}

type ListTenantMembersRow struct {
	ID        uuid.UUID          `json:"id"`
	TenantID  uuid.UUID          `json:"tenant_id"`
	UserID    uuid.UUID          `json:"user_id"`
	Role      MemberRole         `json:"role"`
	Status    MemberStatus       `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	FullName  string             `json:"full_name"`
	Phone     *string            `json:"phone"`
	Email     *string            `json:"email"`
}

func (q *Queries) ListTenantMembers(ctx context.Context, arg ListTenantMembersParams) ([]ListTenantMembersRow, error) {
	rows, err := q.db.Query(ctx, listTenantMembers, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTenantMembersRow{}
	for rows.Next() {
		var i ListTenantMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.Role,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FullName,
			&i.Phone,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setMembershipRole = `-- name: SetMembershipRole :one
UPDATE memberships SET role = $1
WHERE tenant_id = $2 AND user_id = $3
RETURNING id, tenant_id, user_id, role, status, created_at, updated_at
`

type SetMembershipRoleParams struct {
	Role     MemberRole `json:"role"`
	TenantID uuid.UUID  `json:"tenant_id"`
	UserID   uuid.UUID  `json:"user_id"`
}

func (q *Queries) SetMembershipRole(ctx context.Context, arg SetMembershipRoleParams) (Membership, error) {
	row := q.db.QueryRow(ctx, setMembershipRole, arg.Role, arg.TenantID, arg.UserID)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
