// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql/driver"
	"fmt"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AttemptState string

const (
	AttemptStateInProgress AttemptState = "in_progress"
	AttemptStateSubmitted  AttemptState = "submitted"
	AttemptStateGraded     AttemptState = "graded"
	AttemptStateExpired    AttemptState = "expired"
)

func (e *AttemptState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AttemptState(s)
	case string:
		*e = AttemptState(s)
	default:
		return fmt.Errorf("unsupported scan type for AttemptState: %T", src)
	}
	return nil
}

type NullAttemptState struct {
	AttemptState AttemptState `json:"attempt_state"`
	Valid        bool         `json:"valid"` // Valid is true if AttemptState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAttemptState) Scan(value interface{}) error {
	if value == nil {
		ns.AttemptState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AttemptState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAttemptState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AttemptState), nil
}

type AttendanceStatus string

const (
	AttendanceStatusPresent AttendanceStatus = "present"
	AttendanceStatusLate    AttendanceStatus = "late"
	AttendanceStatusAbsent  AttendanceStatus = "absent"
	AttendanceStatusExcused AttendanceStatus = "excused"
)

func (e *AttendanceStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AttendanceStatus(s)
	case string:
		*e = AttendanceStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AttendanceStatus: %T", src)
	}
	return nil
}

type NullAttendanceStatus struct {
	AttendanceStatus AttendanceStatus `json:"attendance_status"`
	Valid            bool             `json:"valid"` // Valid is true if AttendanceStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAttendanceStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AttendanceStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AttendanceStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAttendanceStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AttendanceStatus), nil
}

type CourseVisibility string

const (
	CourseVisibilityPrivate  CourseVisibility = "private"
	CourseVisibilityUnlisted CourseVisibility = "unlisted"
	CourseVisibilityPublic   CourseVisibility = "public"
)

func (e *CourseVisibility) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CourseVisibility(s)
	case string:
		*e = CourseVisibility(s)
	default:
		return fmt.Errorf("unsupported scan type for CourseVisibility: %T", src)
	}
	return nil
}

type NullCourseVisibility struct {
	CourseVisibility CourseVisibility `json:"course_visibility"`
	Valid            bool             `json:"valid"` // Valid is true if CourseVisibility is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCourseVisibility) Scan(value interface{}) error {
	if value == nil {
		ns.CourseVisibility, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CourseVisibility.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCourseVisibility) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CourseVisibility), nil
}

type DeliveryState string

const (
	DeliveryStateQueued  DeliveryState = "queued"
	DeliveryStateSent    DeliveryState = "sent"
	DeliveryStateFailed  DeliveryState = "failed"
	DeliveryStateSkipped DeliveryState = "skipped"
)

func (e *DeliveryState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DeliveryState(s)
	case string:
		*e = DeliveryState(s)
	default:
		return fmt.Errorf("unsupported scan type for DeliveryState: %T", src)
	}
	return nil
}

type NullDeliveryState struct {
	DeliveryState DeliveryState `json:"delivery_state"`
	Valid         bool          `json:"valid"` // Valid is true if DeliveryState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDeliveryState) Scan(value interface{}) error {
	if value == nil {
		ns.DeliveryState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DeliveryState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDeliveryState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DeliveryState), nil
}

type DiscountKind string

const (
	DiscountKindPercent DiscountKind = "percent"
	DiscountKindAmount  DiscountKind = "amount"
)

func (e *DiscountKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DiscountKind(s)
	case string:
		*e = DiscountKind(s)
	default:
		return fmt.Errorf("unsupported scan type for DiscountKind: %T", src)
	}
	return nil
}

type NullDiscountKind struct {
	DiscountKind DiscountKind `json:"discount_kind"`
	Valid        bool         `json:"valid"` // Valid is true if DiscountKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDiscountKind) Scan(value interface{}) error {
	if value == nil {
		ns.DiscountKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DiscountKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDiscountKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DiscountKind), nil
}

type EnrollmentSource string

const (
	EnrollmentSourceSelf     EnrollmentSource = "self"
	EnrollmentSourceStaff    EnrollmentSource = "staff"
	EnrollmentSourcePurchase EnrollmentSource = "purchase"
	EnrollmentSourceImport   EnrollmentSource = "import"
)

func (e *EnrollmentSource) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EnrollmentSource(s)
	case string:
		*e = EnrollmentSource(s)
	default:
		return fmt.Errorf("unsupported scan type for EnrollmentSource: %T", src)
	}
	return nil
}

type NullEnrollmentSource struct {
	EnrollmentSource EnrollmentSource `json:"enrollment_source"`
	Valid            bool             `json:"valid"` // Valid is true if EnrollmentSource is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEnrollmentSource) Scan(value interface{}) error {
	if value == nil {
		ns.EnrollmentSource, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EnrollmentSource.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEnrollmentSource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EnrollmentSource), nil
}

type EnrollmentStatus string

const (
	EnrollmentStatusActive    EnrollmentStatus = "active"
	EnrollmentStatusCompleted EnrollmentStatus = "completed"
	EnrollmentStatusCancelled EnrollmentStatus = "cancelled"
)

func (e *EnrollmentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EnrollmentStatus(s)
	case string:
		*e = EnrollmentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for EnrollmentStatus: %T", src)
	}
	return nil
}

type NullEnrollmentStatus struct {
	EnrollmentStatus EnrollmentStatus `json:"enrollment_status"`
	Valid            bool             `json:"valid"` // Valid is true if EnrollmentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEnrollmentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.EnrollmentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EnrollmentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEnrollmentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EnrollmentStatus), nil
}

type GradeSource string

const (
	GradeSourceQuiz       GradeSource = "quiz"
	GradeSourceManual     GradeSource = "manual"
	GradeSourceAssignment GradeSource = "assignment"
)

func (e *GradeSource) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GradeSource(s)
	case string:
		*e = GradeSource(s)
	default:
		return fmt.Errorf("unsupported scan type for GradeSource: %T", src)
	}
	return nil
}

type NullGradeSource struct {
	GradeSource GradeSource `json:"grade_source"`
	Valid       bool        `json:"valid"` // Valid is true if GradeSource is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGradeSource) Scan(value interface{}) error {
	if value == nil {
		ns.GradeSource, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GradeSource.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGradeSource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GradeSource), nil
}

type LessonKind string

const (
	LessonKindVideo      LessonKind = "video"
	LessonKindAudio      LessonKind = "audio"
	LessonKindText       LessonKind = "text"
	LessonKindPdf        LessonKind = "pdf"
	LessonKindLink       LessonKind = "link"
	LessonKindLive       LessonKind = "live"
	LessonKindQuiz       LessonKind = "quiz"
	LessonKindAssignment LessonKind = "assignment"
)

func (e *LessonKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LessonKind(s)
	case string:
		*e = LessonKind(s)
	default:
		return fmt.Errorf("unsupported scan type for LessonKind: %T", src)
	}
	return nil
}

type NullLessonKind struct {
	LessonKind LessonKind `json:"lesson_kind"`
	Valid      bool       `json:"valid"` // Valid is true if LessonKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLessonKind) Scan(value interface{}) error {
	if value == nil {
		ns.LessonKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LessonKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLessonKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LessonKind), nil
}

type MediaState string

const (
	MediaStatePending    MediaState = "pending"
	MediaStateProcessing MediaState = "processing"
	MediaStateReady      MediaState = "ready"
	MediaStateFailed     MediaState = "failed"
)

func (e *MediaState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MediaState(s)
	case string:
		*e = MediaState(s)
	default:
		return fmt.Errorf("unsupported scan type for MediaState: %T", src)
	}
	return nil
}

type NullMediaState struct {
	MediaState MediaState `json:"media_state"`
	Valid      bool       `json:"valid"` // Valid is true if MediaState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMediaState) Scan(value interface{}) error {
	if value == nil {
		ns.MediaState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MediaState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMediaState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MediaState), nil
}

type MemberRole string

const (
	MemberRoleOwner      MemberRole = "owner"
	MemberRoleAdmin      MemberRole = "admin"
	MemberRoleInstructor MemberRole = "instructor"
	MemberRoleAssistant  MemberRole = "assistant"
	MemberRoleStudent    MemberRole = "student"
	MemberRoleParent     MemberRole = "parent"
)

func (e *MemberRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MemberRole(s)
	case string:
		*e = MemberRole(s)
	default:
		return fmt.Errorf("unsupported scan type for MemberRole: %T", src)
	}
	return nil
}

type NullMemberRole struct {
	MemberRole MemberRole `json:"member_role"`
	Valid      bool       `json:"valid"` // Valid is true if MemberRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMemberRole) Scan(value interface{}) error {
	if value == nil {
		ns.MemberRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MemberRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMemberRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MemberRole), nil
}

type MemberStatus string

const (
	MemberStatusInvited   MemberStatus = "invited"
	MemberStatusActive    MemberStatus = "active"
	MemberStatusSuspended MemberStatus = "suspended"
)

func (e *MemberStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MemberStatus(s)
	case string:
		*e = MemberStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for MemberStatus: %T", src)
	}
	return nil
}

type NullMemberStatus struct {
	MemberStatus MemberStatus `json:"member_status"`
	Valid        bool         `json:"valid"` // Valid is true if MemberStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMemberStatus) Scan(value interface{}) error {
	if value == nil {
		ns.MemberStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MemberStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMemberStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MemberStatus), nil
}

type OrderStatus string

const (
	OrderStatusPending        OrderStatus = "pending"
	OrderStatusAwaitingReview OrderStatus = "awaiting_review"
	OrderStatusPaid           OrderStatus = "paid"
	OrderStatusRejected       OrderStatus = "rejected"
	OrderStatusCancelled      OrderStatus = "cancelled"
	OrderStatusRefunded       OrderStatus = "refunded"
)

func (e *OrderStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrderStatus(s)
	case string:
		*e = OrderStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OrderStatus: %T", src)
	}
	return nil
}

type NullOrderStatus struct {
	OrderStatus OrderStatus `json:"order_status"`
	Valid       bool        `json:"valid"` // Valid is true if OrderStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrderStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OrderStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrderStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrderStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrderStatus), nil
}

type OtpPurpose string

const (
	OtpPurposeLogin         OtpPurpose = "login"
	OtpPurposeVerifyContact OtpPurpose = "verify_contact"
)

func (e *OtpPurpose) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OtpPurpose(s)
	case string:
		*e = OtpPurpose(s)
	default:
		return fmt.Errorf("unsupported scan type for OtpPurpose: %T", src)
	}
	return nil
}

type NullOtpPurpose struct {
	OtpPurpose OtpPurpose `json:"otp_purpose"`
	Valid      bool       `json:"valid"` // Valid is true if OtpPurpose is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOtpPurpose) Scan(value interface{}) error {
	if value == nil {
		ns.OtpPurpose, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OtpPurpose.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOtpPurpose) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OtpPurpose), nil
}

type ProgressState string

const (
	ProgressStateNotStarted ProgressState = "not_started"
	ProgressStateInProgress ProgressState = "in_progress"
	ProgressStateCompleted  ProgressState = "completed"
)

func (e *ProgressState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProgressState(s)
	case string:
		*e = ProgressState(s)
	default:
		return fmt.Errorf("unsupported scan type for ProgressState: %T", src)
	}
	return nil
}

type NullProgressState struct {
	ProgressState ProgressState `json:"progress_state"`
	Valid         bool          `json:"valid"` // Valid is true if ProgressState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProgressState) Scan(value interface{}) error {
	if value == nil {
		ns.ProgressState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProgressState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProgressState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProgressState), nil
}

type PublishStatus string

const (
	PublishStatusDraft     PublishStatus = "draft"
	PublishStatusPublished PublishStatus = "published"
	PublishStatusArchived  PublishStatus = "archived"
)

func (e *PublishStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PublishStatus(s)
	case string:
		*e = PublishStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PublishStatus: %T", src)
	}
	return nil
}

type NullPublishStatus struct {
	PublishStatus PublishStatus `json:"publish_status"`
	Valid         bool          `json:"valid"` // Valid is true if PublishStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPublishStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PublishStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PublishStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPublishStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PublishStatus), nil
}

type QuestionKind string

const (
	QuestionKindMcqSingle   QuestionKind = "mcq_single"
	QuestionKindMcqMulti    QuestionKind = "mcq_multi"
	QuestionKindTrueFalse   QuestionKind = "true_false"
	QuestionKindShortAnswer QuestionKind = "short_answer"
	QuestionKindEssay       QuestionKind = "essay"
)

func (e *QuestionKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = QuestionKind(s)
	case string:
		*e = QuestionKind(s)
	default:
		return fmt.Errorf("unsupported scan type for QuestionKind: %T", src)
	}
	return nil
}

type NullQuestionKind struct {
	QuestionKind QuestionKind `json:"question_kind"`
	Valid        bool         `json:"valid"` // Valid is true if QuestionKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullQuestionKind) Scan(value interface{}) error {
	if value == nil {
		ns.QuestionKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.QuestionKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullQuestionKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.QuestionKind), nil
}

type SubmissionState string

const (
	SubmissionStateDraft     SubmissionState = "draft"
	SubmissionStateSubmitted SubmissionState = "submitted"
	SubmissionStateReturned  SubmissionState = "returned"
)

func (e *SubmissionState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SubmissionState(s)
	case string:
		*e = SubmissionState(s)
	default:
		return fmt.Errorf("unsupported scan type for SubmissionState: %T", src)
	}
	return nil
}

type NullSubmissionState struct {
	SubmissionState SubmissionState `json:"submission_state"`
	Valid           bool            `json:"valid"` // Valid is true if SubmissionState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSubmissionState) Scan(value interface{}) error {
	if value == nil {
		ns.SubmissionState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SubmissionState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSubmissionState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SubmissionState), nil
}

type TenantKind string

const (
	TenantKindInstitution TenantKind = "institution"
	TenantKindCreator     TenantKind = "creator"
	TenantKindCorporate   TenantKind = "corporate"
)

func (e *TenantKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TenantKind(s)
	case string:
		*e = TenantKind(s)
	default:
		return fmt.Errorf("unsupported scan type for TenantKind: %T", src)
	}
	return nil
}

type NullTenantKind struct {
	TenantKind TenantKind `json:"tenant_kind"`
	Valid      bool       `json:"valid"` // Valid is true if TenantKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTenantKind) Scan(value interface{}) error {
	if value == nil {
		ns.TenantKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TenantKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTenantKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TenantKind), nil
}

type TenantStatus string

const (
	TenantStatusActive    TenantStatus = "active"
	TenantStatusSuspended TenantStatus = "suspended"
)

func (e *TenantStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TenantStatus(s)
	case string:
		*e = TenantStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TenantStatus: %T", src)
	}
	return nil
}

type NullTenantStatus struct {
	TenantStatus TenantStatus `json:"tenant_status"`
	Valid        bool         `json:"valid"` // Valid is true if TenantStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTenantStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TenantStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TenantStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTenantStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TenantStatus), nil
}

type TextDir string

const (
	TextDirAuto TextDir = "auto"
	TextDirLtr  TextDir = "ltr"
	TextDirRtl  TextDir = "rtl"
)

func (e *TextDir) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TextDir(s)
	case string:
		*e = TextDir(s)
	default:
		return fmt.Errorf("unsupported scan type for TextDir: %T", src)
	}
	return nil
}

type NullTextDir struct {
	TextDir TextDir `json:"text_dir"`
	Valid   bool    `json:"valid"` // Valid is true if TextDir is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTextDir) Scan(value interface{}) error {
	if value == nil {
		ns.TextDir, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TextDir.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTextDir) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TextDir), nil
}

type Assignment struct {
	ID           uuid.UUID          `json:"id"`
	TenantID     uuid.UUID          `json:"tenant_id"`
	LessonID     uuid.UUID          `json:"lesson_id"`
	Title        string             `json:"title"`
	Instructions string             `json:"instructions"`
	Dir          TextDir            `json:"dir"`
	Points       int32              `json:"points"`
	DueAt        pgtype.Timestamptz `json:"due_at"`
	AllowLate    bool               `json:"allow_late"`
	LatePenalty  int16              `json:"late_penalty"`
	MaxFiles     int16              `json:"max_files"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type AttemptAnswer struct {
	AttemptID     uuid.UUID          `json:"attempt_id"`
	QuestionID    uuid.UUID          `json:"question_id"`
	TenantID      uuid.UUID          `json:"tenant_id"`
	OptionIds     []uuid.UUID        `json:"option_ids"`
	TextAnswer    string             `json:"text_answer"`
	PointsAwarded *int32             `json:"points_awarded"`
	NeedsGrading  bool               `json:"needs_grading"`
	Feedback      string             `json:"feedback"`
	GradedBy      uuid.NullUUID      `json:"graded_by"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type AttemptQuestion struct {
	AttemptID  uuid.UUID `json:"attempt_id"`
	QuestionID uuid.UUID `json:"question_id"`
	TenantID   uuid.UUID `json:"tenant_id"`
	Position   int32     `json:"position"`
}

type Attendance struct {
	SessionID    uuid.UUID          `json:"session_id"`
	EnrollmentID uuid.UUID          `json:"enrollment_id"`
	TenantID     uuid.UUID          `json:"tenant_id"`
	Status       AttendanceStatus   `json:"status"`
	Note         string             `json:"note"`
	MarkedBy     uuid.NullUUID      `json:"marked_by"`
	MarkedAt     pgtype.Timestamptz `json:"marked_at"`
}

type Certificate struct {
	ID            uuid.UUID          `json:"id"`
	TenantID      uuid.UUID          `json:"tenant_id"`
	CourseID      uuid.UUID          `json:"course_id"`
	EnrollmentID  uuid.UUID          `json:"enrollment_id"`
	UserID        uuid.UUID          `json:"user_id"`
	Serial        string             `json:"serial"`
	RecipientName string             `json:"recipient_name"`
	CourseTitle   string             `json:"course_title"`
	IssuerName    string             `json:"issuer_name"`
	GradePercent  *int16             `json:"grade_percent"`
	IssuedAt      pgtype.Timestamptz `json:"issued_at"`
	RevokedAt     pgtype.Timestamptz `json:"revoked_at"`
	RevokedReason string             `json:"revoked_reason"`
	IssuedBy      uuid.NullUUID      `json:"issued_by"`
}

type CertificateVerification struct {
	Serial        string             `json:"serial"`
	RecipientName string             `json:"recipient_name"`
	CourseTitle   string             `json:"course_title"`
	IssuerName    string             `json:"issuer_name"`
	GradePercent  *int16             `json:"grade_percent"`
	IssuedAt      pgtype.Timestamptz `json:"issued_at"`
	RevokedAt     pgtype.Timestamptz `json:"revoked_at"`
	TenantDir     TextDir            `json:"tenant_dir"`
}

type ClassSession struct {
	ID               uuid.UUID          `json:"id"`
	TenantID         uuid.UUID          `json:"tenant_id"`
	CourseID         uuid.UUID          `json:"course_id"`
	Title            string             `json:"title"`
	Location         string             `json:"location"`
	StartsAt         pgtype.Timestamptz `json:"starts_at"`
	EndsAt           pgtype.Timestamptz `json:"ends_at"`
	CreatedBy        uuid.NullUUID      `json:"created_by"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	Provider         string             `json:"provider"`
	JoinUrl          string             `json:"join_url"`
	HostUrl          string             `json:"host_url"`
	RecordingMediaID uuid.NullUUID      `json:"recording_media_id"`
}

type Coupon struct {
	ID             uuid.UUID          `json:"id"`
	TenantID       uuid.UUID          `json:"tenant_id"`
	Code           string             `json:"code"`
	Kind           DiscountKind       `json:"kind"`
	Value          int64              `json:"value"`
	CourseID       uuid.NullUUID      `json:"course_id"`
	MaxRedemptions *int32             `json:"max_redemptions"`
	Redeemed       int32              `json:"redeemed"`
	StartsAt       pgtype.Timestamptz `json:"starts_at"`
	EndsAt         pgtype.Timestamptz `json:"ends_at"`
	Active         bool               `json:"active"`
	CreatedBy      uuid.NullUUID      `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Course struct {
	ID                 uuid.UUID          `json:"id"`
	TenantID           uuid.UUID          `json:"tenant_id"`
	Slug               string             `json:"slug"`
	Title              string             `json:"title"`
	Summary            string             `json:"summary"`
	Dir                TextDir            `json:"dir"`
	Status             PublishStatus      `json:"status"`
	Visibility         CourseVisibility   `json:"visibility"`
	PriceMinor         int64              `json:"price_minor"`
	Currency           string             `json:"currency"`
	CreatedBy          uuid.NullUUID      `json:"created_by"`
	PublishedAt        pgtype.Timestamptz `json:"published_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	Installments       int16              `json:"installments"`
	InstallmentGapDays int16              `json:"installment_gap_days"`
}

type Enrollment struct {
	ID          uuid.UUID          `json:"id"`
	TenantID    uuid.UUID          `json:"tenant_id"`
	CourseID    uuid.UUID          `json:"course_id"`
	UserID      uuid.UUID          `json:"user_id"`
	Status      EnrollmentStatus   `json:"status"`
	Source      EnrollmentSource   `json:"source"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type GradeItem struct {
	ID             uuid.UUID          `json:"id"`
	TenantID       uuid.UUID          `json:"tenant_id"`
	CourseID       uuid.UUID          `json:"course_id"`
	QuizID         uuid.NullUUID      `json:"quiz_id"`
	Source         GradeSource        `json:"source"`
	Title          string             `json:"title"`
	Category       string             `json:"category"`
	PointsPossible int32              `json:"points_possible"`
	Weight         int32              `json:"weight"`
	Position       float64            `json:"position"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	AssignmentID   uuid.NullUUID      `json:"assignment_id"`
}

type GradeOverride struct {
	GradeItemID  uuid.UUID          `json:"grade_item_id"`
	EnrollmentID uuid.UUID          `json:"enrollment_id"`
	TenantID     uuid.UUID          `json:"tenant_id"`
	Points       int32              `json:"points"`
	Note         string             `json:"note"`
	SetBy        uuid.NullUUID      `json:"set_by"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Guardianship struct {
	TenantID   uuid.UUID          `json:"tenant_id"`
	GuardianID uuid.UUID          `json:"guardian_id"`
	StudentID  uuid.UUID          `json:"student_id"`
	Relation   string             `json:"relation"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Lesson struct {
	ID        uuid.UUID          `json:"id"`
	TenantID  uuid.UUID          `json:"tenant_id"`
	ModuleID  uuid.UUID          `json:"module_id"`
	Title     string             `json:"title"`
	Kind      LessonKind         `json:"kind"`
	Body      string             `json:"body"`
	Dir       TextDir            `json:"dir"`
	DurationS int32              `json:"duration_s"`
	IsPreview bool               `json:"is_preview"`
	Status    PublishStatus      `json:"status"`
	Position  float64            `json:"position"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	MediaID   uuid.NullUUID      `json:"media_id"`
}

type LessonProgress struct {
	TenantID     uuid.UUID          `json:"tenant_id"`
	EnrollmentID uuid.UUID          `json:"enrollment_id"`
	LessonID     uuid.UUID          `json:"lesson_id"`
	State        ProgressState      `json:"state"`
	PositionS    int32              `json:"position_s"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type LiveSession struct {
	SessionID uuid.UUID          `json:"session_id"`
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash []byte             `json:"token_hash"`
	FullName  string             `json:"full_name"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type MediaAsset struct {
	ID          uuid.UUID          `json:"id"`
	TenantID    uuid.UUID          `json:"tenant_id"`
	Provider    string             `json:"provider"`
	ExternalRef string             `json:"external_ref"`
	State       MediaState         `json:"state"`
	Kind        LessonKind         `json:"kind"`
	Title       string             `json:"title"`
	DurationS   int32              `json:"duration_s"`
	ByteSize    int64              `json:"byte_size"`
	ContentType string             `json:"content_type"`
	Error       string             `json:"error"`
	Metadata    []byte             `json:"metadata"`
	CreatedBy   uuid.NullUUID      `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type MediaDelivery struct {
	TenantID uuid.UUID   `json:"tenant_id"`
	Day      pgtype.Date `json:"day"`
	Requests int64       `json:"requests"`
	Bytes    int64       `json:"bytes"`
}

type Membership struct {
	ID        uuid.UUID          `json:"id"`
	TenantID  uuid.UUID          `json:"tenant_id"`
	UserID    uuid.UUID          `json:"user_id"`
	Role      MemberRole         `json:"role"`
	Status    MemberStatus       `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Module struct {
	ID        uuid.UUID          `json:"id"`
	TenantID  uuid.UUID          `json:"tenant_id"`
	CourseID  uuid.UUID          `json:"course_id"`
	Title     string             `json:"title"`
	Position  float64            `json:"position"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Notification struct {
	ID        uuid.UUID          `json:"id"`
	TenantID  uuid.UUID          `json:"tenant_id"`
	UserID    uuid.UUID          `json:"user_id"`
	Kind      string             `json:"kind"`
	Title     string             `json:"title"`
	Body      string             `json:"body"`
	Data      []byte             `json:"data"`
	ReadAt    pgtype.Timestamptz `json:"read_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type NotificationDelivery struct {
	ID             uuid.UUID          `json:"id"`
	NotificationID uuid.UUID          `json:"notification_id"`
	TenantID       uuid.UUID          `json:"tenant_id"`
	Channel        string             `json:"channel"`
	Destination    string             `json:"destination"`
	Body           string             `json:"body"`
	State          DeliveryState      `json:"state"`
	Attempts       int16              `json:"attempts"`
	Error          string             `json:"error"`
	RunAfter       pgtype.Timestamptz `json:"run_after"`
	SentAt         pgtype.Timestamptz `json:"sent_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Order struct {
	ID              uuid.UUID          `json:"id"`
	TenantID        uuid.UUID          `json:"tenant_id"`
	UserID          uuid.UUID          `json:"user_id"`
	CourseID        uuid.UUID          `json:"course_id"`
	Provider        string             `json:"provider"`
	AmountMinor     int64              `json:"amount_minor"`
	Currency        string             `json:"currency"`
	Status          OrderStatus        `json:"status"`
	Reference       string             `json:"reference"`
	ProviderRef     string             `json:"provider_ref"`
	Note            string             `json:"note"`
	ProofMediaID    uuid.NullUUID      `json:"proof_media_id"`
	ReviewedBy      uuid.NullUUID      `json:"reviewed_by"`
	ReviewedAt      pgtype.Timestamptz `json:"reviewed_at"`
	PaidAt          pgtype.Timestamptz `json:"paid_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	CouponID        uuid.NullUUID      `json:"coupon_id"`
	ListAmountMinor *int64             `json:"list_amount_minor"`
	DiscountMinor   int64              `json:"discount_minor"`
	RefundedMinor   int64              `json:"refunded_minor"`
	RefundReason    string             `json:"refund_reason"`
	RefundedBy      uuid.NullUUID      `json:"refunded_by"`
	RefundedAt      pgtype.Timestamptz `json:"refunded_at"`
	PlanID          uuid.NullUUID      `json:"plan_id"`
	PartNo          *int16             `json:"part_no"`
}

type OtpChallenge struct {
	ID          uuid.UUID          `json:"id"`
	Destination string             `json:"destination"`
	Purpose     OtpPurpose         `json:"purpose"`
	CodeHash    []byte             `json:"code_hash"`
	Attempts    int16              `json:"attempts"`
	ConsumedAt  pgtype.Timestamptz `json:"consumed_at"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type PaymentEvent struct {
	ID        uuid.UUID          `json:"id"`
	TenantID  uuid.UUID          `json:"tenant_id"`
	OrderID   uuid.NullUUID      `json:"order_id"`
	Provider  string             `json:"provider"`
	EventID   string             `json:"event_id"`
	Kind      string             `json:"kind"`
	Payload   []byte             `json:"payload"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type PaymentPlan struct {
	ID         uuid.UUID          `json:"id"`
	TenantID   uuid.UUID          `json:"tenant_id"`
	UserID     uuid.UUID          `json:"user_id"`
	CourseID   uuid.UUID          `json:"course_id"`
	TotalMinor int64              `json:"total_minor"`
	Currency   string             `json:"currency"`
	Parts      int16              `json:"parts"`
	PaidParts  int16              `json:"paid_parts"`
	GapDays    int16              `json:"gap_days"`
	NextDueOn  pgtype.Date        `json:"next_due_on"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type PublishedCourse struct {
	ID          uuid.UUID          `json:"id"`
	Slug        string             `json:"slug"`
	Title       string             `json:"title"`
	Summary     string             `json:"summary"`
	Dir         TextDir            `json:"dir"`
	PriceMinor  int64              `json:"price_minor"`
	Currency    string             `json:"currency"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	TenantSlug  string             `json:"tenant_slug"`
}

type PublishedPage struct {
	ID          uuid.UUID          `json:"id"`
	Slug        string             `json:"slug"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	Dir         TextDir            `json:"dir"`
	Blocks      []byte             `json:"blocks"`
	NavLabel    string             `json:"nav_label"`
	NavOrder    int32              `json:"nav_order"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	TenantSlug  string             `json:"tenant_slug"`
	TenantName  string             `json:"tenant_name"`
	TenantDir   TextDir            `json:"tenant_dir"`
	SiteTheme   string             `json:"site_theme"`
}

type Question struct {
	ID          uuid.UUID          `json:"id"`
	TenantID    uuid.UUID          `json:"tenant_id"`
	QuizID      uuid.UUID          `json:"quiz_id"`
	Kind        QuestionKind       `json:"kind"`
	Prompt      string             `json:"prompt"`
	Dir         TextDir            `json:"dir"`
	Points      int32              `json:"points"`
	Explanation string             `json:"explanation"`
	Position    float64            `json:"position"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type QuestionOption struct {
	ID         uuid.UUID `json:"id"`
	TenantID   uuid.UUID `json:"tenant_id"`
	QuestionID uuid.UUID `json:"question_id"`
	Label      string    `json:"label"`
	IsCorrect  bool      `json:"is_correct"`
	Position   float64   `json:"position"`
}

type Quiz struct {
	ID            uuid.UUID          `json:"id"`
	TenantID      uuid.UUID          `json:"tenant_id"`
	LessonID      uuid.UUID          `json:"lesson_id"`
	Title         string             `json:"title"`
	Instructions  string             `json:"instructions"`
	Dir           TextDir            `json:"dir"`
	TimeLimitS    int32              `json:"time_limit_s"`
	MaxAttempts   int16              `json:"max_attempts"`
	PassPercent   int16              `json:"pass_percent"`
	Shuffle       bool               `json:"shuffle"`
	RevealAnswers bool               `json:"reveal_answers"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DrawCount     *int32             `json:"draw_count"`
}

type QuizAttempt struct {
	ID             uuid.UUID          `json:"id"`
	TenantID       uuid.UUID          `json:"tenant_id"`
	QuizID         uuid.UUID          `json:"quiz_id"`
	EnrollmentID   uuid.UUID          `json:"enrollment_id"`
	UserID         uuid.UUID          `json:"user_id"`
	AttemptNo      int16              `json:"attempt_no"`
	State          AttemptState       `json:"state"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	SubmittedAt    pgtype.Timestamptz `json:"submitted_at"`
	GradedAt       pgtype.Timestamptz `json:"graded_at"`
	PointsAwarded  int32              `json:"points_awarded"`
	PointsPossible int32              `json:"points_possible"`
}

type Session struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	TokenHash  []byte             `json:"token_hash"`
	UserAgent  string             `json:"user_agent"`
	Ip         *netip.Addr        `json:"ip"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type SitePage struct {
	ID          uuid.UUID          `json:"id"`
	TenantID    uuid.UUID          `json:"tenant_id"`
	Slug        string             `json:"slug"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	Dir         TextDir            `json:"dir"`
	Blocks      []byte             `json:"blocks"`
	Status      PublishStatus      `json:"status"`
	NavLabel    string             `json:"nav_label"`
	NavOrder    int32              `json:"nav_order"`
	UpdatedBy   uuid.NullUUID      `json:"updated_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Submission struct {
	ID            uuid.UUID          `json:"id"`
	TenantID      uuid.UUID          `json:"tenant_id"`
	AssignmentID  uuid.UUID          `json:"assignment_id"`
	EnrollmentID  uuid.UUID          `json:"enrollment_id"`
	UserID        uuid.UUID          `json:"user_id"`
	State         SubmissionState    `json:"state"`
	Body          string             `json:"body"`
	MediaIds      []uuid.UUID        `json:"media_ids"`
	IsLate        bool               `json:"is_late"`
	SubmittedAt   pgtype.Timestamptz `json:"submitted_at"`
	PointsAwarded *int32             `json:"points_awarded"`
	Feedback      string             `json:"feedback"`
	GradedBy      uuid.NullUUID      `json:"graded_by"`
	GradedAt      pgtype.Timestamptz `json:"graded_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Tenant struct {
	ID               uuid.UUID          `json:"id"`
	Slug             string             `json:"slug"`
	Name             string             `json:"name"`
	Kind             TenantKind         `json:"kind"`
	Status           TenantStatus       `json:"status"`
	DefaultDir       TextDir            `json:"default_dir"`
	Locale           string             `json:"locale"`
	Currency         string             `json:"currency"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	SiteTheme        string             `json:"site_theme"`
	CustomDomain     *string            `json:"custom_domain"`
	DomainToken      string             `json:"domain_token"`
	DomainVerifiedAt pgtype.Timestamptz `json:"domain_verified_at"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	Phone        *string            `json:"phone"`
	Email        *string            `json:"email"`
	FullName     string             `json:"full_name"`
	PasswordHash *string            `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type UserTenant struct {
	UserID     uuid.UUID    `json:"user_id"`
	Role       MemberRole   `json:"role"`
	ID         uuid.UUID    `json:"id"`
	Slug       string       `json:"slug"`
	Name       string       `json:"name"`
	Kind       TenantKind   `json:"kind"`
	Status     TenantStatus `json:"status"`
	DefaultDir TextDir      `json:"default_dir"`
	Locale     string       `json:"locale"`
	Currency   string       `json:"currency"`
}
