// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql/driver"
	"fmt"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type CourseVisibility string

const (
	CourseVisibilityPrivate  CourseVisibility = "private"
	CourseVisibilityUnlisted CourseVisibility = "unlisted"
	CourseVisibilityPublic   CourseVisibility = "public"
)

func (e *CourseVisibility) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CourseVisibility(s)
	case string:
		*e = CourseVisibility(s)
	default:
		return fmt.Errorf("unsupported scan type for CourseVisibility: %T", src)
	}
	return nil
}

type NullCourseVisibility struct {
	CourseVisibility CourseVisibility `json:"course_visibility"`
	Valid            bool             `json:"valid"` // Valid is true if CourseVisibility is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCourseVisibility) Scan(value interface{}) error {
	if value == nil {
		ns.CourseVisibility, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CourseVisibility.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCourseVisibility) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CourseVisibility), nil
}

type LessonKind string

const (
	LessonKindVideo      LessonKind = "video"
	LessonKindAudio      LessonKind = "audio"
	LessonKindText       LessonKind = "text"
	LessonKindPdf        LessonKind = "pdf"
	LessonKindLink       LessonKind = "link"
	LessonKindLive       LessonKind = "live"
	LessonKindQuiz       LessonKind = "quiz"
	LessonKindAssignment LessonKind = "assignment"
)

func (e *LessonKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LessonKind(s)
	case string:
		*e = LessonKind(s)
	default:
		return fmt.Errorf("unsupported scan type for LessonKind: %T", src)
	}
	return nil
}

type NullLessonKind struct {
	LessonKind LessonKind `json:"lesson_kind"`
	Valid      bool       `json:"valid"` // Valid is true if LessonKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLessonKind) Scan(value interface{}) error {
	if value == nil {
		ns.LessonKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LessonKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLessonKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LessonKind), nil
}

type MemberRole string

const (
	MemberRoleOwner      MemberRole = "owner"
	MemberRoleAdmin      MemberRole = "admin"
	MemberRoleInstructor MemberRole = "instructor"
	MemberRoleAssistant  MemberRole = "assistant"
	MemberRoleStudent    MemberRole = "student"
	MemberRoleParent     MemberRole = "parent"
)

func (e *MemberRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MemberRole(s)
	case string:
		*e = MemberRole(s)
	default:
		return fmt.Errorf("unsupported scan type for MemberRole: %T", src)
	}
	return nil
}

type NullMemberRole struct {
	MemberRole MemberRole `json:"member_role"`
	Valid      bool       `json:"valid"` // Valid is true if MemberRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMemberRole) Scan(value interface{}) error {
	if value == nil {
		ns.MemberRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MemberRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMemberRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MemberRole), nil
}

type MemberStatus string

const (
	MemberStatusInvited   MemberStatus = "invited"
	MemberStatusActive    MemberStatus = "active"
	MemberStatusSuspended MemberStatus = "suspended"
)

func (e *MemberStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MemberStatus(s)
	case string:
		*e = MemberStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for MemberStatus: %T", src)
	}
	return nil
}

type NullMemberStatus struct {
	MemberStatus MemberStatus `json:"member_status"`
	Valid        bool         `json:"valid"` // Valid is true if MemberStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMemberStatus) Scan(value interface{}) error {
	if value == nil {
		ns.MemberStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MemberStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMemberStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MemberStatus), nil
}

type OtpPurpose string

const (
	OtpPurposeLogin         OtpPurpose = "login"
	OtpPurposeVerifyContact OtpPurpose = "verify_contact"
)

func (e *OtpPurpose) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OtpPurpose(s)
	case string:
		*e = OtpPurpose(s)
	default:
		return fmt.Errorf("unsupported scan type for OtpPurpose: %T", src)
	}
	return nil
}

type NullOtpPurpose struct {
	OtpPurpose OtpPurpose `json:"otp_purpose"`
	Valid      bool       `json:"valid"` // Valid is true if OtpPurpose is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOtpPurpose) Scan(value interface{}) error {
	if value == nil {
		ns.OtpPurpose, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OtpPurpose.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOtpPurpose) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OtpPurpose), nil
}

type PublishStatus string

const (
	PublishStatusDraft     PublishStatus = "draft"
	PublishStatusPublished PublishStatus = "published"
	PublishStatusArchived  PublishStatus = "archived"
)

func (e *PublishStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PublishStatus(s)
	case string:
		*e = PublishStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PublishStatus: %T", src)
	}
	return nil
}

type NullPublishStatus struct {
	PublishStatus PublishStatus `json:"publish_status"`
	Valid         bool          `json:"valid"` // Valid is true if PublishStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPublishStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PublishStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PublishStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPublishStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PublishStatus), nil
}

type TenantKind string

const (
	TenantKindInstitution TenantKind = "institution"
	TenantKindCreator     TenantKind = "creator"
	TenantKindCorporate   TenantKind = "corporate"
)

func (e *TenantKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TenantKind(s)
	case string:
		*e = TenantKind(s)
	default:
		return fmt.Errorf("unsupported scan type for TenantKind: %T", src)
	}
	return nil
}

type NullTenantKind struct {
	TenantKind TenantKind `json:"tenant_kind"`
	Valid      bool       `json:"valid"` // Valid is true if TenantKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTenantKind) Scan(value interface{}) error {
	if value == nil {
		ns.TenantKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TenantKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTenantKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TenantKind), nil
}

type TenantStatus string

const (
	TenantStatusActive    TenantStatus = "active"
	TenantStatusSuspended TenantStatus = "suspended"
)

func (e *TenantStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TenantStatus(s)
	case string:
		*e = TenantStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TenantStatus: %T", src)
	}
	return nil
}

type NullTenantStatus struct {
	TenantStatus TenantStatus `json:"tenant_status"`
	Valid        bool         `json:"valid"` // Valid is true if TenantStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTenantStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TenantStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TenantStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTenantStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TenantStatus), nil
}

type TextDir string

const (
	TextDirAuto TextDir = "auto"
	TextDirLtr  TextDir = "ltr"
	TextDirRtl  TextDir = "rtl"
)

func (e *TextDir) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TextDir(s)
	case string:
		*e = TextDir(s)
	default:
		return fmt.Errorf("unsupported scan type for TextDir: %T", src)
	}
	return nil
}

type NullTextDir struct {
	TextDir TextDir `json:"text_dir"`
	Valid   bool    `json:"valid"` // Valid is true if TextDir is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTextDir) Scan(value interface{}) error {
	if value == nil {
		ns.TextDir, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TextDir.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTextDir) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TextDir), nil
}

type Course struct {
	ID          uuid.UUID          `json:"id"`
	TenantID    uuid.UUID          `json:"tenant_id"`
	Slug        string             `json:"slug"`
	Title       string             `json:"title"`
	Summary     string             `json:"summary"`
	Dir         TextDir            `json:"dir"`
	Status      PublishStatus      `json:"status"`
	Visibility  CourseVisibility   `json:"visibility"`
	PriceMinor  int64              `json:"price_minor"`
	Currency    string             `json:"currency"`
	CreatedBy   uuid.NullUUID      `json:"created_by"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Lesson struct {
	ID        uuid.UUID          `json:"id"`
	TenantID  uuid.UUID          `json:"tenant_id"`
	ModuleID  uuid.UUID          `json:"module_id"`
	Title     string             `json:"title"`
	Kind      LessonKind         `json:"kind"`
	Body      string             `json:"body"`
	Dir       TextDir            `json:"dir"`
	DurationS int32              `json:"duration_s"`
	IsPreview bool               `json:"is_preview"`
	Status    PublishStatus      `json:"status"`
	Position  float64            `json:"position"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type LiveSession struct {
	SessionID uuid.UUID          `json:"session_id"`
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash []byte             `json:"token_hash"`
	FullName  string             `json:"full_name"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type Membership struct {
	ID        uuid.UUID          `json:"id"`
	TenantID  uuid.UUID          `json:"tenant_id"`
	UserID    uuid.UUID          `json:"user_id"`
	Role      MemberRole         `json:"role"`
	Status    MemberStatus       `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Module struct {
	ID        uuid.UUID          `json:"id"`
	TenantID  uuid.UUID          `json:"tenant_id"`
	CourseID  uuid.UUID          `json:"course_id"`
	Title     string             `json:"title"`
	Position  float64            `json:"position"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type OtpChallenge struct {
	ID          uuid.UUID          `json:"id"`
	Destination string             `json:"destination"`
	Purpose     OtpPurpose         `json:"purpose"`
	CodeHash    []byte             `json:"code_hash"`
	Attempts    int16              `json:"attempts"`
	ConsumedAt  pgtype.Timestamptz `json:"consumed_at"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Session struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	TokenHash  []byte             `json:"token_hash"`
	UserAgent  string             `json:"user_agent"`
	Ip         *netip.Addr        `json:"ip"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Tenant struct {
	ID         uuid.UUID          `json:"id"`
	Slug       string             `json:"slug"`
	Name       string             `json:"name"`
	Kind       TenantKind         `json:"kind"`
	Status     TenantStatus       `json:"status"`
	DefaultDir TextDir            `json:"default_dir"`
	Locale     string             `json:"locale"`
	Currency   string             `json:"currency"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	Phone        *string            `json:"phone"`
	Email        *string            `json:"email"`
	FullName     string             `json:"full_name"`
	PasswordHash *string            `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
