// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type MemberRole string

const (
	MemberRoleOwner      MemberRole = "owner"
	MemberRoleAdmin      MemberRole = "admin"
	MemberRoleInstructor MemberRole = "instructor"
	MemberRoleAssistant  MemberRole = "assistant"
	MemberRoleStudent    MemberRole = "student"
	MemberRoleParent     MemberRole = "parent"
)

func (e *MemberRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MemberRole(s)
	case string:
		*e = MemberRole(s)
	default:
		return fmt.Errorf("unsupported scan type for MemberRole: %T", src)
	}
	return nil
}

type NullMemberRole struct {
	MemberRole MemberRole `json:"member_role"`
	Valid      bool       `json:"valid"` // Valid is true if MemberRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMemberRole) Scan(value interface{}) error {
	if value == nil {
		ns.MemberRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MemberRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMemberRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MemberRole), nil
}

type MemberStatus string

const (
	MemberStatusInvited   MemberStatus = "invited"
	MemberStatusActive    MemberStatus = "active"
	MemberStatusSuspended MemberStatus = "suspended"
)

func (e *MemberStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MemberStatus(s)
	case string:
		*e = MemberStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for MemberStatus: %T", src)
	}
	return nil
}

type NullMemberStatus struct {
	MemberStatus MemberStatus `json:"member_status"`
	Valid        bool         `json:"valid"` // Valid is true if MemberStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMemberStatus) Scan(value interface{}) error {
	if value == nil {
		ns.MemberStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MemberStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMemberStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MemberStatus), nil
}

type TenantKind string

const (
	TenantKindInstitution TenantKind = "institution"
	TenantKindCreator     TenantKind = "creator"
	TenantKindCorporate   TenantKind = "corporate"
)

func (e *TenantKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TenantKind(s)
	case string:
		*e = TenantKind(s)
	default:
		return fmt.Errorf("unsupported scan type for TenantKind: %T", src)
	}
	return nil
}

type NullTenantKind struct {
	TenantKind TenantKind `json:"tenant_kind"`
	Valid      bool       `json:"valid"` // Valid is true if TenantKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTenantKind) Scan(value interface{}) error {
	if value == nil {
		ns.TenantKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TenantKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTenantKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TenantKind), nil
}

type TenantStatus string

const (
	TenantStatusActive    TenantStatus = "active"
	TenantStatusSuspended TenantStatus = "suspended"
)

func (e *TenantStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TenantStatus(s)
	case string:
		*e = TenantStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TenantStatus: %T", src)
	}
	return nil
}

type NullTenantStatus struct {
	TenantStatus TenantStatus `json:"tenant_status"`
	Valid        bool         `json:"valid"` // Valid is true if TenantStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTenantStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TenantStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TenantStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTenantStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TenantStatus), nil
}

type TextDir string

const (
	TextDirAuto TextDir = "auto"
	TextDirLtr  TextDir = "ltr"
	TextDirRtl  TextDir = "rtl"
)

func (e *TextDir) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TextDir(s)
	case string:
		*e = TextDir(s)
	default:
		return fmt.Errorf("unsupported scan type for TextDir: %T", src)
	}
	return nil
}

type NullTextDir struct {
	TextDir TextDir `json:"text_dir"`
	Valid   bool    `json:"valid"` // Valid is true if TextDir is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTextDir) Scan(value interface{}) error {
	if value == nil {
		ns.TextDir, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TextDir.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTextDir) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TextDir), nil
}

type Membership struct {
	ID        uuid.UUID          `json:"id"`
	TenantID  uuid.UUID          `json:"tenant_id"`
	UserID    uuid.UUID          `json:"user_id"`
	Role      MemberRole         `json:"role"`
	Status    MemberStatus       `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Tenant struct {
	ID         uuid.UUID          `json:"id"`
	Slug       string             `json:"slug"`
	Name       string             `json:"name"`
	Kind       TenantKind         `json:"kind"`
	Status     TenantStatus       `json:"status"`
	DefaultDir TextDir            `json:"default_dir"`
	Locale     string             `json:"locale"`
	Currency   string             `json:"currency"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	Phone        *string            `json:"phone"`
	Email        *string            `json:"email"`
	FullName     string             `json:"full_name"`
	PasswordHash *string            `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
