// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notices.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const classAudience = `-- name: ClassAudience :many
SELECT p.user_id AS student_id, g.guardian_id
FROM placements p
JOIN sections s ON s.id = p.section_id
JOIN academic_years y ON y.id = p.year_id AND y.is_current
LEFT JOIN guardianships g ON g.student_id = p.user_id AND g.tenant_id = p.tenant_id
WHERE s.class_id = $1
`

type ClassAudienceRow struct {
	StudentID  uuid.UUID     `json:"student_id"`
	GuardianID uuid.NullUUID `json:"guardian_id"`
}

func (q *Queries) ClassAudience(ctx context.Context, classID uuid.UUID) ([]ClassAudienceRow, error) {
	rows, err := q.db.Query(ctx, classAudience, classID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClassAudienceRow{}
	for rows.Next() {
		var i ClassAudienceRow
		if err := rows.Scan(&i.StudentID, &i.GuardianID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const myChildren = `-- name: MyChildren :many
SELECT g.student_id, g.relation, u.full_name,
       (SELECT s.name FROM placements p
        JOIN sections s ON s.id = p.section_id
        JOIN academic_years y ON y.id = p.year_id AND y.is_current
        WHERE p.user_id = g.student_id) AS section_name,
       (SELECT c.name FROM placements p
        JOIN sections s ON s.id = p.section_id
        JOIN classes c ON c.id = s.class_id
        JOIN academic_years y ON y.id = p.year_id AND y.is_current
        WHERE p.user_id = g.student_id) AS class_name
FROM guardianships g JOIN users u ON u.id = g.student_id
WHERE g.guardian_id = $1
ORDER BY u.full_name
`

type MyChildrenRow struct {
	StudentID   uuid.UUID `json:"student_id"`
	Relation    string    `json:"relation"`
	FullName    string    `json:"full_name"`
	SectionName string    `json:"section_name"`
	ClassName   string    `json:"class_name"`
}

func (q *Queries) MyChildren(ctx context.Context, guardianID uuid.UUID) ([]MyChildrenRow, error) {
	rows, err := q.db.Query(ctx, myChildren, guardianID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MyChildrenRow{}
	for rows.Next() {
		var i MyChildrenRow
		if err := rows.Scan(
			&i.StudentID,
			&i.Relation,
			&i.FullName,
			&i.SectionName,
			&i.ClassName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const schoolAudience = `-- name: SchoolAudience :many
SELECT m.user_id AS student_id, g.guardian_id
FROM memberships m
LEFT JOIN guardianships g ON g.student_id = m.user_id AND g.tenant_id = m.tenant_id
WHERE m.role = 'student' AND m.status = 'active'
`

type SchoolAudienceRow struct {
	StudentID  uuid.UUID     `json:"student_id"`
	GuardianID uuid.NullUUID `json:"guardian_id"`
}

func (q *Queries) SchoolAudience(ctx context.Context) ([]SchoolAudienceRow, error) {
	rows, err := q.db.Query(ctx, schoolAudience)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SchoolAudienceRow{}
	for rows.Next() {
		var i SchoolAudienceRow
		if err := rows.Scan(&i.StudentID, &i.GuardianID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sectionAudience = `-- name: SectionAudience :many
SELECT p.user_id AS student_id, g.guardian_id
FROM placements p
JOIN academic_years y ON y.id = p.year_id AND y.is_current
LEFT JOIN guardianships g ON g.student_id = p.user_id AND g.tenant_id = p.tenant_id
WHERE p.section_id = $1
`

type SectionAudienceRow struct {
	StudentID  uuid.UUID     `json:"student_id"`
	GuardianID uuid.NullUUID `json:"guardian_id"`
}

func (q *Queries) SectionAudience(ctx context.Context, sectionID uuid.UUID) ([]SectionAudienceRow, error) {
	rows, err := q.db.Query(ctx, sectionAudience, sectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SectionAudienceRow{}
	for rows.Next() {
		var i SectionAudienceRow
		if err := rows.Scan(&i.StudentID, &i.GuardianID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
