// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimDeliveries = `-- name: ClaimDeliveries :many
SELECT id, notification_id, tenant_id, channel, destination, body, state, attempts, error, run_after, sent_at, created_at FROM claim_deliveries($1)
`

func (q *Queries) ClaimDeliveries(ctx context.Context, claimLimit int32) ([]NotificationDelivery, error) {
	rows, err := q.db.Query(ctx, claimDeliveries, claimLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationDelivery{}
	for rows.Next() {
		var i NotificationDelivery
		if err := rows.Scan(
			&i.ID,
			&i.NotificationID,
			&i.TenantID,
			&i.Channel,
			&i.Destination,
			&i.Body,
			&i.State,
			&i.Attempts,
			&i.Error,
			&i.RunAfter,
			&i.SentAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countUnread = `-- name: CountUnread :one
SELECT count(*) FROM notifications WHERE user_id = $1 AND read_at IS NULL
`

func (q *Queries) CountUnread(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnread, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (tenant_id, user_id, kind, title, body, data)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, user_id, kind, title, body, data, read_at, created_at
`

type CreateNotificationParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	UserID   uuid.UUID `json:"user_id"`
	Kind     string    `json:"kind"`
	Title    string    `json:"title"`
	Body     string    `json:"body"`
	Data     []byte    `json:"data"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.TenantID,
		arg.UserID,
		arg.Kind,
		arg.Title,
		arg.Body,
		arg.Data,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Kind,
		&i.Title,
		&i.Body,
		&i.Data,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const deliveriesForNotification = `-- name: DeliveriesForNotification :many
SELECT id, notification_id, tenant_id, channel, destination, body, state, attempts, error, run_after, sent_at, created_at FROM notification_deliveries WHERE notification_id = $1 ORDER BY channel
`

func (q *Queries) DeliveriesForNotification(ctx context.Context, notificationID uuid.UUID) ([]NotificationDelivery, error) {
	rows, err := q.db.Query(ctx, deliveriesForNotification, notificationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationDelivery{}
	for rows.Next() {
		var i NotificationDelivery
		if err := rows.Scan(
			&i.ID,
			&i.NotificationID,
			&i.TenantID,
			&i.Channel,
			&i.Destination,
			&i.Body,
			&i.State,
			&i.Attempts,
			&i.Error,
			&i.RunAfter,
			&i.SentAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInbox = `-- name: ListInbox :many
SELECT id, tenant_id, user_id, kind, title, body, data, read_at, created_at FROM notifications
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListInboxParams struct {
	UserID     uuid.UUID `json:"user_id"`
	PageOffset int32     `json:"page_offset"`
	PageLimit  int32     `json:"page_limit"`
}

func (q *Queries) ListInbox(ctx context.Context, arg ListInboxParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listInbox, arg.UserID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.Kind,
			&i.Title,
			&i.Body,
			&i.Data,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllRead = `-- name: MarkAllRead :execrows
UPDATE notifications SET read_at = now() WHERE user_id = $1 AND read_at IS NULL
`

func (q *Queries) MarkAllRead(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markAllRead, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markRead = `-- name: MarkRead :execrows
UPDATE notifications SET read_at = now() WHERE id = $1 AND user_id = $2 AND read_at IS NULL
`

type MarkReadParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) MarkRead(ctx context.Context, arg MarkReadParams) (int64, error) {
	result, err := q.db.Exec(ctx, markRead, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const queueDelivery = `-- name: QueueDelivery :one
INSERT INTO notification_deliveries (notification_id, tenant_id, channel, destination, body)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, notification_id, tenant_id, channel, destination, body, state, attempts, error, run_after, sent_at, created_at
`

type QueueDeliveryParams struct {
	NotificationID uuid.UUID `json:"notification_id"`
	TenantID       uuid.UUID `json:"tenant_id"`
	Channel        string    `json:"channel"`
	Destination    string    `json:"destination"`
	Body           string    `json:"body"`
}

func (q *Queries) QueueDelivery(ctx context.Context, arg QueueDeliveryParams) (NotificationDelivery, error) {
	row := q.db.QueryRow(ctx, queueDelivery,
		arg.NotificationID,
		arg.TenantID,
		arg.Channel,
		arg.Destination,
		arg.Body,
	)
	var i NotificationDelivery
	err := row.Scan(
		&i.ID,
		&i.NotificationID,
		&i.TenantID,
		&i.Channel,
		&i.Destination,
		&i.Body,
		&i.State,
		&i.Attempts,
		&i.Error,
		&i.RunAfter,
		&i.SentAt,
		&i.CreatedAt,
	)
	return i, err
}

const settleDelivery = `-- name: SettleDelivery :exec
SELECT settle_delivery($1, $2, $3, $4)
`

type SettleDeliveryParams struct {
	DeliveryID uuid.UUID       `json:"delivery_id"`
	NewState   DeliveryState   `json:"new_state"`
	Failure    string          `json:"failure"`
	Backoff    pgtype.Interval `json:"backoff"`
}

func (q *Queries) SettleDelivery(ctx context.Context, arg SettleDeliveryParams) error {
	_, err := q.db.Exec(ctx, settleDelivery,
		arg.DeliveryID,
		arg.NewState,
		arg.Failure,
		arg.Backoff,
	)
	return err
}
