// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const cancelOrder = `-- name: CancelOrder :one
UPDATE orders SET status = 'cancelled'
WHERE id = $1 AND status IN ('pending', 'awaiting_review')
RETURNING id, tenant_id, user_id, course_id, provider, amount_minor, currency, status, reference, provider_ref, note, proof_media_id, reviewed_by, reviewed_at, paid_at, created_at, updated_at, coupon_id, list_amount_minor, discount_minor
`

func (q *Queries) CancelOrder(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, cancelOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.CourseID,
		&i.Provider,
		&i.AmountMinor,
		&i.Currency,
		&i.Status,
		&i.Reference,
		&i.ProviderRef,
		&i.Note,
		&i.ProofMediaID,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CouponID,
		&i.ListAmountMinor,
		&i.DiscountMinor,
	)
	return i, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (tenant_id, user_id, course_id, provider, amount_minor, currency, reference,
                    coupon_id, list_amount_minor, discount_minor)
VALUES ($1, $2, $3, $4, $5, $6, $7,
        $8, $9, $10)
RETURNING id, tenant_id, user_id, course_id, provider, amount_minor, currency, status, reference, provider_ref, note, proof_media_id, reviewed_by, reviewed_at, paid_at, created_at, updated_at, coupon_id, list_amount_minor, discount_minor
`

type CreateOrderParams struct {
	TenantID        uuid.UUID     `json:"tenant_id"`
	UserID          uuid.UUID     `json:"user_id"`
	CourseID        uuid.UUID     `json:"course_id"`
	Provider        string        `json:"provider"`
	AmountMinor     int64         `json:"amount_minor"`
	Currency        string        `json:"currency"`
	Reference       string        `json:"reference"`
	CouponID        uuid.NullUUID `json:"coupon_id"`
	ListAmountMinor *int64        `json:"list_amount_minor"`
	DiscountMinor   int64         `json:"discount_minor"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.TenantID,
		arg.UserID,
		arg.CourseID,
		arg.Provider,
		arg.AmountMinor,
		arg.Currency,
		arg.Reference,
		arg.CouponID,
		arg.ListAmountMinor,
		arg.DiscountMinor,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.CourseID,
		&i.Provider,
		&i.AmountMinor,
		&i.Currency,
		&i.Status,
		&i.Reference,
		&i.ProviderRef,
		&i.Note,
		&i.ProofMediaID,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CouponID,
		&i.ListAmountMinor,
		&i.DiscountMinor,
	)
	return i, err
}

const getOrder = `-- name: GetOrder :one
SELECT id, tenant_id, user_id, course_id, provider, amount_minor, currency, status, reference, provider_ref, note, proof_media_id, reviewed_by, reviewed_at, paid_at, created_at, updated_at, coupon_id, list_amount_minor, discount_minor FROM orders WHERE id = $1
`

func (q *Queries) GetOrder(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.CourseID,
		&i.Provider,
		&i.AmountMinor,
		&i.Currency,
		&i.Status,
		&i.Reference,
		&i.ProviderRef,
		&i.Note,
		&i.ProofMediaID,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CouponID,
		&i.ListAmountMinor,
		&i.DiscountMinor,
	)
	return i, err
}

const getOrderByReference = `-- name: GetOrderByReference :one
SELECT id, tenant_id, user_id, course_id, provider, amount_minor, currency, status, reference, provider_ref, note, proof_media_id, reviewed_by, reviewed_at, paid_at, created_at, updated_at, coupon_id, list_amount_minor, discount_minor FROM orders WHERE reference = $1
`

func (q *Queries) GetOrderByReference(ctx context.Context, reference string) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByReference, reference)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.CourseID,
		&i.Provider,
		&i.AmountMinor,
		&i.Currency,
		&i.Status,
		&i.Reference,
		&i.ProviderRef,
		&i.Note,
		&i.ProofMediaID,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CouponID,
		&i.ListAmountMinor,
		&i.DiscountMinor,
	)
	return i, err
}

const listMyOrders = `-- name: ListMyOrders :many
SELECT o.id, o.tenant_id, o.user_id, o.course_id, o.provider, o.amount_minor, o.currency, o.status, o.reference, o.provider_ref, o.note, o.proof_media_id, o.reviewed_by, o.reviewed_at, o.paid_at, o.created_at, o.updated_at, o.coupon_id, o.list_amount_minor, o.discount_minor, c.title, c.slug
FROM orders o JOIN courses c ON c.id = o.course_id
WHERE o.user_id = $1
ORDER BY o.created_at DESC
LIMIT $3 OFFSET $2
`

type ListMyOrdersParams struct {
	UserID     uuid.UUID `json:"user_id"`
	PageOffset int32     `json:"page_offset"`
	PageLimit  int32     `json:"page_limit"`
}

type ListMyOrdersRow struct {
	Order Order  `json:"order"`
	Title string `json:"title"`
	Slug  string `json:"slug"`
}

func (q *Queries) ListMyOrders(ctx context.Context, arg ListMyOrdersParams) ([]ListMyOrdersRow, error) {
	rows, err := q.db.Query(ctx, listMyOrders, arg.UserID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMyOrdersRow{}
	for rows.Next() {
		var i ListMyOrdersRow
		if err := rows.Scan(
			&i.Order.ID,
			&i.Order.TenantID,
			&i.Order.UserID,
			&i.Order.CourseID,
			&i.Order.Provider,
			&i.Order.AmountMinor,
			&i.Order.Currency,
			&i.Order.Status,
			&i.Order.Reference,
			&i.Order.ProviderRef,
			&i.Order.Note,
			&i.Order.ProofMediaID,
			&i.Order.ReviewedBy,
			&i.Order.ReviewedAt,
			&i.Order.PaidAt,
			&i.Order.CreatedAt,
			&i.Order.UpdatedAt,
			&i.Order.CouponID,
			&i.Order.ListAmountMinor,
			&i.Order.DiscountMinor,
			&i.Title,
			&i.Slug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderEvents = `-- name: ListOrderEvents :many
SELECT id, tenant_id, order_id, provider, event_id, kind, payload, created_at FROM payment_events WHERE order_id = $1 ORDER BY created_at
`

func (q *Queries) ListOrderEvents(ctx context.Context, orderID uuid.NullUUID) ([]PaymentEvent, error) {
	rows, err := q.db.Query(ctx, listOrderEvents, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentEvent{}
	for rows.Next() {
		var i PaymentEvent
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.OrderID,
			&i.Provider,
			&i.EventID,
			&i.Kind,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersForReview = `-- name: ListOrdersForReview :many
SELECT o.id, o.tenant_id, o.user_id, o.course_id, o.provider, o.amount_minor, o.currency, o.status, o.reference, o.provider_ref, o.note, o.proof_media_id, o.reviewed_by, o.reviewed_at, o.paid_at, o.created_at, o.updated_at, o.coupon_id, o.list_amount_minor, o.discount_minor, c.title, u.full_name
FROM orders o JOIN courses c ON c.id = o.course_id JOIN users u ON u.id = o.user_id
WHERE o.status = 'awaiting_review'
ORDER BY o.created_at
LIMIT $2 OFFSET $1
`

type ListOrdersForReviewParams struct {
	PageOffset int32 `json:"page_offset"`
	PageLimit  int32 `json:"page_limit"`
}

type ListOrdersForReviewRow struct {
	Order    Order  `json:"order"`
	Title    string `json:"title"`
	FullName string `json:"full_name"`
}

func (q *Queries) ListOrdersForReview(ctx context.Context, arg ListOrdersForReviewParams) ([]ListOrdersForReviewRow, error) {
	rows, err := q.db.Query(ctx, listOrdersForReview, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrdersForReviewRow{}
	for rows.Next() {
		var i ListOrdersForReviewRow
		if err := rows.Scan(
			&i.Order.ID,
			&i.Order.TenantID,
			&i.Order.UserID,
			&i.Order.CourseID,
			&i.Order.Provider,
			&i.Order.AmountMinor,
			&i.Order.Currency,
			&i.Order.Status,
			&i.Order.Reference,
			&i.Order.ProviderRef,
			&i.Order.Note,
			&i.Order.ProofMediaID,
			&i.Order.ReviewedBy,
			&i.Order.ReviewedAt,
			&i.Order.PaidAt,
			&i.Order.CreatedAt,
			&i.Order.UpdatedAt,
			&i.Order.CouponID,
			&i.Order.ListAmountMinor,
			&i.Order.DiscountMinor,
			&i.Title,
			&i.FullName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const openOrderForCourse = `-- name: OpenOrderForCourse :one
SELECT id, tenant_id, user_id, course_id, provider, amount_minor, currency, status, reference, provider_ref, note, proof_media_id, reviewed_by, reviewed_at, paid_at, created_at, updated_at, coupon_id, list_amount_minor, discount_minor FROM orders
WHERE course_id = $1 AND user_id = $2 AND status IN ('pending', 'awaiting_review')
`

type OpenOrderForCourseParams struct {
	CourseID uuid.UUID `json:"course_id"`
	UserID   uuid.UUID `json:"user_id"`
}

func (q *Queries) OpenOrderForCourse(ctx context.Context, arg OpenOrderForCourseParams) (Order, error) {
	row := q.db.QueryRow(ctx, openOrderForCourse, arg.CourseID, arg.UserID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.CourseID,
		&i.Provider,
		&i.AmountMinor,
		&i.Currency,
		&i.Status,
		&i.Reference,
		&i.ProviderRef,
		&i.Note,
		&i.ProofMediaID,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CouponID,
		&i.ListAmountMinor,
		&i.DiscountMinor,
	)
	return i, err
}

const recordPaymentEvent = `-- name: RecordPaymentEvent :one
INSERT INTO payment_events (tenant_id, order_id, provider, event_id, kind, payload)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (provider, event_id) DO NOTHING
RETURNING id, tenant_id, order_id, provider, event_id, kind, payload, created_at
`

type RecordPaymentEventParams struct {
	TenantID uuid.UUID     `json:"tenant_id"`
	OrderID  uuid.NullUUID `json:"order_id"`
	Provider string        `json:"provider"`
	EventID  string        `json:"event_id"`
	Kind     string        `json:"kind"`
	Payload  []byte        `json:"payload"`
}

func (q *Queries) RecordPaymentEvent(ctx context.Context, arg RecordPaymentEventParams) (PaymentEvent, error) {
	row := q.db.QueryRow(ctx, recordPaymentEvent,
		arg.TenantID,
		arg.OrderID,
		arg.Provider,
		arg.EventID,
		arg.Kind,
		arg.Payload,
	)
	var i PaymentEvent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OrderID,
		&i.Provider,
		&i.EventID,
		&i.Kind,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const settleOrder = `-- name: SettleOrder :one
UPDATE orders SET
  status = $1,
  reviewed_by = $2,
  reviewed_at = now(),
  paid_at = CASE WHEN $1::order_status = 'paid' THEN coalesce(paid_at, now()) ELSE paid_at END
WHERE id = $3 AND status IN ('pending', 'awaiting_review')
RETURNING id, tenant_id, user_id, course_id, provider, amount_minor, currency, status, reference, provider_ref, note, proof_media_id, reviewed_by, reviewed_at, paid_at, created_at, updated_at, coupon_id, list_amount_minor, discount_minor
`

type SettleOrderParams struct {
	Status     OrderStatus   `json:"status"`
	ReviewedBy uuid.NullUUID `json:"reviewed_by"`
	ID         uuid.UUID     `json:"id"`
}

func (q *Queries) SettleOrder(ctx context.Context, arg SettleOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, settleOrder, arg.Status, arg.ReviewedBy, arg.ID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.CourseID,
		&i.Provider,
		&i.AmountMinor,
		&i.Currency,
		&i.Status,
		&i.Reference,
		&i.ProviderRef,
		&i.Note,
		&i.ProofMediaID,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CouponID,
		&i.ListAmountMinor,
		&i.DiscountMinor,
	)
	return i, err
}

const submitPaymentProof = `-- name: SubmitPaymentProof :one
UPDATE orders SET
  status = 'awaiting_review',
  proof_media_id = $1,
  provider_ref = $2,
  note = $3
WHERE id = $4 AND status = 'pending'
RETURNING id, tenant_id, user_id, course_id, provider, amount_minor, currency, status, reference, provider_ref, note, proof_media_id, reviewed_by, reviewed_at, paid_at, created_at, updated_at, coupon_id, list_amount_minor, discount_minor
`

type SubmitPaymentProofParams struct {
	ProofMediaID uuid.NullUUID `json:"proof_media_id"`
	ProviderRef  string        `json:"provider_ref"`
	Note         string        `json:"note"`
	ID           uuid.UUID     `json:"id"`
}

func (q *Queries) SubmitPaymentProof(ctx context.Context, arg SubmitPaymentProofParams) (Order, error) {
	row := q.db.QueryRow(ctx, submitPaymentProof,
		arg.ProofMediaID,
		arg.ProviderRef,
		arg.Note,
		arg.ID,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.CourseID,
		&i.Provider,
		&i.AmountMinor,
		&i.Currency,
		&i.Status,
		&i.Reference,
		&i.ProviderRef,
		&i.Note,
		&i.ProofMediaID,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CouponID,
		&i.ListAmountMinor,
		&i.DiscountMinor,
	)
	return i, err
}
