// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plans.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const countPlanPart = `-- name: CountPlanPart :one
UPDATE payment_plans SET
  paid_parts = paid_parts + 1,
  next_due_on = CASE WHEN paid_parts + 1 >= parts THEN NULL
                     ELSE current_date + (gap_days || ' days')::interval END
WHERE id = $1 AND paid_parts < parts
RETURNING id, tenant_id, user_id, course_id, total_minor, currency, parts, paid_parts, gap_days, next_due_on, created_at, updated_at
`

// Counts a part as paid and moves the due date on. The whole plan being paid
// off leaves no next date.
func (q *Queries) CountPlanPart(ctx context.Context, id uuid.UUID) (PaymentPlan, error) {
	row := q.db.QueryRow(ctx, countPlanPart, id)
	var i PaymentPlan
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.CourseID,
		&i.TotalMinor,
		&i.Currency,
		&i.Parts,
		&i.PaidParts,
		&i.GapDays,
		&i.NextDueOn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPlan = `-- name: CreatePlan :one
INSERT INTO payment_plans (tenant_id, user_id, course_id, total_minor, currency, parts, gap_days, next_due_on)
VALUES ($1, $2, $3, $4, $5, $6, $7, current_date)
RETURNING id, tenant_id, user_id, course_id, total_minor, currency, parts, paid_parts, gap_days, next_due_on, created_at, updated_at
`

type CreatePlanParams struct {
	TenantID   uuid.UUID `json:"tenant_id"`
	UserID     uuid.UUID `json:"user_id"`
	CourseID   uuid.UUID `json:"course_id"`
	TotalMinor int64     `json:"total_minor"`
	Currency   string    `json:"currency"`
	Parts      int16     `json:"parts"`
	GapDays    int16     `json:"gap_days"`
}

func (q *Queries) CreatePlan(ctx context.Context, arg CreatePlanParams) (PaymentPlan, error) {
	row := q.db.QueryRow(ctx, createPlan,
		arg.TenantID,
		arg.UserID,
		arg.CourseID,
		arg.TotalMinor,
		arg.Currency,
		arg.Parts,
		arg.GapDays,
	)
	var i PaymentPlan
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.CourseID,
		&i.TotalMinor,
		&i.Currency,
		&i.Parts,
		&i.PaidParts,
		&i.GapDays,
		&i.NextDueOn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlan = `-- name: GetPlan :one
SELECT id, tenant_id, user_id, course_id, total_minor, currency, parts, paid_parts, gap_days, next_due_on, created_at, updated_at FROM payment_plans WHERE id = $1
`

func (q *Queries) GetPlan(ctx context.Context, id uuid.UUID) (PaymentPlan, error) {
	row := q.db.QueryRow(ctx, getPlan, id)
	var i PaymentPlan
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.CourseID,
		&i.TotalMinor,
		&i.Currency,
		&i.Parts,
		&i.PaidParts,
		&i.GapDays,
		&i.NextDueOn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPlans = `-- name: ListPlans :many
SELECT p.id, p.tenant_id, p.user_id, p.course_id, p.total_minor, p.currency, p.parts, p.paid_parts, p.gap_days, p.next_due_on, p.created_at, p.updated_at, c.title, u.full_name
FROM payment_plans p JOIN courses c ON c.id = p.course_id JOIN users u ON u.id = p.user_id
ORDER BY p.next_due_on NULLS LAST
LIMIT $2 OFFSET $1
`

type ListPlansParams struct {
	PageOffset int32 `json:"page_offset"`
	PageLimit  int32 `json:"page_limit"`
}

type ListPlansRow struct {
	PaymentPlan PaymentPlan `json:"payment_plan"`
	Title       string      `json:"title"`
	FullName    string      `json:"full_name"`
}

func (q *Queries) ListPlans(ctx context.Context, arg ListPlansParams) ([]ListPlansRow, error) {
	rows, err := q.db.Query(ctx, listPlans, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlansRow{}
	for rows.Next() {
		var i ListPlansRow
		if err := rows.Scan(
			&i.PaymentPlan.ID,
			&i.PaymentPlan.TenantID,
			&i.PaymentPlan.UserID,
			&i.PaymentPlan.CourseID,
			&i.PaymentPlan.TotalMinor,
			&i.PaymentPlan.Currency,
			&i.PaymentPlan.Parts,
			&i.PaymentPlan.PaidParts,
			&i.PaymentPlan.GapDays,
			&i.PaymentPlan.NextDueOn,
			&i.PaymentPlan.CreatedAt,
			&i.PaymentPlan.UpdatedAt,
			&i.Title,
			&i.FullName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const myPlans = `-- name: MyPlans :many
SELECT p.id, p.tenant_id, p.user_id, p.course_id, p.total_minor, p.currency, p.parts, p.paid_parts, p.gap_days, p.next_due_on, p.created_at, p.updated_at, c.title, c.slug
FROM payment_plans p JOIN courses c ON c.id = p.course_id
WHERE p.user_id = $1
ORDER BY p.next_due_on NULLS LAST
`

type MyPlansRow struct {
	PaymentPlan PaymentPlan `json:"payment_plan"`
	Title       string      `json:"title"`
	Slug        string      `json:"slug"`
}

func (q *Queries) MyPlans(ctx context.Context, userID uuid.UUID) ([]MyPlansRow, error) {
	rows, err := q.db.Query(ctx, myPlans, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MyPlansRow{}
	for rows.Next() {
		var i MyPlansRow
		if err := rows.Scan(
			&i.PaymentPlan.ID,
			&i.PaymentPlan.TenantID,
			&i.PaymentPlan.UserID,
			&i.PaymentPlan.CourseID,
			&i.PaymentPlan.TotalMinor,
			&i.PaymentPlan.Currency,
			&i.PaymentPlan.Parts,
			&i.PaymentPlan.PaidParts,
			&i.PaymentPlan.GapDays,
			&i.PaymentPlan.NextDueOn,
			&i.PaymentPlan.CreatedAt,
			&i.PaymentPlan.UpdatedAt,
			&i.Title,
			&i.Slug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const planForCourse = `-- name: PlanForCourse :one
SELECT id, tenant_id, user_id, course_id, total_minor, currency, parts, paid_parts, gap_days, next_due_on, created_at, updated_at FROM payment_plans WHERE course_id = $1 AND user_id = $2
`

type PlanForCourseParams struct {
	CourseID uuid.UUID `json:"course_id"`
	UserID   uuid.UUID `json:"user_id"`
}

func (q *Queries) PlanForCourse(ctx context.Context, arg PlanForCourseParams) (PaymentPlan, error) {
	row := q.db.QueryRow(ctx, planForCourse, arg.CourseID, arg.UserID)
	var i PaymentPlan
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.CourseID,
		&i.TotalMinor,
		&i.Currency,
		&i.Parts,
		&i.PaidParts,
		&i.GapDays,
		&i.NextDueOn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
