// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: points.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const awardBadge = `-- name: AwardBadge :exec
INSERT INTO badge_awards (badge_id, user_id, tenant_id)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type AwardBadgeParams struct {
	BadgeID  uuid.UUID `json:"badge_id"`
	UserID   uuid.UUID `json:"user_id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) AwardBadge(ctx context.Context, arg AwardBadgeParams) error {
	_, err := q.db.Exec(ctx, awardBadge, arg.BadgeID, arg.UserID, arg.TenantID)
	return err
}

const awardPoints = `-- name: AwardPoints :exec
INSERT INTO point_awards (tenant_id, user_id, kind, ref_id, points)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (tenant_id, user_id, kind, ref_id) DO NOTHING
`

type AwardPointsParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	UserID   uuid.UUID `json:"user_id"`
	Kind     string    `json:"kind"`
	RefID    uuid.UUID `json:"ref_id"`
	Points   int32     `json:"points"`
}

// Nothing happens if this thing was already paid for.
func (q *Queries) AwardPoints(ctx context.Context, arg AwardPointsParams) error {
	_, err := q.db.Exec(ctx, awardPoints,
		arg.TenantID,
		arg.UserID,
		arg.Kind,
		arg.RefID,
		arg.Points,
	)
	return err
}

const badgesToAward = `-- name: BadgesToAward :many
SELECT b.id, b.tenant_id, b.name, b.description, b.emoji, b.threshold, b.created_at FROM badges b
WHERE b.threshold <= $1
  AND NOT EXISTS (SELECT 1 FROM badge_awards a WHERE a.badge_id = b.id AND a.user_id = $2)
`

type BadgesToAwardParams struct {
	Points int32     `json:"points"`
	UserID uuid.UUID `json:"user_id"`
}

// The badges this person has passed the mark for and does not yet hold.
func (q *Queries) BadgesToAward(ctx context.Context, arg BadgesToAwardParams) ([]Badge, error) {
	rows, err := q.db.Query(ctx, badgesToAward, arg.Points, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Badge{}
	for rows.Next() {
		var i Badge
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Description,
			&i.Emoji,
			&i.Threshold,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createBadge = `-- name: CreateBadge :one
INSERT INTO badges (tenant_id, name, description, emoji, threshold)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, name, description, emoji, threshold, created_at
`

type CreateBadgeParams struct {
	TenantID    uuid.UUID `json:"tenant_id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Emoji       string    `json:"emoji"`
	Threshold   int32     `json:"threshold"`
}

func (q *Queries) CreateBadge(ctx context.Context, arg CreateBadgeParams) (Badge, error) {
	row := q.db.QueryRow(ctx, createBadge,
		arg.TenantID,
		arg.Name,
		arg.Description,
		arg.Emoji,
		arg.Threshold,
	)
	var i Badge
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.Emoji,
		&i.Threshold,
		&i.CreatedAt,
	)
	return i, err
}

const deleteBadge = `-- name: DeleteBadge :execrows
DELETE FROM badges WHERE id = $1
`

func (q *Queries) DeleteBadge(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBadge, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const leaderboard = `-- name: Leaderboard :many
SELECT p.user_id, u.full_name, sum(p.points)::bigint AS points
FROM point_awards p JOIN users u ON u.id = p.user_id
WHERE p.created_at >= $1
GROUP BY p.user_id, u.full_name
ORDER BY points DESC, u.full_name
LIMIT $2
`

type LeaderboardParams struct {
	Since     pgtype.Timestamptz `json:"since"`
	PageLimit int32              `json:"page_limit"`
}

type LeaderboardRow struct {
	UserID   uuid.UUID `json:"user_id"`
	FullName string    `json:"full_name"`
	Points   int64     `json:"points"`
}

func (q *Queries) Leaderboard(ctx context.Context, arg LeaderboardParams) ([]LeaderboardRow, error) {
	rows, err := q.db.Query(ctx, leaderboard, arg.Since, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LeaderboardRow{}
	for rows.Next() {
		var i LeaderboardRow
		if err := rows.Scan(&i.UserID, &i.FullName, &i.Points); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBadges = `-- name: ListBadges :many
SELECT b.id, b.tenant_id, b.name, b.description, b.emoji, b.threshold, b.created_at, (SELECT count(*) FROM badge_awards a WHERE a.badge_id = b.id) AS earned_by
FROM badges b ORDER BY b.threshold
`

type ListBadgesRow struct {
	ID          uuid.UUID          `json:"id"`
	TenantID    uuid.UUID          `json:"tenant_id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Emoji       string             `json:"emoji"`
	Threshold   int32              `json:"threshold"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	EarnedBy    int64              `json:"earned_by"`
}

func (q *Queries) ListBadges(ctx context.Context) ([]ListBadgesRow, error) {
	rows, err := q.db.Query(ctx, listBadges)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBadgesRow{}
	for rows.Next() {
		var i ListBadgesRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Description,
			&i.Emoji,
			&i.Threshold,
			&i.CreatedAt,
			&i.EarnedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const myBadges = `-- name: MyBadges :many
SELECT b.id, b.tenant_id, b.name, b.description, b.emoji, b.threshold, b.created_at, a.awarded_at
FROM badge_awards a JOIN badges b ON b.id = a.badge_id
WHERE a.user_id = $1
ORDER BY a.awarded_at DESC
`

type MyBadgesRow struct {
	ID          uuid.UUID          `json:"id"`
	TenantID    uuid.UUID          `json:"tenant_id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Emoji       string             `json:"emoji"`
	Threshold   int32              `json:"threshold"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	AwardedAt   pgtype.Timestamptz `json:"awarded_at"`
}

func (q *Queries) MyBadges(ctx context.Context, userID uuid.UUID) ([]MyBadgesRow, error) {
	rows, err := q.db.Query(ctx, myBadges, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MyBadgesRow{}
	for rows.Next() {
		var i MyBadgesRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Description,
			&i.Emoji,
			&i.Threshold,
			&i.CreatedAt,
			&i.AwardedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const myPoints = `-- name: MyPoints :one
SELECT coalesce(sum(points), 0)::bigint AS points FROM point_awards WHERE user_id = $1
`

func (q *Queries) MyPoints(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, myPoints, userID)
	var points int64
	err := row.Scan(&points)
	return points, err
}

const setPointsOn = `-- name: SetPointsOn :one
UPDATE tenants SET points_on = $1 WHERE id = $2 RETURNING id, slug, name, kind, status, default_dir, locale, currency, created_at, updated_at, site_theme, custom_domain, domain_token, domain_verified_at, institution, points_on, demo
`

type SetPointsOnParams struct {
	PointsOn bool      `json:"points_on"`
	ID       uuid.UUID `json:"id"`
}

func (q *Queries) SetPointsOn(ctx context.Context, arg SetPointsOnParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, setPointsOn, arg.PointsOn, arg.ID)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Kind,
		&i.Status,
		&i.DefaultDir,
		&i.Locale,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SiteTheme,
		&i.CustomDomain,
		&i.DomainToken,
		&i.DomainVerifiedAt,
		&i.Institution,
		&i.PointsOn,
		&i.Demo,
	)
	return i, err
}
