// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scorm.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addSCORMFile = `-- name: AddSCORMFile :exec
INSERT INTO scorm_files (package_id, path, content_type, body)
VALUES ($1, $2, $3, $4)
ON CONFLICT (package_id, path) DO UPDATE SET content_type = excluded.content_type, body = excluded.body
`

type AddSCORMFileParams struct {
	PackageID   uuid.UUID `json:"package_id"`
	Path        string    `json:"path"`
	ContentType string    `json:"content_type"`
	Body        []byte    `json:"body"`
}

func (q *Queries) AddSCORMFile(ctx context.Context, arg AddSCORMFileParams) error {
	_, err := q.db.Exec(ctx, addSCORMFile,
		arg.PackageID,
		arg.Path,
		arg.ContentType,
		arg.Body,
	)
	return err
}

const createSCORMPackage = `-- name: CreateSCORMPackage :one
INSERT INTO scorm_packages (tenant_id, lesson_id, title, entry_href, version, mastery,
                            file_count, bytes, grade_item_id)
VALUES ($1, $2, $3, $4, $5, $6,
        $7, $8, $9)
RETURNING id, tenant_id, lesson_id, title, entry_href, version, mastery, file_count, bytes, grade_item_id, created_at
`

type CreateSCORMPackageParams struct {
	TenantID    uuid.UUID     `json:"tenant_id"`
	LessonID    uuid.UUID     `json:"lesson_id"`
	Title       string        `json:"title"`
	EntryHref   string        `json:"entry_href"`
	Version     string        `json:"version"`
	Mastery     *int16        `json:"mastery"`
	FileCount   int32         `json:"file_count"`
	Bytes       int64         `json:"bytes"`
	GradeItemID uuid.NullUUID `json:"grade_item_id"`
}

func (q *Queries) CreateSCORMPackage(ctx context.Context, arg CreateSCORMPackageParams) (ScormPackage, error) {
	row := q.db.QueryRow(ctx, createSCORMPackage,
		arg.TenantID,
		arg.LessonID,
		arg.Title,
		arg.EntryHref,
		arg.Version,
		arg.Mastery,
		arg.FileCount,
		arg.Bytes,
		arg.GradeItemID,
	)
	var i ScormPackage
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.LessonID,
		&i.Title,
		&i.EntryHref,
		&i.Version,
		&i.Mastery,
		&i.FileCount,
		&i.Bytes,
		&i.GradeItemID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSCORMPackage = `-- name: DeleteSCORMPackage :execrows
DELETE FROM scorm_packages WHERE lesson_id = $1
`

func (q *Queries) DeleteSCORMPackage(ctx context.Context, lessonID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSCORMPackage, lessonID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listSCORMStates = `-- name: ListSCORMStates :many
SELECT s.package_id, s.user_id, s.tenant_id, s.cmi, s.lesson_status, s.score_raw, s.suspend_data, s.location, s.total_time_s, s.updated_at, u.full_name
FROM scorm_states s JOIN users u ON u.id = s.user_id
WHERE s.package_id = $1
ORDER BY u.full_name
`

type ListSCORMStatesRow struct {
	ScormState ScormState `json:"scorm_state"`
	FullName   string     `json:"full_name"`
}

func (q *Queries) ListSCORMStates(ctx context.Context, packageID uuid.UUID) ([]ListSCORMStatesRow, error) {
	rows, err := q.db.Query(ctx, listSCORMStates, packageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSCORMStatesRow{}
	for rows.Next() {
		var i ListSCORMStatesRow
		if err := rows.Scan(
			&i.ScormState.PackageID,
			&i.ScormState.UserID,
			&i.ScormState.TenantID,
			&i.ScormState.Cmi,
			&i.ScormState.LessonStatus,
			&i.ScormState.ScoreRaw,
			&i.ScormState.SuspendData,
			&i.ScormState.Location,
			&i.ScormState.TotalTimeS,
			&i.ScormState.UpdatedAt,
			&i.FullName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sCORMFile = `-- name: SCORMFile :one
SELECT content_type, body FROM scorm_files WHERE package_id = $1 AND path = $2
`

type SCORMFileParams struct {
	PackageID uuid.UUID `json:"package_id"`
	Path      string    `json:"path"`
}

type SCORMFileRow struct {
	ContentType string `json:"content_type"`
	Body        []byte `json:"body"`
}

func (q *Queries) SCORMFile(ctx context.Context, arg SCORMFileParams) (SCORMFileRow, error) {
	row := q.db.QueryRow(ctx, sCORMFile, arg.PackageID, arg.Path)
	var i SCORMFileRow
	err := row.Scan(&i.ContentType, &i.Body)
	return i, err
}

const sCORMPackageForLesson = `-- name: SCORMPackageForLesson :one
SELECT id, tenant_id, lesson_id, title, entry_href, version, mastery, file_count, bytes, grade_item_id, created_at FROM scorm_packages WHERE lesson_id = $1
`

func (q *Queries) SCORMPackageForLesson(ctx context.Context, lessonID uuid.UUID) (ScormPackage, error) {
	row := q.db.QueryRow(ctx, sCORMPackageForLesson, lessonID)
	var i ScormPackage
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.LessonID,
		&i.Title,
		&i.EntryHref,
		&i.Version,
		&i.Mastery,
		&i.FileCount,
		&i.Bytes,
		&i.GradeItemID,
		&i.CreatedAt,
	)
	return i, err
}

const sCORMState = `-- name: SCORMState :one
SELECT package_id, user_id, tenant_id, cmi, lesson_status, score_raw, suspend_data, location, total_time_s, updated_at FROM scorm_states WHERE package_id = $1 AND user_id = $2
`

type SCORMStateParams struct {
	PackageID uuid.UUID `json:"package_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) SCORMState(ctx context.Context, arg SCORMStateParams) (ScormState, error) {
	row := q.db.QueryRow(ctx, sCORMState, arg.PackageID, arg.UserID)
	var i ScormState
	err := row.Scan(
		&i.PackageID,
		&i.UserID,
		&i.TenantID,
		&i.Cmi,
		&i.LessonStatus,
		&i.ScoreRaw,
		&i.SuspendData,
		&i.Location,
		&i.TotalTimeS,
		&i.UpdatedAt,
	)
	return i, err
}

const saveSCORMState = `-- name: SaveSCORMState :one
INSERT INTO scorm_states (package_id, user_id, tenant_id, cmi, lesson_status, score_raw,
                          suspend_data, location, total_time_s)
VALUES ($1, $2, $3, $4, $5, $6,
        $7, $8, $9)
ON CONFLICT (package_id, user_id) DO UPDATE SET
  cmi = excluded.cmi,
  lesson_status = excluded.lesson_status,
  score_raw = excluded.score_raw,
  suspend_data = excluded.suspend_data,
  location = excluded.location,
  total_time_s = greatest(scorm_states.total_time_s, excluded.total_time_s)
RETURNING package_id, user_id, tenant_id, cmi, lesson_status, score_raw, suspend_data, location, total_time_s, updated_at
`

type SaveSCORMStateParams struct {
	PackageID    uuid.UUID      `json:"package_id"`
	UserID       uuid.UUID      `json:"user_id"`
	TenantID     uuid.UUID      `json:"tenant_id"`
	Cmi          []byte         `json:"cmi"`
	LessonStatus string         `json:"lesson_status"`
	ScoreRaw     pgtype.Numeric `json:"score_raw"`
	SuspendData  string         `json:"suspend_data"`
	Location     string         `json:"location"`
	TotalTimeS   int32          `json:"total_time_s"`
}

func (q *Queries) SaveSCORMState(ctx context.Context, arg SaveSCORMStateParams) (ScormState, error) {
	row := q.db.QueryRow(ctx, saveSCORMState,
		arg.PackageID,
		arg.UserID,
		arg.TenantID,
		arg.Cmi,
		arg.LessonStatus,
		arg.ScoreRaw,
		arg.SuspendData,
		arg.Location,
		arg.TotalTimeS,
	)
	var i ScormState
	err := row.Scan(
		&i.PackageID,
		&i.UserID,
		&i.TenantID,
		&i.Cmi,
		&i.LessonStatus,
		&i.ScoreRaw,
		&i.SuspendData,
		&i.Location,
		&i.TotalTimeS,
		&i.UpdatedAt,
	)
	return i, err
}
