// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: site.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const clearCustomDomain = `-- name: ClearCustomDomain :one
UPDATE tenants SET custom_domain = NULL, domain_token = '', domain_verified_at = NULL
WHERE id = $1
RETURNING id, slug, name, kind, status, default_dir, locale, currency, created_at, updated_at, site_theme, custom_domain, domain_token, domain_verified_at, institution
`

func (q *Queries) ClearCustomDomain(ctx context.Context, id uuid.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, clearCustomDomain, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Kind,
		&i.Status,
		&i.DefaultDir,
		&i.Locale,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SiteTheme,
		&i.CustomDomain,
		&i.DomainToken,
		&i.DomainVerifiedAt,
		&i.Institution,
	)
	return i, err
}

const createSitePage = `-- name: CreateSitePage :one
INSERT INTO site_pages (tenant_id, slug, title, description, dir, blocks, nav_label, nav_order, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, tenant_id, slug, title, description, dir, blocks, status, nav_label, nav_order, updated_by, created_at, updated_at
`

type CreateSitePageParams struct {
	TenantID    uuid.UUID     `json:"tenant_id"`
	Slug        string        `json:"slug"`
	Title       string        `json:"title"`
	Description string        `json:"description"`
	Dir         TextDir       `json:"dir"`
	Blocks      []byte        `json:"blocks"`
	NavLabel    string        `json:"nav_label"`
	NavOrder    int32         `json:"nav_order"`
	UpdatedBy   uuid.NullUUID `json:"updated_by"`
}

func (q *Queries) CreateSitePage(ctx context.Context, arg CreateSitePageParams) (SitePage, error) {
	row := q.db.QueryRow(ctx, createSitePage,
		arg.TenantID,
		arg.Slug,
		arg.Title,
		arg.Description,
		arg.Dir,
		arg.Blocks,
		arg.NavLabel,
		arg.NavOrder,
		arg.UpdatedBy,
	)
	var i SitePage
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Dir,
		&i.Blocks,
		&i.Status,
		&i.NavLabel,
		&i.NavOrder,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSitePage = `-- name: DeleteSitePage :execrows
DELETE FROM site_pages WHERE id = $1
`

func (q *Queries) DeleteSitePage(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSitePage, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPublishedPage = `-- name: GetPublishedPage :one
SELECT id, slug, title, description, dir, blocks, nav_label, nav_order, updated_at, tenant_slug, tenant_name, tenant_dir, site_theme FROM published_pages WHERE tenant_slug = $1 AND slug = $2
`

type GetPublishedPageParams struct {
	TenantSlug string `json:"tenant_slug"`
	Slug       string `json:"slug"`
}

func (q *Queries) GetPublishedPage(ctx context.Context, arg GetPublishedPageParams) (PublishedPage, error) {
	row := q.db.QueryRow(ctx, getPublishedPage, arg.TenantSlug, arg.Slug)
	var i PublishedPage
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Dir,
		&i.Blocks,
		&i.NavLabel,
		&i.NavOrder,
		&i.UpdatedAt,
		&i.TenantSlug,
		&i.TenantName,
		&i.TenantDir,
		&i.SiteTheme,
	)
	return i, err
}

const getSitePage = `-- name: GetSitePage :one
SELECT id, tenant_id, slug, title, description, dir, blocks, status, nav_label, nav_order, updated_by, created_at, updated_at FROM site_pages WHERE id = $1
`

func (q *Queries) GetSitePage(ctx context.Context, id uuid.UUID) (SitePage, error) {
	row := q.db.QueryRow(ctx, getSitePage, id)
	var i SitePage
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Dir,
		&i.Blocks,
		&i.Status,
		&i.NavLabel,
		&i.NavOrder,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPublishedCourses = `-- name: ListPublishedCourses :many
SELECT id, slug, title, summary, dir, price_minor, currency, published_at, tenant_slug FROM published_courses
WHERE tenant_slug = $1
ORDER BY published_at DESC NULLS LAST
LIMIT $2
`

type ListPublishedCoursesParams struct {
	TenantSlug string `json:"tenant_slug"`
	PageLimit  int32  `json:"page_limit"`
}

func (q *Queries) ListPublishedCourses(ctx context.Context, arg ListPublishedCoursesParams) ([]PublishedCourse, error) {
	rows, err := q.db.Query(ctx, listPublishedCourses, arg.TenantSlug, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PublishedCourse{}
	for rows.Next() {
		var i PublishedCourse
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Summary,
			&i.Dir,
			&i.PriceMinor,
			&i.Currency,
			&i.PublishedAt,
			&i.TenantSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSiteNav = `-- name: ListSiteNav :many
SELECT slug, nav_label, nav_order FROM published_pages
WHERE tenant_slug = $1 AND nav_label <> ''
ORDER BY nav_order, nav_label
`

type ListSiteNavRow struct {
	Slug     string `json:"slug"`
	NavLabel string `json:"nav_label"`
	NavOrder int32  `json:"nav_order"`
}

func (q *Queries) ListSiteNav(ctx context.Context, tenantSlug string) ([]ListSiteNavRow, error) {
	rows, err := q.db.Query(ctx, listSiteNav, tenantSlug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSiteNavRow{}
	for rows.Next() {
		var i ListSiteNavRow
		if err := rows.Scan(&i.Slug, &i.NavLabel, &i.NavOrder); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSitePages = `-- name: ListSitePages :many
SELECT id, tenant_id, slug, title, description, dir, blocks, status, nav_label, nav_order, updated_by, created_at, updated_at FROM site_pages ORDER BY nav_order, title
`

func (q *Queries) ListSitePages(ctx context.Context) ([]SitePage, error) {
	rows, err := q.db.Query(ctx, listSitePages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SitePage{}
	for rows.Next() {
		var i SitePage
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Slug,
			&i.Title,
			&i.Description,
			&i.Dir,
			&i.Blocks,
			&i.Status,
			&i.NavLabel,
			&i.NavOrder,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDomainVerified = `-- name: MarkDomainVerified :one
UPDATE tenants SET domain_verified_at = now() WHERE id = $1 RETURNING id, slug, name, kind, status, default_dir, locale, currency, created_at, updated_at, site_theme, custom_domain, domain_token, domain_verified_at, institution
`

func (q *Queries) MarkDomainVerified(ctx context.Context, id uuid.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, markDomainVerified, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Kind,
		&i.Status,
		&i.DefaultDir,
		&i.Locale,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SiteTheme,
		&i.CustomDomain,
		&i.DomainToken,
		&i.DomainVerifiedAt,
		&i.Institution,
	)
	return i, err
}

const resolveDomain = `-- name: ResolveDomain :one
SELECT id, slug, name, kind, status, default_dir, locale, currency, created_at, updated_at, site_theme, custom_domain, domain_token, domain_verified_at, institution FROM resolve_domain($1)
`

func (q *Queries) ResolveDomain(ctx context.Context, customDomain string) (Tenant, error) {
	row := q.db.QueryRow(ctx, resolveDomain, customDomain)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Kind,
		&i.Status,
		&i.DefaultDir,
		&i.Locale,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SiteTheme,
		&i.CustomDomain,
		&i.DomainToken,
		&i.DomainVerifiedAt,
		&i.Institution,
	)
	return i, err
}

const setCustomDomain = `-- name: SetCustomDomain :one
UPDATE tenants SET custom_domain = $1, domain_token = $2, domain_verified_at = NULL
WHERE id = $3
RETURNING id, slug, name, kind, status, default_dir, locale, currency, created_at, updated_at, site_theme, custom_domain, domain_token, domain_verified_at, institution
`

type SetCustomDomainParams struct {
	CustomDomain *string   `json:"custom_domain"`
	DomainToken  string    `json:"domain_token"`
	ID           uuid.UUID `json:"id"`
}

func (q *Queries) SetCustomDomain(ctx context.Context, arg SetCustomDomainParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, setCustomDomain, arg.CustomDomain, arg.DomainToken, arg.ID)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Kind,
		&i.Status,
		&i.DefaultDir,
		&i.Locale,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SiteTheme,
		&i.CustomDomain,
		&i.DomainToken,
		&i.DomainVerifiedAt,
		&i.Institution,
	)
	return i, err
}

const setSitePageStatus = `-- name: SetSitePageStatus :one
UPDATE site_pages SET status = $1, updated_by = $2 WHERE id = $3 RETURNING id, tenant_id, slug, title, description, dir, blocks, status, nav_label, nav_order, updated_by, created_at, updated_at
`

type SetSitePageStatusParams struct {
	Status    PublishStatus `json:"status"`
	UpdatedBy uuid.NullUUID `json:"updated_by"`
	ID        uuid.UUID     `json:"id"`
}

func (q *Queries) SetSitePageStatus(ctx context.Context, arg SetSitePageStatusParams) (SitePage, error) {
	row := q.db.QueryRow(ctx, setSitePageStatus, arg.Status, arg.UpdatedBy, arg.ID)
	var i SitePage
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Dir,
		&i.Blocks,
		&i.Status,
		&i.NavLabel,
		&i.NavOrder,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setSiteTheme = `-- name: SetSiteTheme :one
UPDATE tenants SET site_theme = $1 WHERE id = $2 RETURNING id, slug, name, kind, status, default_dir, locale, currency, created_at, updated_at, site_theme, custom_domain, domain_token, domain_verified_at, institution
`

type SetSiteThemeParams struct {
	SiteTheme string    `json:"site_theme"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) SetSiteTheme(ctx context.Context, arg SetSiteThemeParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, setSiteTheme, arg.SiteTheme, arg.ID)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Kind,
		&i.Status,
		&i.DefaultDir,
		&i.Locale,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SiteTheme,
		&i.CustomDomain,
		&i.DomainToken,
		&i.DomainVerifiedAt,
		&i.Institution,
	)
	return i, err
}

const updateSitePage = `-- name: UpdateSitePage :one
UPDATE site_pages SET
  title       = coalesce($1, title),
  description = coalesce($2, description),
  dir         = coalesce($3, dir),
  blocks      = coalesce($4, blocks),
  nav_label   = coalesce($5, nav_label),
  nav_order   = coalesce($6, nav_order),
  updated_by  = $7
WHERE id = $8
RETURNING id, tenant_id, slug, title, description, dir, blocks, status, nav_label, nav_order, updated_by, created_at, updated_at
`

type UpdateSitePageParams struct {
	Title       *string       `json:"title"`
	Description *string       `json:"description"`
	Dir         *TextDir      `json:"dir"`
	Blocks      []byte        `json:"blocks"`
	NavLabel    *string       `json:"nav_label"`
	NavOrder    *int32        `json:"nav_order"`
	UpdatedBy   uuid.NullUUID `json:"updated_by"`
	ID          uuid.UUID     `json:"id"`
}

func (q *Queries) UpdateSitePage(ctx context.Context, arg UpdateSitePageParams) (SitePage, error) {
	row := q.db.QueryRow(ctx, updateSitePage,
		arg.Title,
		arg.Description,
		arg.Dir,
		arg.Blocks,
		arg.NavLabel,
		arg.NavOrder,
		arg.UpdatedBy,
		arg.ID,
	)
	var i SitePage
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Dir,
		&i.Blocks,
		&i.Status,
		&i.NavLabel,
		&i.NavOrder,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
