// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sso.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const deleteIdentityProvider = `-- name: DeleteIdentityProvider :execrows
DELETE FROM identity_providers WHERE tenant_id = $1
`

func (q *Queries) DeleteIdentityProvider(ctx context.Context, tenantID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteIdentityProvider, tenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getIdentityProvider = `-- name: GetIdentityProvider :one
SELECT id, tenant_id, label, issuer, client_id, client_secret, allowed_domains, join_role, auto_join, enabled, created_at, updated_at FROM identity_providers WHERE tenant_id = $1
`

func (q *Queries) GetIdentityProvider(ctx context.Context, tenantID uuid.UUID) (IdentityProvider, error) {
	row := q.db.QueryRow(ctx, getIdentityProvider, tenantID)
	var i IdentityProvider
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Label,
		&i.Issuer,
		&i.ClientID,
		&i.ClientSecret,
		&i.AllowedDomains,
		&i.JoinRole,
		&i.AutoJoin,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const joinBySSO = `-- name: JoinBySSO :exec
SELECT sso_join($1, $2, $3)
`

type JoinBySSOParams struct {
	TenantID uuid.UUID  `json:"tenant_id"`
	UserID   uuid.UUID  `json:"user_id"`
	JoinRole MemberRole `json:"join_role"`
}

func (q *Queries) JoinBySSO(ctx context.Context, arg JoinBySSOParams) error {
	_, err := q.db.Exec(ctx, joinBySSO, arg.TenantID, arg.UserID, arg.JoinRole)
	return err
}

const linkSSOUser = `-- name: LinkSSOUser :exec
SELECT sso_link_user($1, $2, $3)
`

type LinkSSOUserParams struct {
	ProviderID uuid.UUID `json:"provider_id"`
	Subject    string    `json:"subject"`
	UserID     uuid.UUID `json:"user_id"`
}

func (q *Queries) LinkSSOUser(ctx context.Context, arg LinkSSOUserParams) error {
	_, err := q.db.Exec(ctx, linkSSOUser, arg.ProviderID, arg.Subject, arg.UserID)
	return err
}

const sSOProviderByID = `-- name: SSOProviderByID :one
SELECT id, tenant_id, label, issuer, client_id, client_secret, allowed_domains, join_role, auto_join, enabled, created_at, updated_at FROM sso_provider_by_id($1)
`

func (q *Queries) SSOProviderByID(ctx context.Context, id uuid.UUID) (IdentityProvider, error) {
	row := q.db.QueryRow(ctx, sSOProviderByID, id)
	var i IdentityProvider
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Label,
		&i.Issuer,
		&i.ClientID,
		&i.ClientSecret,
		&i.AllowedDomains,
		&i.JoinRole,
		&i.AutoJoin,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const sSOProviderFor = `-- name: SSOProviderFor :one
SELECT id, tenant_id, label, issuer, client_id, client_secret, allowed_domains, join_role, auto_join, enabled, created_at, updated_at FROM sso_provider_for($1)
`

func (q *Queries) SSOProviderFor(ctx context.Context, slug string) (IdentityProvider, error) {
	row := q.db.QueryRow(ctx, sSOProviderFor, slug)
	var i IdentityProvider
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Label,
		&i.Issuer,
		&i.ClientID,
		&i.ClientSecret,
		&i.AllowedDomains,
		&i.JoinRole,
		&i.AutoJoin,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const sSOUser = `-- name: SSOUser :one
SELECT id, phone, email, full_name, password_hash, created_at, updated_at FROM sso_user_for($1, $2)
`

type SSOUserParams struct {
	ProviderID uuid.UUID `json:"provider_id"`
	Subject    string    `json:"subject"`
}

func (q *Queries) SSOUser(ctx context.Context, arg SSOUserParams) (User, error) {
	row := q.db.QueryRow(ctx, sSOUser, arg.ProviderID, arg.Subject)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Email,
		&i.FullName,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setIdentityProvider = `-- name: SetIdentityProvider :one
INSERT INTO identity_providers (tenant_id, label, issuer, client_id, client_secret,
                                allowed_domains, join_role, auto_join, enabled)
VALUES ($1, $2, $3, $4, $5,
        $6, $7, $8, $9)
ON CONFLICT (tenant_id) DO UPDATE SET
  label = excluded.label,
  issuer = excluded.issuer,
  client_id = excluded.client_id,
  client_secret = CASE WHEN excluded.client_secret = '' THEN identity_providers.client_secret
                       ELSE excluded.client_secret END,
  allowed_domains = excluded.allowed_domains,
  join_role = excluded.join_role,
  auto_join = excluded.auto_join,
  enabled = excluded.enabled
RETURNING id, tenant_id, label, issuer, client_id, client_secret, allowed_domains, join_role, auto_join, enabled, created_at, updated_at
`

type SetIdentityProviderParams struct {
	TenantID       uuid.UUID  `json:"tenant_id"`
	Label          string     `json:"label"`
	Issuer         string     `json:"issuer"`
	ClientID       string     `json:"client_id"`
	ClientSecret   string     `json:"client_secret"`
	AllowedDomains []string   `json:"allowed_domains"`
	JoinRole       MemberRole `json:"join_role"`
	AutoJoin       bool       `json:"auto_join"`
	Enabled        bool       `json:"enabled"`
}

func (q *Queries) SetIdentityProvider(ctx context.Context, arg SetIdentityProviderParams) (IdentityProvider, error) {
	row := q.db.QueryRow(ctx, setIdentityProvider,
		arg.TenantID,
		arg.Label,
		arg.Issuer,
		arg.ClientID,
		arg.ClientSecret,
		arg.AllowedDomains,
		arg.JoinRole,
		arg.AutoJoin,
		arg.Enabled,
	)
	var i IdentityProvider
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Label,
		&i.Issuer,
		&i.ClientID,
		&i.ClientSecret,
		&i.AllowedDomains,
		&i.JoinRole,
		&i.AutoJoin,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const startSSOLogin = `-- name: StartSSOLogin :one
SELECT state, provider_id, nonce, verifier, redirect_uri, expires_at, created_at FROM sso_login_start($1, $2, $3, $4, $5, $6)
`

type StartSSOLoginParams struct {
	State       string    `json:"state"`
	ProviderID  uuid.UUID `json:"provider_id"`
	Nonce       string    `json:"nonce"`
	Verifier    string    `json:"verifier"`
	RedirectUri string    `json:"redirect_uri"`
	TtlS        int32     `json:"ttl_s"`
}

func (q *Queries) StartSSOLogin(ctx context.Context, arg StartSSOLoginParams) (SsoLogin, error) {
	row := q.db.QueryRow(ctx, startSSOLogin,
		arg.State,
		arg.ProviderID,
		arg.Nonce,
		arg.Verifier,
		arg.RedirectUri,
		arg.TtlS,
	)
	var i SsoLogin
	err := row.Scan(
		&i.State,
		&i.ProviderID,
		&i.Nonce,
		&i.Verifier,
		&i.RedirectUri,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const takeSSOLogin = `-- name: TakeSSOLogin :one
SELECT state, provider_id, nonce, verifier, redirect_uri, expires_at, created_at FROM sso_login_take($1)
`

func (q *Queries) TakeSSOLogin(ctx context.Context, state string) (SsoLogin, error) {
	row := q.db.QueryRow(ctx, takeSSOLogin, state)
	var i SsoLogin
	err := row.Scan(
		&i.State,
		&i.ProviderID,
		&i.Nonce,
		&i.Verifier,
		&i.RedirectUri,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
