// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenants.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getTenant = `-- name: GetTenant :one
SELECT id, slug, name, kind, status, default_dir, locale, currency, created_at, updated_at FROM tenants WHERE id = $1
`

func (q *Queries) GetTenant(ctx context.Context, id uuid.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenant, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Kind,
		&i.Status,
		&i.DefaultDir,
		&i.Locale,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const provisionTenant = `-- name: ProvisionTenant :one
SELECT id, slug, name, kind, status, default_dir, locale, currency, created_at, updated_at FROM provision_tenant($1, $2, $3, $4, $5, $6)
`

type ProvisionTenantParams struct {
	Slug       string     `json:"slug"`
	Name       string     `json:"name"`
	Kind       TenantKind `json:"kind"`
	DefaultDir TextDir    `json:"default_dir"`
	Locale     string     `json:"locale"`
	Currency   string     `json:"currency"`
}

func (q *Queries) ProvisionTenant(ctx context.Context, arg ProvisionTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, provisionTenant,
		arg.Slug,
		arg.Name,
		arg.Kind,
		arg.DefaultDir,
		arg.Locale,
		arg.Currency,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Kind,
		&i.Status,
		&i.DefaultDir,
		&i.Locale,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const resolveTenant = `-- name: ResolveTenant :one
SELECT resolve_tenant FROM resolve_tenant($1)
`

func (q *Queries) ResolveTenant(ctx context.Context, slug string) (interface{}, error) {
	row := q.db.QueryRow(ctx, resolveTenant, slug)
	var resolve_tenant interface{}
	err := row.Scan(&resolve_tenant)
	return resolve_tenant, err
}
