// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenants.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getTenant = `-- name: GetTenant :one
SELECT id, slug, name, kind, status, default_dir, locale, currency, created_at, updated_at, site_theme, custom_domain, domain_token, domain_verified_at, institution, points_on FROM tenants WHERE id = $1
`

func (q *Queries) GetTenant(ctx context.Context, id uuid.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenant, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Kind,
		&i.Status,
		&i.DefaultDir,
		&i.Locale,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SiteTheme,
		&i.CustomDomain,
		&i.DomainToken,
		&i.DomainVerifiedAt,
		&i.Institution,
		&i.PointsOn,
	)
	return i, err
}

const listUserTenants = `-- name: ListUserTenants :many
SELECT user_id, role, id, slug, name, kind, status, default_dir, locale, currency FROM user_tenants WHERE user_id = $1 ORDER BY name
`

func (q *Queries) ListUserTenants(ctx context.Context, userID uuid.UUID) ([]UserTenant, error) {
	rows, err := q.db.Query(ctx, listUserTenants, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserTenant{}
	for rows.Next() {
		var i UserTenant
		if err := rows.Scan(
			&i.UserID,
			&i.Role,
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Kind,
			&i.Status,
			&i.DefaultDir,
			&i.Locale,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const provisionTenant = `-- name: ProvisionTenant :one
SELECT id, slug, name, kind, status, default_dir, locale, currency, created_at, updated_at, site_theme, custom_domain, domain_token, domain_verified_at, institution, points_on FROM provision_tenant($1, $2, $3, $4, $5, $6)
`

type ProvisionTenantParams struct {
	Slug       string     `json:"slug"`
	Name       string     `json:"name"`
	Kind       TenantKind `json:"kind"`
	DefaultDir TextDir    `json:"default_dir"`
	Locale     string     `json:"locale"`
	Currency   string     `json:"currency"`
}

func (q *Queries) ProvisionTenant(ctx context.Context, arg ProvisionTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, provisionTenant,
		arg.Slug,
		arg.Name,
		arg.Kind,
		arg.DefaultDir,
		arg.Locale,
		arg.Currency,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Kind,
		&i.Status,
		&i.DefaultDir,
		&i.Locale,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SiteTheme,
		&i.CustomDomain,
		&i.DomainToken,
		&i.DomainVerifiedAt,
		&i.Institution,
		&i.PointsOn,
	)
	return i, err
}

const resolveTenant = `-- name: ResolveTenant :one
SELECT id, slug, name, kind, status, default_dir, locale, currency, created_at, updated_at, site_theme, custom_domain, domain_token, domain_verified_at, institution, points_on FROM resolve_tenant($1)
`

func (q *Queries) ResolveTenant(ctx context.Context, slug string) (Tenant, error) {
	row := q.db.QueryRow(ctx, resolveTenant, slug)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Kind,
		&i.Status,
		&i.DefaultDir,
		&i.Locale,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SiteTheme,
		&i.CustomDomain,
		&i.DomainToken,
		&i.DomainVerifiedAt,
		&i.Institution,
		&i.PointsOn,
	)
	return i, err
}
