// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const findUserForAuth = `-- name: FindUserForAuth :one
SELECT auth_find_user FROM auth_find_user($1, $2)
`

type FindUserForAuthParams struct {
	Phone string `json:"phone"`
	Email string `json:"email"`
}

func (q *Queries) FindUserForAuth(ctx context.Context, arg FindUserForAuthParams) (interface{}, error) {
	row := q.db.QueryRow(ctx, findUserForAuth, arg.Phone, arg.Email)
	var auth_find_user interface{}
	err := row.Scan(&auth_find_user)
	return auth_find_user, err
}

const getUser = `-- name: GetUser :one
SELECT id, phone, email, full_name, password_hash, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Email,
		&i.FullName,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUserMemberships = `-- name: ListUserMemberships :many
SELECT auth_memberships FROM auth_memberships($1)
`

func (q *Queries) ListUserMemberships(ctx context.Context, userID uuid.UUID) ([]interface{}, error) {
	rows, err := q.db.Query(ctx, listUserMemberships, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []interface{}{}
	for rows.Next() {
		var auth_memberships interface{}
		if err := rows.Scan(&auth_memberships); err != nil {
			return nil, err
		}
		items = append(items, auth_memberships)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const signupUser = `-- name: SignupUser :one
SELECT id, phone, email, full_name, password_hash, created_at, updated_at FROM signup_user($1, $2, $3, $4)
`

type SignupUserParams struct {
	Phone        string `json:"phone"`
	Email        string `json:"email"`
	FullName     string `json:"full_name"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) SignupUser(ctx context.Context, arg SignupUserParams) (User, error) {
	row := q.db.QueryRow(ctx, signupUser,
		arg.Phone,
		arg.Email,
		arg.FullName,
		arg.PasswordHash,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Email,
		&i.FullName,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
