-- The API connects as fajr_app, which is subject to row-level security.
CREATE ROLE fajr_app LOGIN PASSWORD 'fajr' NOSUPERUSER NOCREATEDB NOCREATEROLE NOBYPASSRLS;
GRANT CONNECT ON DATABASE fajr TO fajr_app;
GRANT USAGE ON SCHEMA public TO fajr_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO fajr_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE ON SEQUENCES TO fajr_app;
